ALTER TABLE net_worth_snapshots ADD COLUMN snapshot_month TEXT;
ALTER TABLE net_worth_snapshots ADD COLUMN snapshot_date TEXT;
ALTER TABLE net_worth_snapshots ADD COLUMN assets_total INTEGER;
ALTER TABLE net_worth_snapshots ADD COLUMN investments_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE net_worth_snapshots ADD COLUMN cash_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE net_worth_snapshots ADD COLUMN other_assets_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE net_worth_snapshots ADD COLUMN liabilities_total INTEGER;
ALTER TABLE net_worth_snapshots ADD COLUMN valuation_status TEXT NOT NULL DEFAULT 'complete';
ALTER TABLE net_worth_snapshots ADD COLUMN priced_assets INTEGER NOT NULL DEFAULT 0;
ALTER TABLE net_worth_snapshots ADD COLUMN missing_assets INTEGER NOT NULL DEFAULT 0;
ALTER TABLE net_worth_snapshots ADD COLUMN stale_assets INTEGER NOT NULL DEFAULT 0;
ALTER TABLE net_worth_snapshots ADD COLUMN generated_at TEXT;
ALTER TABLE net_worth_snapshots ADD COLUMN updated_at TEXT;
ALTER TABLE net_worth_snapshots ADD COLUMN locked_at TEXT;
ALTER TABLE net_worth_snapshots ADD COLUMN unlocked_at TEXT;
ALTER TABLE net_worth_snapshots ADD COLUMN content_hash TEXT;
UPDATE net_worth_snapshots SET snapshot_month=month, snapshot_date=month || '-31', assets_total=assets, liabilities_total=liabilities, generated_at=COALESCE(calculated_at,created_at), updated_at=COALESCE(calculated_at,created_at) WHERE snapshot_month IS NULL;
CREATE INDEX IF NOT EXISTS idx_net_worth_snapshots_user_snapshot_date ON net_worth_snapshots (user_id, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_net_worth_snapshots_user_status ON net_worth_snapshots (user_id, valuation_status);
