import type { D1Database } from '@cloudflare/workers-types';

export type BudgetStatus = 'under_budget'|'approaching_limit'|'over_budget'|'completed'|'no_activity'|'insufficient_data';
const OWNED = new Set(['wallet','deposit','portfolio','credit_card','cicilan']);
const DAY_MS = 86400000;
export const CASH_FLOW_DEFINITIONS = {
  income: 'Outside-to-owned-account ordinary Ledger movements.',
  ordinaryExpenses: 'Owned-account-to-outside Ledger movements, excluding investment, transfer, and debt-payment classifications.',
  transfers: 'Movements with both endpoints owned by the user; excluded from income and expense.',
  debtPayments: 'Wallet-to-cicilan, wallet-to-credit-card, or debt_payment classified movements; shown separately and deduplicated from ordinary expenses.',
  investmentContributions: 'Cash moving to portfolios or investment-classified categories; shown separately from consumption expenses.',
  savingsAmount: 'income − ordinary expenses − debt payments.',
  savingsRate: 'savings amount / income; null when income is zero.',
};

function finite(n: any, fallback = 0) { const v = Number(n); return Number.isFinite(v) ? v : fallback; }
function ym(d: Date) { return d.toISOString().slice(0,7); }
function endOfMonth(month: string) { const [y,m]=month.split('-').map(Number); return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10); }
function daysInMonth(month: string) { return Number(endOfMonth(month).slice(8,10)); }
function elapsed(month: string) { const today = new Date(); if (ym(today) !== month) return daysInMonth(month); return Math.max(1, today.getUTCDate()); }
function classify(c: any) { return c?.classification || (c?.type === 'income' ? 'income' : c?.is_debt_service ? 'debt_payment' : 'variable'); }
function isTransfer(m:any){ return OWNED.has(m.src_kind) && OWNED.has(m.dst_kind); }
function isIncome(m:any){ return m.src_kind == null && OWNED.has(m.dst_kind); }
function isExpense(m:any){ return OWNED.has(m.src_kind) && m.dst_kind == null; }
function merchant(desc:string|null){ return String(desc||'').toLowerCase().replace(/[^a-z0-9 ]/g,'').split(/\s+/).slice(0,3).join(' ') || 'unknown'; }

export async function getCategories(db:D1Database, userId:number){
  const res = await db.prepare(`SELECT c.*, cc.classification FROM categories c LEFT JOIN category_classifications cc ON cc.category_id=c.id AND cc.user_id=c.user_id WHERE c.user_id=?`).bind(userId).all<any>();
  return res.results || [];
}
export async function getMovements(db:D1Database,userId:number,from:string,to:string){
  const res = await db.prepare(`SELECT * FROM movements WHERE user_id=? AND date BETWEEN ? AND ? ORDER BY date,id`).bind(userId,from,to).all<any>();
  return res.results || [];
}
export async function getBudgets(db:D1Database,userId:number,month?:string,status?:string){
  let sql=`SELECT b.*, COALESCE(b.amount,b.budget_amount) AS effective_base_amount, c.name category_name FROM budgets b LEFT JOIN categories c ON c.id=b.category_id AND c.user_id=b.user_id WHERE b.user_id=?`;
  const args:any[]=[userId]; if(month){ sql+=` AND (b.month=? OR (b.start_date<=? AND b.end_date>=?))`; args.push(month,`${month}-31`,`${month}-01`); } if(status){ sql+=` AND b.status=?`; args.push(status); }
  const res=await db.prepare(sql+` ORDER BY b.status,b.month DESC,b.id`).bind(...args).all<any>(); return res.results||[];
}
export function movementBuckets(movements:any[], categories:any[]){
  const cats=new Map(categories.map((c:any)=>[c.id,c])); let income=0, ordinaryExpenses=0, fixedExpenses=0, variableExpenses=0, discretionaryExpenses=0, debtPayments=0, investmentContributions=0, recurringExpenses=0, oneTimeExpenses=0, refunds=0, transfers=0;
  for(const m of movements){ const cls=classify(cats.get(m.category_id)); const amt=finite(m.amount); if(isTransfer(m)){ transfers+=amt; if(m.dst_kind==='portfolio') investmentContributions+=amt; if(m.dst_kind==='cicilan'||m.dst_kind==='credit_card') debtPayments+=amt; continue; } if(isIncome(m)){ if(/refund|reversal|cashback/i.test(m.description||'')){ refunds+=amt; ordinaryExpenses-=amt; } else income+=amt; continue; } if(isExpense(m)){ if(cls==='investment'){ investmentContributions+=amt; continue; } if(cls==='debt_payment'){ debtPayments+=amt; continue; } ordinaryExpenses+=amt; if(cls==='fixed'||m.recurring_id) fixedExpenses+=amt; else if(cls==='discretionary') discretionaryExpenses+=amt; else variableExpenses+=amt; if(m.recurring_id) recurringExpenses+=amt; else oneTimeExpenses+=amt; }}
  return {income, ordinaryExpenses, fixedExpenses, variableExpenses, discretionaryExpenses, debtPayments, investmentContributions, recurringExpenses, oneTimeExpenses, refunds, transfers};
}
export async function calculateBudgetRows(db:D1Database,userId:number,month:string){
  const [budgets,cats,mv]=await Promise.all([getBudgets(db,userId,month),getCategories(db,userId),getMovements(db,userId,`${month}-01`,endOfMonth(month))]);
  const byCat=new Map<number,number>(); for(const m of mv){ if(isExpense(m)) byCat.set(m.category_id, (byCat.get(m.category_id)||0)+finite(m.amount)); if(isIncome(m)&&/refund|reversal|cashback/i.test(m.description||'')) byCat.set(m.category_id,(byCat.get(m.category_id)||0)-finite(m.amount)); }
  const de=elapsed(month), dim=daysInMonth(month); return budgets.map((b:any)=>{ const base=finite(b.effective_base_amount||b.amount||b.budget_amount); const roll=finite(b.rollover_amount); const amount=base+roll; const actual=b.budget_type==='monthly_total' ? Array.from(byCat.values()).reduce((s,v)=>s+v,0) : finite(byCat.get(b.category_id)); const used=amount>0? actual/amount : null; const projected=de>0? Math.round(actual/de*dim):null; const remaining=amount-actual; let status:BudgetStatus='under_budget'; const warnings:string[]=[]; if(actual===0) status='no_activity'; if(!amount) status='insufficient_data'; else if(actual>amount) {status='over_budget'; warnings.push('Budget exceeded.');} else if(used!==null && used>=finite(b.alert_percent,0.8)) {status='approaching_limit'; warnings.push(`Budget is above ${Math.round(finite(b.alert_percent,0.8)*100)}%.`);} if(b.status==='archived') status='completed'; return {...b,budget_amount:base,base_amount:base,effective_budget:amount,actual_spending:actual,actual,remaining_amount:remaining,remaining,used_percentage:used,rollover_amount:roll,projected_month_end_spending:projected,days_elapsed:de,days_remaining:Math.max(0,dim-de),daily_safe_to_spend:Math.max(0,Math.floor(remaining/Math.max(1,dim-de))),status,warnings}; });
}
export async function monthlyCashFlow(db:D1Database,userId:number,month:string){ const cats=await getCategories(db,userId); const mv=await getMovements(db,userId,`${month}-01`,endOfMonth(month)); const parts=movementBuckets(mv,cats); const de=elapsed(month), dim=daysInMonth(month); const projected=Math.round(parts.ordinaryExpenses/de*dim); const savingsAmount=parts.income-parts.ordinaryExpenses-parts.debtPayments; return {month,total_income:parts.income,total_expenses:parts.ordinaryExpenses,net_cash_flow:parts.income-parts.ordinaryExpenses,savings_amount:savingsAmount,savings_rate:parts.income>0?savingsAmount/parts.income:null,fixed_expenses:parts.fixedExpenses,variable_expenses:parts.variableExpenses,discretionary_expenses:parts.discretionaryExpenses,debt_payments:parts.debtPayments,investment_contributions:parts.investmentContributions,recurring_expenses:parts.recurringExpenses,one_time_expenses:parts.oneTimeExpenses,refunds:parts.refunds,transfers:parts.transfers,average_daily_spending:parts.ordinaryExpenses/de,projected_month_end_expense:projected,projected_month_end_surplus_or_deficit:parts.income-projected-parts.debtPayments,definitions:CASH_FLOW_DEFINITIONS}; }
export async function categoryAnalytics(db:D1Database,userId:number,month:string){ const cats=await getCategories(db,userId); const budgets=await calculateBudgetRows(db,userId,month); const mv=await getMovements(db,userId,`${month.slice(0,4)}-01-01`,endOfMonth(month)); const cur=mv.filter(m=>m.date.startsWith(month)&&isExpense(m)); const prevMonth=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7))-2,1)).toISOString().slice(0,7); return cats.filter(c=>c.type==='expense').map(c=>{ const cm=cur.filter(m=>m.category_id===c.id); const curSum=cm.reduce((s,m)=>s+finite(m.amount),0); const prev=mv.filter(m=>m.date.startsWith(prevMonth)&&m.category_id===c.id&&isExpense(m)).reduce((s,m)=>s+finite(m.amount),0); const last3=mv.filter(m=>m.category_id===c.id&&isExpense(m)).reduce((s,m)=>s+finite(m.amount),0)/3; const budget=budgets.find((b:any)=>b.category_id===c.id); const largest=cm.slice().sort((a,b)=>b.amount-a.amount)[0]||null; const recurring=cm.filter(m=>m.recurring_id).reduce((s,m)=>s+finite(m.amount),0); return {category_id:c.id,category_name:c.name,classification:classify(c),current_month_spending:curSum,previous_month_spending:prev,change_amount:curSum-prev,change_percentage:prev?((curSum-prev)/prev):null,three_month_average:Math.round(last3),six_month_average:Math.round(last3/2),budget_amount:budget?.effective_budget??null,budget_used_percentage:budget?.used_percentage??null,transaction_count:cm.length,average_transaction_size:cm.length?curSum/cm.length:null,largest_transaction:largest,recurring_portion:recurring,discretionary_portion:classify(c)==='discretionary'?curSum:0}; }); }
export async function recurringCandidates(db:D1Database,userId:number){ const to=new Date().toISOString().slice(0,10); const from=new Date(Date.now()-180*DAY_MS).toISOString().slice(0,10); const mv=(await getMovements(db,userId,from,to)).filter(isExpense); const groups=new Map<string,any[]>(); for(const m of mv){ const key=[merchant(m.description),m.category_id,m.src_kind,m.src_id].join('|'); groups.set(key,[...(groups.get(key)||[]),m]); } const out:any[]=[]; for(const [key,arr] of groups){ if(arr.length<3) continue; arr.sort((a,b)=>a.date.localeCompare(b.date)); const avg=arr.reduce((s,m)=>s+m.amount,0)/arr.length; const diffs=arr.slice(1).map((m,i)=>(new Date(m.date).getTime()-new Date(arr[i].date).getTime())/DAY_MS); const avgDiff=diffs.reduce((s,d)=>s+d,0)/diffs.length; if(diffs.some(d=>Math.abs(d-avgDiff)>10) || arr.some(m=>Math.abs(m.amount-avg)/avg>0.2)) continue; const frequency=avgDiff<10?'weekly':avgDiff<45?'monthly':'yearly'; const monthly=frequency==='weekly'?avg*4.345:frequency==='monthly'?avg:avg/12; out.push({merchant:key.split('|')[0],typical_amount:Math.round(avg),frequency,last_occurrence:arr[arr.length-1].date,next_expected_date:new Date(new Date(arr[arr.length-1].date).getTime()+avgDiff*DAY_MS).toISOString().slice(0,10),confidence:Math.min(0.95,0.5+arr.length*0.1),status:'candidate',monthly_equivalent_cost:Math.round(monthly),annual_equivalent_cost:Math.round(monthly*12),requires_confirmation:true}); } return out; }
export async function alerts(db:D1Database,userId:number,month:string){ const budgets=await calculateBudgetRows(db,userId,month); const cf=await monthlyCashFlow(db,userId,month); const cats=await categoryAnalytics(db,userId,month); const list:any[]=[]; const push=(a:any)=>list.push({...a,generated_date:new Date().toISOString().slice(0,10),dismissible:true}); for(const b of budgets){ if(b.status==='approaching_limit') push({alert_type:'budget_80',severity:'warning',title:'Category budget above alert threshold',explanation:`${b.category_name} has used ${Math.round((b.used_percentage||0)*100)}% of its budget.`,affected_category_id:b.category_id,current_value:b.actual,comparison_value:b.effective_budget,threshold:b.alert_percent}); if(b.status==='over_budget') push({alert_type:'budget_exceeded',severity:'critical',title:'Category budget exceeded',explanation:`${b.category_name} is over budget by Rp${Math.abs(b.remaining_amount).toLocaleString('id-ID')}.`,affected_category_id:b.category_id,current_value:b.actual,comparison_value:b.effective_budget,threshold:1}); } if(cf.projected_month_end_surplus_or_deficit<0) push({alert_type:'projected_deficit',severity:'critical',title:'Projected month-end deficit',explanation:'Projected expenses and debt payments are above income for this month.',current_value:cf.projected_month_end_surplus_or_deficit,comparison_value:0,threshold:0}); if(cf.savings_rate!==null && cf.savings_rate<0.1) push({alert_type:'low_savings_rate',severity:'warning',title:'Savings rate below target',explanation:'Savings rate is below the 10% tracking threshold. This is not financial advice.',current_value:cf.savings_rate,comparison_value:0.1,threshold:0.1}); for(const c of cats){ if((c.change_percentage||0)>0.5) push({alert_type:'spending_increase',severity:'info',title:'Category spending increased',explanation:`${c.category_name} spending is more than 50% above the previous month.`,affected_category_id:c.category_id,current_value:c.current_month_spending,comparison_value:c.previous_month_spending,threshold:0.5}); if(c.largest_transaction && c.average_transaction_size && c.largest_transaction.amount>c.average_transaction_size*3) push({alert_type:'unusual_transaction',severity:'warning',title:'Unusually large transaction',explanation:'A transaction is more than 3× this category average.',affected_transaction_id:c.largest_transaction.id,current_value:c.largest_transaction.amount,comparison_value:c.average_transaction_size,threshold:3}); } return list; }
