import { describe, expect, it } from 'vitest';
import { zipSync, strToU8 } from 'fflate';
import { NseBhavcopyProvider, nseUdKiffUrl } from '../src/server/market-data/india/nse-bhavcopy';
import { YahooFinanceProvider } from '../src/server/market-data/india/yahoo-finance';
import { MfApiProvider } from '../src/server/market-data/india/mfapi';

const resp=(body:any, init:any={})=>new Response((body instanceof Uint8Array?body:typeof body==='string'?body:JSON.stringify(body)) as any,init);
const zipCsv=(csv:string)=>zipSync({'BhavCopy_NSE_CM_0_0_0_20260701_F_0000.csv':strToU8(csv)});
const assets=[{id:1,symbol:'RELIANCE',exchange:'NSE',provider_symbol:'RELIANCE'},{id:2,symbol:'ETF',exchange:'NSE',provider_symbol:'ETF'}];

describe('NseBhavcopyProvider',()=>{
  it('builds the current CM-UDiFF archive filename',()=>expect(nseUdKiffUrl('2026-07-01')).toContain('BhavCopy_NSE_CM_0_0_0_20260701_F_0000.csv.zip'));

  it('accepts ZIP by magic bytes with generic content-type',async()=>{ const p=new NseBhavcopyProvider(async()=>resp(zipCsv('TckrSymb,SctySrs,Sgmt,TradDt,ClsPric\nRELIANCE,EQ,CM,2026-07-01,10\n'),{status:200,headers:{'content-type':'application/octet-stream'}}) as any); const r=await p.fetchPrices({targetDate:'2026-07-01',assets}); expect(r.prices[0].close).toBe('10'); });
  it('returns structured errors for HTML, JSON and HTTP failures',async()=>{ const cases:any[]=[[200,'<html>blocked</html>','text/html','NOT_ZIP'],[200,{error:'bad'},'application/json','JSON_ERROR'],[403,'no','text/plain','HTTP_403'],[404,'no','text/plain','HTTP_404'],[429,'no','text/plain','HTTP_429'],[503,'no','text/plain','HTTP_5XX']]; for(const [status,body,ct,code] of cases){ const p=new NseBhavcopyProvider(async()=>resp(body,{status,headers:{'content-type':ct}}) as any); const r:any=await p.fetchPrices({targetDate:'2026-07-01',assets}); expect(r.prices).toHaveLength(0); expect(r.providerError.code).toBe(code); } });
  it('follows a 302 redirect to a ZIP',async()=>{ let calls=0; const p=new NseBhavcopyProvider((async(url:string)=>{calls++; return calls===1?resp('',{status:302,headers:{location:'https://example.test/file.zip'}}):resp(zipCsv('TckrSymb,SctySrs,Sgmt,TradDt,ClsPric\nRELIANCE,EQ,CM,2026-07-01,10\n'),{status:200});}) as any); expect((await p.fetchPrices({targetDate:'2026-07-01',assets})).prices).toHaveLength(1); expect(calls).toBe(2); });
  it('reports invalid ZIP and wrong trade date',async()=>{ let p=new NseBhavcopyProvider(async()=>resp(new Uint8Array([0x50,0x4b,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]),{status:200}) as any); expect(((await p.fetchPrices({targetDate:'2026-07-01',assets})) as any).providerError.code).toBe('INVALID_ZIP'); p=new NseBhavcopyProvider(async()=>resp(zipCsv('TckrSymb,SctySrs,Sgmt,TradDt,ClsPric\nRELIANCE,EQ,CM,2026-06-30,10\n'),{status:200}) as any); expect(((await p.fetchPrices({targetDate:'2026-07-01',assets})) as any).providerError.code).toBe('WRONG_TRADE_DATE'); });
  it('parses valid ZIP fixtures with BOM, CRLF, quotes, reordered and extra columns',async()=>{ const csv='\uFEFFExtra,ClsPric,TradDt,SctySrs,TckrSymb,Sgmt\r\n"x","1410.50","2026-07-01","EQ","RELIANCE","CM"\r\n'; const p=new NseBhavcopyProvider(async()=>resp(zipCsv(csv),{status:200,headers:{'content-type':'application/zip'}}) as any); const r=await p.fetchPrices({targetDate:'2026-07-01',assets}); expect(r.prices[0]).toMatchObject({symbol:'RELIANCE',close:'1410.5',sourceType:'official_close'}); });
  it('rejects invalid ZIP, HTML, empty payload, wrong dates, missing closes and invalid prices safely',async()=>{ for(const body of ['not zip','<html>blocked</html>',new Uint8Array()]){ const p=new NseBhavcopyProvider(async()=>resp(body,{status:200,headers:{'content-type':String(body).startsWith('<')?'text/html':'application/zip'}}) as any); expect((await p.fetchPrices({targetDate:'2026-07-01',assets})).prices).toHaveLength(0); } const csv='TckrSymb,SctySrs,Sgmt,TradDt,ClsPric\nRELIANCE,EQ,CM,2026-06-30,10\nTCS,EQ,CM,2026-07-01,\nINFY,EQ,CM,2026-07-01,0\n'; const p=new NseBhavcopyProvider(async()=>resp(zipCsv(csv),{status:200,headers:{'content-type':'application/zip'}}) as any); expect((await p.fetchPrices({targetDate:'2026-07-01',assets})).prices).toHaveLength(0); });
  it('resolves duplicate symbols deterministically and prefers EQ while allowing ETF-compatible BE series',async()=>{ const csv='TckrSymb,SctySrs,Sgmt,TradDt,ClsPric\nRELIANCE,BE,CM,2026-07-01,99\nRELIANCE,EQ,CM,2026-07-01,100\nETF,BE,CM,2026-07-01,25\n'; const p=new NseBhavcopyProvider(async()=>resp(zipCsv(csv),{status:200,headers:{'content-type':'application/zip'}}) as any); const r=await p.fetchPrices({targetDate:'2026-07-01',assets}); expect(r.prices.find(x=>x.symbol==='RELIANCE')?.close).toBe('100'); expect(r.prices.find(x=>x.symbol==='ETF')?.series).toBe('BE'); });
  it('returns symbol not found as empty prices rather than destructive failure',async()=>{ const p=new NseBhavcopyProvider(async()=>resp(zipCsv('TckrSymb,SctySrs,Sgmt,TradDt,ClsPric\nTCS,EQ,CM,2026-07-01,10\n'),{status:200,headers:{'content-type':'application/zip'}}) as any); expect((await p.fetchPrices({targetDate:'2026-07-01',assets:[assets[0]]})).prices).toHaveLength(0); });
});

describe('YahooFinanceProvider',()=>{
  const chart=(over:any={})=>({chart:{result:[{meta:{currency:'INR',regularMarketTime:1782864000,regularMarketPrice:10,symbol:'RELIANCE.NS',exchangeName:'NSI',...over.meta},timestamp:[1782864000],indicators:{quote:[{close:[Object.prototype.hasOwnProperty.call(over,'close')?over.close:9]}]}}],error:over.error}});
  it('uses valid regularMarketPrice and daily-close fallback',async()=>{ const p=new YahooFinanceProvider(async()=>resp(chart(),{status:200}) as any); expect((await p.fetchPrices({targetDate:'2026-07-01',assets:[{id:1,provider_symbol:'RELIANCE.NS',exchange:'NSE'}]})).prices[0].sourceType).toBe('yahoo_market_price'); const f=new YahooFinanceProvider(async()=>resp(chart({meta:{regularMarketPrice:null},close:11}),{status:200}) as any); expect((await f.fetchPrices({targetDate:'2026-07-01',assets:[{id:1,provider_symbol:'RELIANCE.NS',exchange:'NSE'}]})).prices[0]).toMatchObject({close:'11',sourceType:'yahoo_daily_close'}); });
  it('handles 404, 429, 5xx, malformed JSON, chart.error, wrong currency, stale timestamp and null closes',async()=>{ const cases=[async()=>resp('',{status:404}),async()=>resp('',{status:429}),async()=>resp('',{status:500}),async()=>new Response('{bad'),async()=>resp({chart:{error:{description:'bad'}}}),async()=>resp(chart({meta:{currency:'USD'}})),async()=>resp(chart({meta:{regularMarketTime:1}})),async()=>resp(chart({meta:{regularMarketPrice:null},close:null}))]; for(const f of cases){ const p=new YahooFinanceProvider(f as any,1); expect((await p.fetchPrices({targetDate:'2026-07-01',assets:[{id:1,provider_symbol:'BAD.NS',exchange:'NSE'}]})).prices).toHaveLength(0); } });
  it('derives .NS for NSE symbols and prefers explicit Yahoo symbols',async()=>{ let requested:string[]=[]; const p=new YahooFinanceProvider((async(url:string)=>{requested.push(url);return resp(chart(),{status:200}) as any}) as any,1); await p.fetchPrices({targetDate:'2026-07-01',assets:[{id:1,provider_symbol:'HINDALCO',exchange:'NSE'},{id:2,yahoo_symbol:'CUSTOM.BO',provider_symbol:'IGNORED',exchange:'NSE'}]}); expect(decodeURIComponent(requested[0])).toContain('HINDALCO.NS'); expect(decodeURIComponent(requested[1])).toContain('CUSTOM.BO'); });
  it('respects configured concurrency limit',async()=>{ let active=0,max=0; const p=new YahooFinanceProvider(async()=>{active++; max=Math.max(max,active); await new Promise(r=>setTimeout(r,5)); active--; return resp(chart(),{status:200});},4); await p.fetchPrices({targetDate:'2026-07-01',assets:Array.from({length:12},(_,i)=>({id:i+1,provider_symbol:`S${i}.NS`,exchange:'NSE'}))}); expect(max).toBeLessThanOrEqual(4); });
});

describe('MfApiProvider',()=>{
  it('parses successful NAV with DD-MM-YYYY dates',async()=>{ const p=new MfApiProvider(async()=>resp({status:'SUCCESS',meta:{scheme_code:'122639'},data:[{date:'01-07-2026',nav:'123.45'}]},{status:200}) as any); expect((await p.fetchPrices({targetDate:'2026-07-01',assets:[{id:1,provider_scheme_code:'122639'}]})).prices[0]).toMatchObject({tradeDate:'2026-07-01',close:'123.45'}); });
  it('rejects stale NAV, invalid NAV, mismatched scheme code, provider error and no newer NAV',async()=>{ const cases=[{status:'SUCCESS',meta:{scheme_code:'122639'},data:[{date:'01-07-2026',nav:'0'}]},{status:'SUCCESS',meta:{scheme_code:'999'},data:[{date:'01-07-2026',nav:'1'}]},{status:'FAILURE',data:[]},{status:'SUCCESS',meta:{scheme_code:'122639'},data:[]}]; for(const body of cases){ const p=new MfApiProvider(async()=>resp(body,{status:200}) as any); expect((await p.fetchPrices({targetDate:'2026-07-01',assets:[{id:1,provider_scheme_code:'122639',last_provider_trade_date:'2026-07-02'}]})).prices).toHaveLength(0); } const p=new MfApiProvider(async()=>resp('',{status:503}) as any); expect((await p.fetchPrices({targetDate:'2026-07-01',assets:[{id:1,provider_scheme_code:'122639'}]})).prices).toHaveLength(0); });
});
