import { describe, it, expect, vi, afterEach } from 'vitest';
import { MarketstackProvider } from '../src/server/market-data/marketstack';

afterEach(()=>vi.restoreAllMocks());
function mockJson(status:number, body:any){ vi.stubGlobal('fetch', vi.fn(async()=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}}))); }

describe('Marketstack EOD provider',()=>{
  it('parses valid NSE-style latest EOD result without exposing key', async()=>{ mockJson(200,{data:[{symbol:'INFY.XNSE',date:'2026-07-13T00:00:00+0000',close:1500.25,currency:'INR'}]}); const p=new MarketstackProvider('secret-key'); const r=await p.getQuote({symbol:'INFY',exchange:'NSE'}); expect(r.ok).toBe(true); if(r.ok){ expect(r.quote.provider).toBe('marketstack'); expect(r.quote.data_kind).toBe('eod'); expect(r.quote.price).toBe('1500.25'); expect(r.quote.market_timestamp.slice(0,10)).toBe('2026-07-13'); } expect(String(await (fetch as any).mock.calls[0][0])).toContain('/eod/latest'); });
  it('requests multiple symbols in one controlled call', async()=>{ mockJson(200,{data:[{symbol:'INFY.XNSE',date:'2026-07-13',close:1,currency:'INR'},{symbol:'TCS.XNSE',date:'2026-07-13',close:2,currency:'INR'}]}); const out=await new MarketstackProvider('k').getQuotes([{symbol:'INFY',exchange:'NSE'},{symbol:'TCS',exchange:'NSE'}]); expect(out.every(x=>x.ok)).toBe(true); expect(String((fetch as any).mock.calls[0][0])).toContain('INFY.XNSE%2CTCS.XNSE'); });
  it('returns missing symbol row failure for empty EOD result', async()=>{ mockJson(200,{data:[]}); const r=await new MarketstackProvider('k').getQuote({symbol:'MISS',exchange:'NSE'}); expect(r.ok).toBe(false); if(!r.ok) expect(r.error_code).toBe('symbol_not_found'); });
  it('rejects unsupported exchange before fetch', async()=>{ const f=vi.fn(); vi.stubGlobal('fetch',f); const r=await new MarketstackProvider('k').getQuote({symbol:'X',exchange:'NYSE' as any}); expect(r.ok).toBe(false); expect(f).not.toHaveBeenCalled(); });
  it('maps HTTP 400, authentication, and rate limit safely', async()=>{ mockJson(400,{error:{message:'bad request'}}); let r=await new MarketstackProvider('secret1234567890123').getQuote({symbol:'INFY',exchange:'NSE'}); expect(r.ok).toBe(false); if(!r.ok) expect(r.error).not.toContain('secret'); mockJson(401,{error:{message:'invalid access_key',code:'invalid_access_key'}}); r=await new MarketstackProvider('k').getQuote({symbol:'INFY',exchange:'NSE'}); if(!r.ok) expect(r.error_code).toBe('provider_authentication_failed'); mockJson(429,{error:{message:'rate limit'}}); r=await new MarketstackProvider('k').getQuote({symbol:'INFY',exchange:'NSE'}); if(!r.ok) expect(r.error_code).toBe('rate_limited'); });
  it('rejects malformed JSON, future dates, and non-INR currency', async()=>{ vi.stubGlobal('fetch',vi.fn(async()=>new Response('{bad',{status:200}))); let r=await new MarketstackProvider('k').getQuote({symbol:'INFY',exchange:'NSE'}); if(!r.ok) expect(r.error_code).toBe('malformed_provider_response'); mockJson(200,{data:[{symbol:'INFY.XNSE',date:'2999-01-01',close:1,currency:'INR'}]}); r=await new MarketstackProvider('k').getQuote({symbol:'INFY',exchange:'NSE'}); if(!r.ok) expect(r.error).toContain('future'); mockJson(200,{data:[{symbol:'INFY.XNSE',date:'2026-07-13',close:1,currency:'USD'}]}); r=await new MarketstackProvider('k').getQuote({symbol:'INFY',exchange:'NSE'}); if(!r.ok) expect(r.error_code).toBe('currency_mismatch'); });
});
