import { describe, it, expect } from 'vitest';
import { calculateBalance, finiteInt, SNAPSHOT_SOURCES } from '../src/server/account-balance-service';

function db(tables:any){ return { prepare(sql:string){ return { bind(...args:any[]){ return { first:async()=>first(sql,args), all:async()=>({results:all(sql,args)}), run:async()=>({success:true,meta:{last_row_id:1}}) }; }, first:async()=>first(sql,[]), all:async()=>({results:all(sql,[])}), run:async()=>({success:true,meta:{last_row_id:1}}) }; } } as any;
 function first(sql:string,args:any[]){ if(sql.includes('FROM wallets')) return tables.wallets.find((w:any)=>w.user_id===args[0]&&w.id===args[1]); if(sql.includes("source='opening_balance'")) return tables.snapshots.filter((s:any)=>s.user_id===args[0]&&s.wallet_id===args[1]&&s.source==='opening_balance'&&s.snapshot_date<=args[2]).at(-1)||null; if(sql.includes("source<>'opening_balance'")) return tables.snapshots.filter((s:any)=>s.user_id===args[0]&&s.wallet_id===args[1]&&s.source!=='opening_balance'&&s.snapshot_date<=args[2]).at(-1)||null; if(sql.includes('COUNT(*) count FROM movements')) return {count:0}; return null; }
 function all(sql:string,args:any[]){ if(sql.includes('FROM movements')) return tables.movements.filter((m:any)=>m.user_id===args[0]&&m.date>args[1]&&m.date<=args[2]&&((m.src_kind==='wallet'&&m.src_id===args[3])||(m.dst_kind==='wallet'&&m.dst_id===args[4]))); return []; }
}
const ctx=(tables:any)=>({env:{DB:db(tables)}} as any);

describe('Phase 17 account balance reconciliation',()=>{
 it('validates finite amounts and supported snapshot sources',()=>{ expect(finiteInt(10.2)).toBe(10); expect(()=>finiteInt(Infinity)).toThrow(/finite/); expect(SNAPSHOT_SOURCES).toContain('opening_balance'); });
 it('calculates as-of wallet balance with opening, credits, debits, transfers and adjustments',async()=>{ const c=ctx({wallets:[{user_id:1,id:7,initial_balance:0}],snapshots:[{user_id:1,wallet_id:7,source:'opening_balance',snapshot_date:'2026-01-01',balance:1000},{user_id:1,wallet_id:7,source:'manual',snapshot_date:'2026-01-31',balance:1224,currency:'IDR'}],movements:[{user_id:1,date:'2026-01-02',amount:500,src_kind:null,src_id:null,dst_kind:'wallet',dst_id:7},{user_id:1,date:'2026-01-03',amount:200,src_kind:'wallet',src_id:7,dst_kind:null,dst_id:null},{user_id:1,date:'2026-01-04',amount:50,src_kind:'wallet',src_id:1,dst_kind:'wallet',dst_id:7},{user_id:1,date:'2026-01-05',amount:25,src_kind:'wallet',src_id:7,dst_kind:'wallet',dst_id:2},{user_id:1,date:'2026-01-06',amount:1,src_kind:null,src_id:null,dst_kind:'wallet',dst_id:7,description:'[Reconciliation adjustment] rounding'}]}); const r=await calculateBalance(c,1,7,'2026-01-31'); expect(r.expected_balance).toBe(1326); expect(r.total_credits).toBe(500); expect(r.total_debits).toBe(200); expect(r.incoming_transfers).toBe(50); expect(r.outgoing_transfers).toBe(25); expect(r.adjustments).toBe(1); expect(r.reconciliation_difference).toBe(102); });
});
