import { Hono } from 'hono';
import { describe, expect, it, vi } from 'vitest';
import wealthPerformance from '../src/server/routes/wealth-performance';
function mockDB(){ const prepare=vi.fn((q:string)=>({bind:vi.fn((...args:any[])=>({
 all:vi.fn(async()=>{ if(q.includes('FROM investment_transactions')) return {results:[{id:1,user_id:1,account_id:1,account_name:'A',asset_id:2,asset_name:'Fund',asset_type:'mutual_fund',pricing_mode:'manual',valuation_mode:'holdings',transaction_type:'buy',trade_date:'2026-01-01',quantity:'10',gross_amount:1000},{id:2,user_id:1,account_id:1,account_name:'A',asset_id:2,asset_name:'Fund',asset_type:'mutual_fund',pricing_mode:'manual',valuation_mode:'holdings',transaction_type:'dividend',trade_date:'2026-06-01',gross_amount:50}]}; if(q.includes('FROM investment_prices')) return {results:[{asset_id:2,price_date:'2026-12-31',price:'120'}]}; if(q.includes('FROM movements')) return {results:[{date:'2026-01-01',amount:1000,dst_kind:'portfolio'}]}; return {results:[]};}),
 first:vi.fn(async()=>{ if(q.includes('SELECT id FROM portfolios')||q.includes('SELECT id FROM investment_assets')) return {id:args[0]}; if(q.includes('SELECT valuation_mode')) return {valuation_mode:'holdings'}; return null;}), run:vi.fn(async()=>({meta:{}}))}))})); return {prepare} as any; }
function app(db=mockDB(), user=true){ const a=new Hono<{Variables:{userId:number}}>(); if(user) a.use('*',async(c,n)=>{c.set('userId',1); await n();}); a.route('/api/wealth/performance',wealthPerformance); return {app:a, env:{DB:db} as any}; }
describe('wealth performance routes',()=>{
 it('serves portfolio, account, asset, asset type and debug responses',async()=>{ let h=app(); for(const url of ['/api/wealth/performance','/api/wealth/performance?scope=account&account_id=1','/api/wealth/performance?scope=asset&asset_id=2&debug=true','/api/wealth/performance?scope=asset_type&asset_type=mutual_fund']){ const r=await h.app.request(url,{},h.env); expect(r.status).toBe(200); const j:any=await r.json(); expect(JSON.stringify(j)).not.toMatch(/NaN|Infinity/); } });
 it('validates inputs and ownership',async()=>{ const h=app(); expect((await h.app.request('/api/wealth/performance?scope=bad',{},h.env)).status).toBe(400); expect((await h.app.request('/api/wealth/performance?scope=account',{},h.env)).status).toBe(400); expect((await h.app.request('/api/wealth/performance?as_of=2026-99-99',{},h.env)).status).toBe(400); const h2=app({prepare:vi.fn(()=>({bind:vi.fn(()=>({first:vi.fn(async()=>null),all:vi.fn(async()=>({results:[]}))}))}))} as any); expect((await h2.app.request('/api/wealth/performance?scope=account&account_id=99',{},h2.env)).status).toBe(404); });
 it('serializes null xirr with status for incomplete valuation',async()=>{ const h=app(); const r=await h.app.request('/api/wealth/performance?scope=asset&asset_id=2&as_of=2026-01-02',{},h.env); const j:any=await r.json(); expect(JSON.stringify(j)).toContain('xirr_status'); });
});
