import { parseCsv } from '../wealth/csv';

export const IMPORT_TYPES = ['bank_statement','credit_card_statement','loan_statement','mutual_fund_statement','epf_statement','nps_statement','generic_ledger','generic_valuation','generic_liability'];
export const STATEMENT_LIMITS = { maxFileSize: 5 * 1024 * 1024, maxRows: 10000, maxColumns: 100, maxCellLength: 10000 };
const SECRET_RE = /(password|otp|cvv|pin|secret)/i;

export function maskSensitive(v:any){
  const s=String(v??'');
  return s.replace(/\b(\d{0,12})(\d{4})\b/g, (_m,p,last)=> p && p.length>=4 ? `${'*'.repeat(Math.min(12,p.length))}${last}` : _m);
}
export function sanitizeFilename(name:string){ return String(name||'statement.csv').replace(/[^\w. -]/g,'_').slice(0,120) || 'statement.csv'; }
export async function sha256Hex(bytes:Uint8Array){ const h=await crypto.subtle.digest('SHA-256',bytes); return Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,'0')).join(''); }
export function safeRaw(row:Record<string,string>){ const out:Record<string,string>={}; for(const [k,v] of Object.entries(row)){ out[k]=SECRET_RE.test(k)?'[redacted]':maskSensitive(v); } return out; }
export function intAmount(v:any){ const s=String(v??'').trim(); if(!s) return null; const neg=/^\(|-$/.test(s)||s.includes('-'); const n=Number(s.replace(/[(),₹$€£\s]/g,'').replace(/,/g,'')); if(!Number.isFinite(n)) return null; return Math.round(Math.abs(n))*(neg?-1:1); }
export function parseDate(v:any, fmt?:string){ const s=String(v??'').trim(); if(!s) return null; let m; if((m=s.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$/))) return `${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`; if((m=s.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{2,4})$/))){ const y=m[3].length===2?`20${m[3]}`:m[3]; const dmy=fmt?.toLowerCase().startsWith('mm')? [y,m[1],m[2]]:[y,m[2],m[1]]; return `${dmy[0]}-${dmy[1].padStart(2,'0')}-${dmy[2].padStart(2,'0')}`; } const d=new Date(s); return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10); }
function normHeader(h:string){ return h.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(); }
export const DEFAULT_TEMPLATES:any[] = [
 {name:'Generic bank statement',institution:'Generic',import_type:'bank_statement',column_mapping:{date:'date',description:'description',reference:'reference number',debit:'debit',credit:'credit',balance:'balance'},date_format:'yyyy-mm-dd',amount_convention:'debit_credit',header_row:1,rows_to_skip:0,active:true},
 {name:'Generic credit card statement',institution:'Generic',import_type:'credit_card_statement',column_mapping:{date:'transaction date',description:'merchant',reference:'reference',debit:'debit',credit:'credit/refund',balance:'statement balance'},date_format:'yyyy-mm-dd',amount_convention:'debit_credit',header_row:1,rows_to_skip:0,active:true},
 {name:'Generic loan statement',institution:'Generic',import_type:'loan_statement',column_mapping:{date:'payment date',amount:'emi',principal:'principal',interest:'interest',fees:'fees',balance:'outstanding balance'},date_format:'yyyy-mm-dd',amount_convention:'signed',header_row:1,rows_to_skip:0,active:true},
 {name:'Generic mutual fund statement',institution:'Generic',import_type:'mutual_fund_statement',column_mapping:{date:'transaction date',description:'scheme',type:'transaction type',amount:'amount',units:'units',nav:'nav',balance:'balance units'},date_format:'yyyy-mm-dd',amount_convention:'signed',header_row:1,rows_to_skip:0,active:true},
 {name:'Generic EPF statement',institution:'Generic',import_type:'epf_statement',column_mapping:{date:'contribution month',credit:'employee contribution',employer:'employer contribution',interest:'interest',balance:'closing balance'},date_format:'yyyy-mm-dd',amount_convention:'contribution',header_row:1,rows_to_skip:0,active:true},
 {name:'Generic NPS statement',institution:'Generic',import_type:'nps_statement',column_mapping:{date:'transaction date',credit:'contribution',units:'units',nav:'nav',description:'scheme',balance:'closing value'},date_format:'yyyy-mm-dd',amount_convention:'contribution',header_row:1,rows_to_skip:0,active:true}
];
export function suggest(headers:string[]){ const hs=headers.map(normHeader); const has=(...xs:string[])=>xs.some(x=>hs.includes(normHeader(x))); let import_type='generic_ledger'; if(has('scheme','folio','nav','units')) import_type='mutual_fund_statement'; else if(has('eps contribution','employee contribution')) import_type='epf_statement'; else if(has('tier','closing value','nav')) import_type='nps_statement'; else if(has('emi','principal','outstanding balance')) import_type='loan_statement'; else if(has('merchant','posting date','statement balance')) import_type='credit_card_statement'; else if(has('debit','credit','balance')) import_type='bank_statement'; const template=DEFAULT_TEMPLATES.find(t=>t.import_type===import_type)||DEFAULT_TEMPLATES[0]; const map:any={}; for(const [k,want] of Object.entries(template.column_mapping)){ const idx=hs.findIndex(h=>h===normHeader(String(want)) || h.includes(normHeader(String(want))) || normHeader(String(want)).includes(h)); if(idx>=0) map[k]=headers[idx]; }
 return {import_type,column_mapping:map,template}; }
export function normalize(row:any, mapping:any, opts:any={}){ const get=(k:string)=> mapping?.[k] ? row[mapping[k]] : ''; const debit=intAmount(get('debit')), credit=intAmount(get('credit')), signed=intAmount(get('amount')); let amount= signed??(credit?Math.abs(credit):debit?Math.abs(debit):null); let direction = signed!=null ? (signed<0?'debit':'credit') : debit?'debit':credit?'credit':null; if(opts.invert_sign && direction) direction=direction==='debit'?'credit':'debit'; const date=parseDate(get('date')||get('posting_date')||get('value_date'), opts.date_format); const type=String(get('type')||'').toLowerCase(); const description=maskSensitive(get('description')||get('merchant')||get('scheme')||type); const reference=maskSensitive(get('reference'));
 return { normalized_type:type||classify(description,direction), normalized_date:date, normalized_amount:amount==null?null:Math.abs(amount), normalized_direction:direction, normalized_description:description, normalized_reference:reference, normalized_account:maskSensitive(get('account')), normalized_category:get('category')||opts.default_category||null, normalized_balance:intAmount(get('balance')) };
}
function classify(desc:string, dir:any){ const d=desc.toLowerCase(); if(/refund|reversal/.test(d)) return 'refund'; if(/interest/.test(d)) return dir==='credit'?'interest_income':'interest'; if(/fee|charge/.test(d)) return 'fee'; if(/atm|withdraw/.test(d)) return 'atm_withdrawal'; if(/cash deposit/.test(d)) return 'cash_deposit'; if(/emi/.test(d)) return 'emi'; return dir==='credit'?'income':'expense'; }
export function financialFingerprint(uid:number,n:any,wallet?:any){ return [uid,n.normalized_date,n.normalized_amount,n.normalized_direction,wallet||n.normalized_account||'',String(n.normalized_description||'').toLowerCase().replace(/\s+/g,' ').slice(0,80),n.normalized_reference||''].join('|'); }
export function parseStatementCsv(bytes:Uint8Array){ return parseCsv(bytes, STATEMENT_LIMITS); }
export function validateNormalized(n:any){ if(!n.normalized_date) return 'Invalid or missing date'; if(!n.normalized_amount || n.normalized_amount<=0) return 'Invalid or missing amount'; if(!n.normalized_direction) return 'Invalid or missing direction'; return null; }
