import { add, compare, divideCostByQuantity, formatDecimal, multiplyQuantityByPriceMinor, parseDecimal, subtract } from './decimal';

export type CutoverTrade = { account_id?: number|string; asset_id?: number|string; symbol?: string|null; isin?: string|null; exchange?: string|null; transaction_type: string; trade_date: string; quantity?: string|null; unit_price?: string|null; gross_amount?: number|null; external_ref?: string|null; notes?: string|null; };
type Lot = { quantity: string; cost: number };
const BUY = new Set(['buy','sip','transfer_in','bonus']);
const SELL = new Set(['sell','redemption','transfer_out']);
const keyOf=(t:CutoverTrade)=>`${t.account_id??''}|${t.asset_id??''}|${t.isin??''}|${t.symbol??''}|${t.exchange??''}`;
const assetRef=(t:CutoverTrade)=>({account_id:t.account_id,asset_id:t.asset_id,symbol:t.symbol,isin:t.isin,exchange:t.exchange});
export function calculateCutoverOpeningPositions(transactions: CutoverTrade[], cutoverDate='2026-04-01'){
  const by=new Map<string,{ref:any,lots:Lot[],warnings:string[],errors:string[],realized:number,buys:string,sells:string}>();
  for(const t of transactions.filter(x=>x.trade_date < cutoverDate).sort((a,b)=>a.trade_date.localeCompare(b.trade_date))){
    const k=keyOf(t); const s=by.get(k)||{ref:assetRef(t),lots:[],warnings:[],errors:[],realized:0,buys:'0',sells:'0'}; by.set(k,s);
    const qty=t.quantity||'0'; if(t.transaction_type==='split'){ const ratio=t.unit_price||t.quantity||'1'; s.lots=s.lots.map(l=>({...l, quantity:formatDecimal(parseDecimal(l.quantity,{allowZero:true})*parseDecimal(ratio,{allowZero:false})/1000000n)})); s.warnings.push('Applied split ratio from unit_price/quantity'); continue; }
    if(BUY.has(t.transaction_type)){ const cost=t.transaction_type==='bonus'?0:(t.gross_amount ?? (t.unit_price?multiplyQuantityByPriceMinor(qty,t.unit_price):0)); s.lots.push({quantity:qty,cost}); s.buys=add(s.buys,qty); }
    else if(SELL.has(t.transaction_type)){ let need=qty; s.sells=add(s.sells,qty); while(compare(need,'0')>0 && s.lots.length){ const lot=s.lots[0]; if(compare(lot.quantity,need)<=0){ s.realized+=lot.cost; need=subtract(need,lot.quantity); s.lots.shift(); } else { const soldCost=Number((BigInt(lot.cost)*parseDecimal(need,{allowZero:false}) + parseDecimal(lot.quantity,{allowZero:false})/2n)/parseDecimal(lot.quantity,{allowZero:false})); lot.quantity=subtract(lot.quantity,need); lot.cost-=soldCost; s.realized+=soldCost; need='0'; } }
      if(compare(need,'0')>0) s.errors.push(`Unresolved oversell before cutover: ${need}`);
    } else s.warnings.push(`Ignored unsupported pre-cutover transaction type: ${t.transaction_type}`);
  }
  const opening_positions:any[]=[]; const unresolved:any[]=[]; const closed_positions:any[]=[];
  for(const [k,s] of by){ const quantity=s.lots.reduce((q,l)=>add(q,l.quantity),'0'); const cost=s.lots.reduce((n,l)=>n+l.cost,0); if(s.errors.length){ unresolved.push({...s.ref,errors:s.errors,warnings:s.warnings}); continue; } if(compare(quantity,'0')>0){ opening_positions.push({...s.ref,transaction_type:'transfer_in',trade_date:previousDay(cutoverDate),quantity,gross_amount:cost,net_amount:cost,unit_price:divideCostByQuantity(cost,quantity),external_ref:`cutover:${cutoverDate}:${k}`,notes:'Opening position generated from pre-cutover tradebook',movement_id:null,warnings:s.warnings}); } else closed_positions.push({...s.ref,realized_cost:s.realized,buy_quantity:s.buys,sell_quantity:s.sells}); }
  return { opening_positions, unresolved, closed_positions, warnings: unresolved.length?['One or more securities have unresolved pre-cutover history.']:[], can_commit: unresolved.length===0 };
}
export function aggregateTradesByOrder(rows: CutoverTrade[]){ const m=new Map<string,CutoverTrade[]>(); for(const r of rows){ const k=[r.trade_date,r.external_ref||'',r.symbol||'',r.isin||'',r.exchange||'',r.transaction_type].join('|'); if(!r.external_ref){ m.set(`${k}|${Math.random()}`,[r]); } else { const a=m.get(k)||[]; a.push(r); m.set(k,a); } } return [...m.values()].map(g=>{ if(g.length===1)return g[0]; const quantity=formatDecimal(g.reduce((n,r)=>n+parseDecimal(r.quantity||'0',{allowZero:true}),0n)); const gross=g.reduce((n,r)=>n+(r.gross_amount ?? multiplyQuantityByPriceMinor(r.quantity||'0',r.unit_price||'0')),0); return {...g[0],quantity,gross_amount:gross,unit_price:divideCostByQuantity(gross,quantity),external_ref:g[0].external_ref,notes:`Aggregated order executions: ${g.map(r=>r.notes||'').filter(Boolean).join(', ')}`}; }); }
export function reconcileOpeningHoldings(generated:any[], statement:any[]){ const id=(x:any)=>x.isin||`${x.symbol||''}|${x.exchange||''}`; const ids=new Set([...generated.map(id),...statement.map(id)]); return [...ids].map(k=>{ const g=generated.find(x=>id(x)===k), s=statement.find(x=>id(x)===k); const gd=g?.quantity||'0', sd=s?.quantity||'0', gc=g?.gross_amount||g?.total_cost||0, sc=s?.total_cost||0; let status='matched'; if(!g) status='missing_in_tradebook'; else if(!s) status='missing_in_statement'; else if(compare(gd,sd)!==0) status='quantity_mismatch'; else if(gc!==sc) status='cost_mismatch'; return {asset:k,generated_quantity:gd,statement_quantity:sd,quantity_difference:subtract(gd,sd),generated_cost:gc,statement_cost:sc,cost_difference:gc-sc,status}; }); }
function previousDay(d:string){ const dt=new Date(d+'T00:00:00Z'); dt.setUTCDate(dt.getUTCDate()-1); return dt.toISOString().slice(0,10); }
