import { getWealthAccountValuations } from './valuation';
import { calculateLiability, schedule, today, int, finite } from './liabilities';

export const GOAL_TYPES = ['emergency_fund','retirement','child_education','home_purchase','vehicle_purchase','debt_payoff','vacation','wedding','major_purchase','custom'];
export const FUNDING_MODES = ['linked_assets','manual','hybrid'];
export const PRIORITIES = ['high','medium','low'];
export const GOAL_STATUSES = ['active','paused','completed','cancelled'];
export const INFLATION_TYPES = ['retirement','child_education','home_purchase','wedding','major_purchase'];

export function assertFiniteNumber(value:any, name:string, required=false){ if(value==null||value===''){ if(required) throw new Error(`${name} required`); return null; } const n=Number(value); if(!Number.isFinite(n)) throw new Error(`Invalid ${name}`); return n; }
export function parseGoalBody(b:any){
 const target=int(assertFiniteNumber(b.target_amount,'target_amount',true));
 const manual=b.current_manual_amount==null?null:int(assertFiniteNumber(b.current_manual_amount,'current_manual_amount'));
 const inf=b.inflation_rate==null?null:Number(b.inflation_rate); const ret=b.expected_return_rate==null?null:Number(b.expected_return_rate);
 const goal={ name:String(b.name||'').trim(), goal_type:b.goal_type||'custom', target_amount:target, target_date:b.target_date||null, current_manual_amount:manual, funding_mode:b.funding_mode||'manual', priority:b.priority||'medium', status:b.status||'active', start_date:b.start_date||null, inflation_rate:inf, expected_return_rate:ret, monthly_contribution_override:b.monthly_contribution_override==null?null:int(b.monthly_contribution_override), include_existing_assets:b.include_existing_assets===false?0:1, notes:b.notes??null, metadata_json:b.metadata_json?JSON.stringify(typeof b.metadata_json==='string'?JSON.parse(b.metadata_json):b.metadata_json):null };
 validateGoal(goal); return goal;
}
export function validateGoal(g:any){ if(!g.name) throw new Error('Name required'); if(!GOAL_TYPES.includes(g.goal_type)) throw new Error('Invalid goal_type'); if(!FUNDING_MODES.includes(g.funding_mode)) throw new Error('Invalid funding_mode'); if(!PRIORITIES.includes(g.priority)) throw new Error('Invalid priority'); if(!GOAL_STATUSES.includes(g.status)) throw new Error('Invalid status'); if(!Number.isFinite(g.target_amount)||g.target_amount<=0) throw new Error('Target amount must be positive'); if(g.current_manual_amount!=null&&(!Number.isFinite(g.current_manual_amount)||g.current_manual_amount<0)) throw new Error('Current amount cannot be negative'); if(g.target_date&&g.start_date&&g.target_date<g.start_date) throw new Error('Target date cannot be before start date'); for(const [k,min,max] of [['inflation_rate',-50,100],['expected_return_rate',-100,100]] as any){ if(g[k]!=null&&(!Number.isFinite(Number(g[k]))||Number(g[k])<min||Number(g[k])>max)) throw new Error(`Invalid ${k}`); } }
export function yearsBetween(from:string,to:string){ return Math.max(0,(Date.parse(to)-Date.parse(from))/31557600000); }
export function inflationAdjustment(goal:any, asOf=today()){ if(!INFLATION_TYPES.includes(goal.goal_type)||!goal.target_date||goal.inflation_rate==null) return null; const years=yearsBetween(asOf,goal.target_date); const rate=finite(goal.inflation_rate)/100; const adjusted=Math.round(int(goal.target_amount)*Math.pow(1+rate,years)); return {base_target:goal.target_amount,inflation_adjusted_target:adjusted,years_remaining:years,inflation_rate:goal.inflation_rate,estimate:true,assumptions:'Compound annual inflation using user-provided rate; original target is not overwritten.'}; }
export function plan(goal:any,current:number, asOf=today(), override?:any){ const targetAdj=inflationAdjustment(goal,asOf)?.inflation_adjusted_target??int(goal.target_amount); const targetDate=override?.target_date||goal.target_date; if(current>=targetAdj) return {status:'already_funded',required_monthly_contribution:0,months_remaining:0,expected_future_value_of_current_corpus:current,expected_target_amount:targetAdj,assumptions:{estimate:true}}; if(!targetDate) return {status:'missing_target_date',required_monthly_contribution:null,months_remaining:null,expected_future_value_of_current_corpus:current,expected_target_amount:targetAdj,assumptions:{estimate:true}}; const months=Math.floor((Date.parse(targetDate)-Date.parse(asOf))/(86400000*30.4375)); if(months<=0) return {status:'target_date_passed',required_monthly_contribution:null,months_remaining:0,expected_future_value_of_current_corpus:current,expected_target_amount:targetAdj,assumptions:{estimate:true}}; const r=override?.expected_return_rate ?? goal.expected_return_rate; const annual=r==null?0:finite(r)/100; const monthly=annual/12; const fvCurrent=monthly?Math.round(current*Math.pow(1+monthly,months)):current; const gap=Math.max(0,targetAdj-fvCurrent); const req=monthly?Math.round(gap*monthly/(Math.pow(1+monthly,months)-1)):Math.ceil(gap/months); return {status:'calculated',required_monthly_contribution:goal.monthly_contribution_override??req,user_override:goal.monthly_contribution_override??null,months_remaining:months,expected_future_value_of_current_corpus:fvCurrent,expected_target_amount:targetAdj,assumptions:{estimate:true,expected_return_rate:r??0,frequency:'monthly'}}; }
async function assetValue(db:D1Database,uid:number,asOf:string,link:any){ const vals=await getWealthAccountValuations(db,uid,asOf); if(link.account_id){ const a=vals.accounts.find(x=>x.account_id===link.account_id); return a?{value:a.value,complete:a.valuation_complete,warnings:a.warnings,stale:a.warnings.some(w=>/stale/i.test(w))}:{missing:true}; } if(link.asset_id){ let value=0, found=false, complete=true, stale=false, warnings:string[]=[]; for(const a of vals.accounts){ const rows=(await db.prepare('SELECT * FROM wealth_valuation_snapshots WHERE user_id=? AND asset_id=? AND valuation_date<=? ORDER BY valuation_date DESC,id DESC LIMIT 1').bind(uid,link.asset_id,asOf).all<any>()).results; if(rows[0]){found=true; value+=int(rows[0].current_value); stale ||= rows[0].valuation_date < asOf.slice(0,8)+'01';} } return found?{value,complete,warnings,stale}:{missing:true}; } return {missing:true}; }
export async function calculateGoalProgress(db:D1Database,uid:number,goal:any,asOf=today()){
 const links=(await db.prepare('SELECT * FROM financial_goal_links WHERE user_id=? AND goal_id=? ORDER BY id').bind(uid,goal.id).all<any>()).results; const warnings:string[]=[], missing:any[]=[], stale:any[]=[]; let linked=0, originalDebt=0, outstanding=0, monthlyScheduled=0, highest:any=null; const counted=new Set<string>();
 for(const l of links){ const key=`${l.link_type}:${l.account_id||l.asset_id||l.liability_id}`; if(counted.has(key)){warnings.push(`duplicate counted link skipped: ${key}`); continue;} counted.add(key); if(l.liability_id){ const liab=await db.prepare('SELECT * FROM liabilities WHERE user_id=? AND id=?').bind(uid,l.liability_id).first<any>(); if(!liab){missing.push(l.id); continue;} const v=await calculateLiability(db,uid,liab,asOf); originalDebt+=int(liab.original_principal||liab.current_outstanding); outstanding+=v.outstanding; monthlyScheduled+=int(liab.emi_amount||liab.minimum_due); if(!highest||Number(liab.interest_rate)>Number(highest.interest_rate)) highest={id:liab.id,name:liab.name,interest_rate:liab.interest_rate}; continue; }
  const v=await assetValue(db,uid,asOf,l); if((v as any).missing){missing.push(l.id); continue;} if((v as any).stale) stale.push(l.id); const alloc=l.fixed_allocation_amount!=null?Math.min(int(l.fixed_allocation_amount),(v as any).value):(v as any).value*((l.allocation_percent??100)/100); linked+=Math.round(alloc); }
 const manual=(goal.funding_mode==='manual'||goal.funding_mode==='hybrid')?int(goal.current_manual_amount):0; const current=goal.goal_type==='debt_payoff'?Math.max(0,originalDebt-outstanding):((goal.funding_mode==='manual'?0:linked)+manual); const target=goal.goal_type==='debt_payoff'?(originalDebt||goal.target_amount):goal.target_amount; const remaining=Math.max(0,target-current); const overfunded=Math.max(0,current-target); const pct=target?Math.min(100,Math.max(0,current/target*100)):0; const elapsed=goal.start_date&&goal.target_date?Math.min(100,Math.max(0,yearsBetween(goal.start_date,asOf)/Math.max(yearsBetween(goal.start_date,goal.target_date),.0001)*100)):null; const expected=elapsed==null?null:Math.round(target*elapsed/100); const behind=expected==null?0:current-expected; let status= current>=target?'achieved':!goal.target_date?'no_target_date':missing.length?'insufficient_data':behind>=0?'on_track':behind>=-target*.05?'slightly_behind':'behind';
 const allocation=await allocationWarnings(db,uid,goal.id); warnings.push(...allocation); return {target_amount:target,current_amount:current,remaining_amount:remaining,progress_percent:pct,display_progress_percent:pct,overfunded_amount:overfunded,elapsed_percent:elapsed,expected_amount_by_today:expected,ahead_or_behind_amount:behind,status,valuation_complete:missing.length===0,missing_linked_values:missing,stale_linked_values:stale,calculation_date:asOf,warnings,inflation:inflationAdjustment(goal,asOf),monthly_plan:plan(goal,current,asOf),debt_payoff:goal.goal_type==='debt_payoff'?{starting_debt:originalDebt,current_outstanding:outstanding,amount_repaid:current,monthly_scheduled_payments:monthlyScheduled,highest_interest_liability:highest}:null,emergency_fund:emergency(goal,current)}; }
function emergency(goal:any,current:number){ if(goal.goal_type!=='emergency_fund') return null; let m:any={}; try{m=goal.metadata_json?JSON.parse(goal.metadata_json):{};}catch{} const exp=int(m.average_essential_monthly_expenses); const desired=int(m.desired_coverage_months)||null; return exp?{current_coverage_months:current/exp,target_coverage_months:desired,shortfall:Math.max(0,(desired?exp*desired:goal.target_amount)-current),status:desired&&current>=exp*desired?'covered':'building'}:null; }
export async function allocationWarnings(db:D1Database,uid:number,excludeGoal?:number){ const rows=(await db.prepare('SELECT * FROM financial_goal_links WHERE user_id=? AND allocation_percent IS NOT NULL').bind(uid).all<any>()).results; const sums:any={}; for(const r of rows){const k=`${r.link_type}:${r.account_id||r.asset_id||r.liability_id}`; sums[k]=(sums[k]||0)+Number(r.allocation_percent||0);} return Object.entries(sums).filter(([,v]:any)=>v>100).map(([k,v])=>`Total allocation for ${k} exceeds 100% (${v}%).`); }
export function scenario(goal:any,current:number,input:any,asOf=today()){ const g={...goal,target_amount:int(input.target_amount??goal.target_amount),target_date:input.target_date??goal.target_date,expected_return_rate:input.expected_return_rate??goal.expected_return_rate,inflation_rate:input.inflation_rate??goal.inflation_rate,monthly_contribution_override:null}; const p=plan(g,int(input.current_amount??current),asOf,input); const months=p.months_remaining||0; const monthly=int(input.monthly_contribution??goal.monthly_contribution_override); const r=finite(g.expected_return_rate)/100/12; const fvCorpus=r?int(input.current_amount??current)*Math.pow(1+r,months):int(input.current_amount??current); const fvContrib=r&&months?monthly*(Math.pow(1+r,months)-1)/r:monthly*months; const projected=Math.round(fvCorpus+fvContrib); return {projected_amount:projected,projected_shortfall_surplus:projected-(p.expected_target_amount||g.target_amount),estimated_completion_date:null,required_contribution:p.required_monthly_contribution,assumptions:{estimate:true,not_guaranteed:true,months,expected_return_rate:g.expected_return_rate??0}}; }
