import type { AppContext } from '../types';
import { parseDecimal, formatDecimal, multiplyQuantityByPriceMinor } from './decimal';
import { validateNoOversell, type InvestmentTransactionInput } from './formulas';
import { ACCOUNT_TYPES, ASSET_TYPES, PRICE_SOURCES } from './types';
import { isDateOnly, isEnumValue, normalizeCurrency, normalizeIdentifier, optionalText } from './validation';

export const CANONICAL_COLUMNS = ['account_id','account_name','account_type','institution','asset_name','asset_type','symbol','isin','exchange','scheme_code','transaction_type','trade_date','settlement_date','quantity','unit_price','gross_amount','charges','taxes','net_amount','currency','movement_id','external_ref','notes','price_date','price','price_source'] as const;
const TX_TYPES = ['buy','sell','sip','redemption','dividend','interest','contribution','withdrawal','transfer_in','transfer_out','bonus','split','charges','maturity'] as const;
export async function sha256Hex(data: Uint8Array | string) { const bytes = typeof data === 'string' ? new TextEncoder().encode(data) : data; const hash = await crypto.subtle.digest('SHA-256', bytes); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
export function validateMapping(mapping:any, headers:string[]) { const out:Record<string,string>={}; const used=new Set<string>(); for (const [src,dst] of Object.entries(mapping||{})) { if (!headers.includes(src)) throw new Error(`Mapped header not found: ${src}`); if (!CANONICAL_COLUMNS.includes(dst as any)) throw new Error(`Invalid canonical field: ${dst}`); if (used.has(dst as string)) throw new Error(`Duplicate canonical mapping: ${dst}`); used.add(dst as string); out[src]=dst as string; } for (const h of headers) { const canonical=CANONICAL_COLUMNS.find(c=>c===String(h).trim().toLowerCase()); if(canonical && !used.has(canonical) && out[h]==null){ out[h]=canonical; used.add(canonical); } } return out; }
function dec(v:any, positive=false){ const t=optionalText(v); if(!t)return null; return formatDecimal(parseDecimal(t,{allowZero:!positive})); }
function money(v:any, name:string){ const t=optionalText(v); if(!t)return null; if(!/^\d+$/.test(t)) throw new Error(`Invalid ${name}`); return Number(t); }
function enumNorm<T extends readonly string[]>(vals:T, v:any, name:string, fallback?:string){ const t=optionalText(v)?.toLowerCase().replace(/[ -]/g,'_') ?? fallback; if(!t) return null; if(!isEnumValue(vals,t)) throw new Error(`Invalid ${name}`); return t; }
export function normalizeImportRow(raw:Record<string,string>, mapping:Record<string,string>, options:any={}) { const source:Record<string,any>={}; for(const [h,v] of Object.entries(raw)) if(mapping[h]) source[mapping[h]]=v; const n:any={}; const warnings:string[]=[]; const get=(k:string)=> source[k] ?? options[`default_${k}`];
  const accountId=get('account_id');
  if(accountId!=null && String(accountId).trim()!=='') { if(!/^\d+$/.test(String(accountId).trim())) throw new Error('Invalid account_id'); n.account_id=Number(String(accountId).trim()); } else n.account_id=null;
  for (const k of ['account_name','institution','asset_name','external_ref','notes'] ) n[k]=optionalText(get(k));
  n.account_type=enumNorm(ACCOUNT_TYPES,get('account_type'),'account_type',options.default_account_type||undefined);
  n.asset_type=enumNorm(ASSET_TYPES,get('asset_type'),'asset_type',options.default_asset_type||undefined);
  n.transaction_type=enumNorm(TX_TYPES,get('transaction_type'),'transaction_type') as string|null;
  n.price_source=enumNorm(PRICE_SOURCES,get('price_source'),'price_source','import') as string|null;
  n.currency=normalizeCurrency(get('currency'), options.default_currency || 'INR'); if(!n.currency) throw new Error('Invalid currency');
  for (const k of ['isin','symbol','exchange','scheme_code']) n[k]=normalizeIdentifier(get(k));
  for (const k of ['trade_date','settlement_date','price_date']) { n[k]=optionalText(get(k)); if(n[k] && !isDateOnly(n[k])) throw new Error(`Invalid ${k}`); }
  n.quantity=dec(get('quantity'), false); n.unit_price=dec(get('unit_price'), false); n.price=dec(get('price'), true);
  for (const k of ['gross_amount','charges','taxes','net_amount']) n[k]=money(get(k),k); n.charges ??= 0; n.taxes ??= 0;
  if (get('movement_id')) { if(!/^\d+$/.test(String(get('movement_id')).trim())) throw new Error('Invalid movement_id'); n.movement_id=Number(String(get('movement_id')).trim()); } else n.movement_id=null;
  if ((n.transaction_type === 'buy' || n.transaction_type === 'sip') && n.gross_amount == null && n.quantity && n.unit_price) n.gross_amount = multiplyQuantityByPriceMinor(n.quantity,n.unit_price);
  if ((n.transaction_type === 'buy' || n.transaction_type === 'sip') && n.net_amount == null && n.gross_amount != null) n.net_amount = n.gross_amount + n.charges + n.taxes;
  const hasTx=!!n.transaction_type, hasPrice=!!(n.price_date||n.price); if(!hasTx && !hasPrice) throw new Error('Row must contain transaction or price data');
  return { normalized:n, warnings };
}
async function oneOrAmb(c:AppContext, sql:string, binds:any[], label:string){ const r=await c.env.DB.prepare(sql).bind(...binds).all<any>(); if(r.results.length>1) throw new Error(`Ambiguous ${label}`); return r.results[0]||null; }
export type AssetAmbiguityDiagnostic = { id:number; name:string; symbol:string|null; isin:string|null; has_transactions:boolean; has_prices:boolean; has_open_holdings:boolean };
export async function diagnoseAssetIdentifierAmbiguity(c:AppContext, uid:number, identifier:{ isin?:string|null; scheme_code?:string|null; symbol?:string|null; exchange?:string|null; asset_type?:string|null }){
  const wh=['a.user_id=?','a.is_active=1']; const binds:any[]=[uid];
  if(identifier.isin){ wh.push('a.isin=?'); binds.push(identifier.isin); }
  else if(identifier.scheme_code){ wh.push('a.scheme_code=?'); binds.push(identifier.scheme_code); }
  else if(identifier.symbol&&identifier.exchange&&identifier.asset_type){ wh.push('a.symbol=?','a.exchange=?','a.asset_type=?'); binds.push(identifier.symbol,identifier.exchange,identifier.asset_type); }
  else return [];
  const r=await c.env.DB.prepare(`SELECT a.id,a.name,a.symbol,a.isin,
    CASE WHEN EXISTS (SELECT 1 FROM investment_transactions t WHERE t.user_id=a.user_id AND t.asset_id=a.id) THEN 1 ELSE 0 END has_transactions,
    CASE WHEN EXISTS (SELECT 1 FROM investment_prices p WHERE p.user_id=a.user_id AND p.asset_id=a.id) THEN 1 ELSE 0 END has_prices,
    CASE WHEN EXISTS (SELECT 1 FROM investment_transactions t WHERE t.user_id=a.user_id AND t.asset_id=a.id GROUP BY t.account_id HAVING SUM(CASE WHEN t.transaction_type IN ('buy','sip','contribution','transfer_in','bonus') THEN CAST(COALESCE(t.quantity,'0') AS REAL) WHEN t.transaction_type IN ('sell','redemption','withdrawal','transfer_out') THEN -CAST(COALESCE(t.quantity,'0') AS REAL) ELSE 0 END) > 0) THEN 1 ELSE 0 END has_open_holdings
    FROM investment_assets a WHERE ${wh.join(' AND ')} ORDER BY a.name,a.id`).bind(...binds).all<any>();
  return r.results.map((a:any):AssetAmbiguityDiagnostic=>({ id:a.id, name:a.name, symbol:a.symbol??null, isin:a.isin??null, has_transactions:!!a.has_transactions, has_prices:!!a.has_prices, has_open_holdings:!!a.has_open_holdings }));
}
export async function resolveAccount(c:AppContext, uid:number, n:any, options:any={}){ const explicitAccountId=n.account_id || options.default_account_id; if(explicitAccountId) { const a=await c.env.DB.prepare('SELECT id,name,account_type FROM portfolios WHERE id=? AND user_id=? AND is_active=1').bind(explicitAccountId,uid).first<any>(); if(!a) throw new Error(n.account_id ? 'Invalid account_id' : 'Invalid default account'); return { id:a.id, name:a.name, account_type:a.account_type }; } if(n.account_name){ const a=await oneOrAmb(c,'SELECT id,name,account_type FROM portfolios WHERE user_id=? AND is_active=1 AND lower(name)=lower(?)',[uid,n.account_name],'account name'); if(a) return { id:a.id, name:a.name, account_type:a.account_type }; } if(n.account_name && n.account_type) return { candidate:{ name:n.account_name, account_type:n.account_type, institution:n.institution, currency:n.currency } }; throw new Error('Missing account identifier'); }
export async function resolveAsset(c:AppContext, uid:number, n:any){ let a:any=null; if(n.isin) { const matches=await diagnoseAssetIdentifierAmbiguity(c,uid,{isin:n.isin}); if(matches.length>1) { const e:any=new Error(`Ambiguous active assets for ISIN ${n.isin}`); e.code='ambiguous_asset'; e.assets=matches; throw e; } a=matches[0]||null; } else if(n.scheme_code) a=await oneOrAmb(c,'SELECT * FROM investment_assets WHERE user_id=? AND scheme_code=? AND is_active=1',[uid,n.scheme_code],'asset scheme code'); else if(n.symbol&&n.exchange&&n.asset_type) a=await oneOrAmb(c,'SELECT * FROM investment_assets WHERE user_id=? AND symbol=? AND exchange=? AND asset_type=? AND is_active=1',[uid,n.symbol,n.exchange,n.asset_type],'asset symbol'); else if(n.asset_name&&n.asset_type) a=await oneOrAmb(c,'SELECT * FROM investment_assets WHERE user_id=? AND lower(name)=lower(?) AND asset_type=? AND is_active=1',[uid,n.asset_name,n.asset_type],'asset name'); if(a) return { id:a.id, name:a.name, asset_type:a.asset_type }; if(n.asset_name && n.asset_type && (n.isin || n.scheme_code || n.symbol || ['other','fixed_income','epf','nps','ppf','ssy','bond'].includes(n.asset_type))) return { candidate:{ name:n.asset_name, asset_type:n.asset_type, symbol:n.symbol, isin:n.isin, exchange:n.exchange, scheme_code:n.scheme_code, currency:n.currency, price_source:'import', pricing_mode:'manual' } }; throw new Error('Missing asset identifier'); }
export async function fingerprint(uid:number,n:any,acc:any,asset:any){ const parts=[uid, acc.id?`a:${acc.id}`:`ac:${acc.candidate?.name}:${acc.candidate?.account_type}`, asset?.id?`s:${asset.id}`:`sc:${asset?.candidate?.name}:${asset?.candidate?.asset_type}:${asset?.candidate?.isin}:${asset?.candidate?.scheme_code}:${asset?.candidate?.symbol}:${asset?.candidate?.exchange}`, n.transaction_type,n.trade_date,n.quantity,n.unit_price,n.gross_amount,n.charges,n.taxes,n.net_amount,n.external_ref,n.price_date,n.price,n.price_source].map(v=>v??'').join('|'); return sha256Hex(parts); }
export async function validateMovement(c:AppContext,uid:number,id:number|null){ if(!id)return; const m=await c.env.DB.prepare('SELECT id FROM movements WHERE id=? AND user_id=?').bind(id,uid).first(); if(!m) throw new Error('Invalid movement ownership'); }
export async function existingSeq(c:AppContext,uid:number,accountId:number,assetId:number, extra:(InvestmentTransactionInput & { __seq?: number })[]=[]){ const r=await c.env.DB.prepare('SELECT * FROM investment_transactions WHERE user_id=? AND account_id=? AND asset_id=? ORDER BY trade_date,id').bind(uid,accountId,assetId).all<any>(); return [...r.results,...extra].sort((a,b)=>a.trade_date.localeCompare(b.trade_date)||((a.__seq??a.id??0)-(b.__seq??b.id??0))); }
export { validateNoOversell };
