import type { AppContext } from '../types';
import { formatDecimal, parseDecimal } from './decimal';
import { NseBhavcopyProvider } from '../market-data/india/nse-bhavcopy';
import { YahooFinanceProvider } from '../market-data/india/yahoo-finance';
import { MfApiProvider } from '../market-data/india/mfapi';
import type { MarketPrice } from '../market-data/india/types';

type Scope='stocks'|'mutual_funds'|'all';
type Trigger='scheduled'|'manual'|'retry';
const today=()=>new Date().toISOString().slice(0,10);
const statusOf=(u:number,f:number,s:number)=>f&&!u?'failed':f?'partially_completed':u?'completed':'completed';
const note=(p:MarketPrice)=>`${p.provider} ${p.sourceType} ${p.providerSymbol||p.symbol}`.slice(0,500);
async function save(c:AppContext, uid:number, p:MarketPrice, force=false){ const price=formatDecimal(parseDecimal(p.close,{allowZero:false})); const same=await c.env.DB.prepare('SELECT id,source,price,provider_timestamp FROM investment_prices WHERE user_id=? AND asset_id=? AND price_date=?').bind(uid,p.assetId,p.tradeDate).first<any>(); if(same?.source==='manual'&&!force) return 'unchanged'; const newer=await c.env.DB.prepare('SELECT id FROM investment_prices WHERE user_id=? AND asset_id=? AND price_date>? LIMIT 1').bind(uid,p.assetId,p.tradeDate).first<any>(); if(newer&&!force) return 'unchanged'; await c.env.DB.prepare(`INSERT INTO investment_prices (user_id,asset_id,price_date,price,currency,source,notes,provider,provider_symbol,provider_timestamp,fetched_at,source_type) VALUES (?,?,?,?,?,'market',?,?,?,?,datetime('now'),?) ON CONFLICT(user_id,asset_id,price_date) DO UPDATE SET price=excluded.price,currency=excluded.currency,source=CASE WHEN investment_prices.source='manual' THEN investment_prices.source ELSE excluded.source END,notes=CASE WHEN investment_prices.source='manual' THEN investment_prices.notes ELSE excluded.notes END,provider=excluded.provider,provider_symbol=excluded.provider_symbol,provider_timestamp=excluded.provider_timestamp,fetched_at=datetime('now'),source_type=excluded.source_type,updated_at=datetime('now')`).bind(uid,p.assetId,p.tradeDate,price,'INR',note(p),p.provider,p.providerSymbol||p.symbol,p.providerTimestamp||p.tradeDate,p.sourceType).run(); await c.env.DB.prepare(`UPDATE investment_assets SET last_price_refresh_at=datetime('now'),last_price_refresh_status='updated',last_price_refresh_error=NULL,last_provider_timestamp=?,last_provider_trade_date=?,updated_at=datetime('now') WHERE user_id=? AND id=?`).bind(p.providerTimestamp||p.tradeDate,p.tradeDate,uid,p.assetId).run(); return same&&Number(same.price)===Number(price)?'unchanged':'updated'; }
export async function refreshIndianMarketPrices(c:AppContext, opts:{scope?:Scope; assetIds?:number[]; trigger?:Trigger; targetDate?:string; force?:boolean}={}){ const uid=c.get('userId'), targetDate=opts.targetDate||today(), scope=opts.scope||'all'; const ids=[...new Set((opts.assetIds||[]).map(Number).filter(Boolean))]; if(ids.length>50) throw new Error('Too many selected assets'); const last=opts.trigger==='manual'&&!opts.force?await c.env.DB.prepare(`SELECT completed_at FROM wealth_price_refresh_runs WHERE user_id=? AND trigger='manual' AND completed_at>datetime('now','-10 minutes') ORDER BY completed_at DESC LIMIT 1`).bind(uid).first<any>():null; if(last) throw new Error('Manual refresh cooldown is active'); const wh=['user_id=?','is_active<>0','automatic_price_refresh=1']; const b:any[]=[uid]; if(ids.length){wh.push(`id IN (${ids.map(()=>'?').join(',')})`); b.push(...ids)} if(scope==='stocks') wh.push("asset_type='stock'"); if(scope==='mutual_funds') wh.push("asset_type='mutual_fund'"); const assets=(await c.env.DB.prepare(`SELECT * FROM investment_assets WHERE ${wh.join(' AND ')}`).bind(...b).all<any>()).results; if(ids.length&&assets.length!==ids.length) throw new Error('Invalid asset ownership'); const run=await c.env.DB.prepare(`INSERT INTO wealth_price_refresh_runs (user_id,provider,status,trigger,scope,target_date,requested_count) VALUES (?,'indian_eod','processing',?,?,?,?)`).bind(uid,opts.trigger||'manual',scope,targetDate,assets.length).run(); const runId=Number(run.meta.last_row_id); const results:any[]=[]; const providers:any={nse_bhavcopy:0,yahoo_finance:0,mfapi:0}; let updated=0, unchanged=0, failed=0; try{ const stockAssets=assets.filter(a=>a.asset_type==='stock'); const mfAssets=assets.filter(a=>a.asset_type==='mutual_fund'); const nseAssets=stockAssets.filter(a=>a.price_provider==='nse_bhavcopy'); const yahooAssets=stockAssets.filter(a=>a.price_provider==='yahoo_finance'); const mfProvider=new MfApiProvider(); const nse=new NseBhavcopyProvider(); const yahoo=new YahooFinanceProvider(); const seen=new Set<number>(); const nseResult=nseAssets.length?await nse.fetchPrices({targetDate,assets:nseAssets}):{status:'no_new_data',prices:[] as MarketPrice[],error:''}; for(const p of nseResult.prices){ seen.add(Number(p.assetId)); providers.nse_bhavcopy++; const s=await save(c,uid,p,opts.force); s==='updated'?updated++:unchanged++; results.push({assetId:p.assetId,provider_requested:'nse_bhavcopy',provider_used:p.provider,status:s,price:p.close,tradeDate:p.tradeDate}); }
 const missingNse=nseAssets.filter(a=>!seen.has(a.id)); const yres=[...yahooAssets,...missingNse].length?await yahoo.fetchPrices({targetDate,assets:[...yahooAssets,...missingNse]}):{status:'no_new_data',prices:[] as MarketPrice[],error:''}; for(const p of yres.prices){ providers.yahoo_finance++; const s=await save(c,uid,p,opts.force); s==='updated'?updated++:unchanged++; results.push({assetId:p.assetId,provider_requested:'yahoo_finance',provider_used:p.provider,status:s,price:p.close,tradeDate:p.tradeDate}); }
 const mres=mfAssets.length?await mfProvider.fetchPrices({targetDate,assets:mfAssets}):{status:'no_new_data',prices:[] as MarketPrice[],error:''}; for(const p of mres.prices){ providers.mfapi++; const s=await save(c,uid,p,opts.force); s==='updated'?updated++:unchanged++; results.push({assetId:p.assetId,provider_requested:'mfapi',provider_used:p.provider,status:s,price:p.close,tradeDate:p.tradeDate}); }
 const covered=new Set(results.map(r=>Number(r.assetId))); for(const a of assets.filter(a=>!covered.has(a.id))){ failed++; const err=a.price_provider==='nse_bhavcopy'?nseResult.error:yres.error||mres.error||'No provider data available'; await c.env.DB.prepare(`UPDATE investment_assets SET last_price_refresh_at=datetime('now'),last_price_refresh_status='failed',last_price_refresh_error=? WHERE user_id=? AND id=?`).bind(String(err||'No data').slice(0,240),uid,a.id).run(); results.push({assetId:a.id,assetName:a.name,provider_requested:a.price_provider,status:'failed',error:String(err||'No data').slice(0,240)}); }
 const status=statusOf(updated,failed,unchanged); await c.env.DB.prepare(`UPDATE wealth_price_refresh_runs SET status=?,updated_count=?,skipped_count=?,failed_count=?,provider_counts_json=?,result_json=?,completed_at=datetime('now') WHERE id=?`).bind(status,updated,unchanged,failed,JSON.stringify(providers),JSON.stringify(results).slice(0,50000),runId).run(); return {batchId:runId,requested:assets.length,updated,unchanged,failed,providers,results,status}; }catch(e:any){ await c.env.DB.prepare(`UPDATE wealth_price_refresh_runs SET status='failed',failed_count=?,batch_error=?,completed_at=datetime('now') WHERE id=?`).bind(assets.length,String(e.message||e).slice(0,240),runId).run(); throw e; } }
export async function refreshHistory(c:AppContext,batchId?:number){ const uid=c.get('userId'); if(batchId){ const r=await c.env.DB.prepare('SELECT * FROM wealth_price_refresh_runs WHERE user_id=? AND id=?').bind(uid,batchId).first<any>(); return r?{...r,providers:JSON.parse(r.provider_counts_json||'{}'),results:JSON.parse(r.result_json||'[]')}:null; } const rows=(await c.env.DB.prepare('SELECT * FROM wealth_price_refresh_runs WHERE user_id=? ORDER BY created_at DESC,id DESC LIMIT 20').bind(uid).all<any>()).results; return rows.map(r=>({...r,providers:JSON.parse(r.provider_counts_json||'{}')})); }
