import type { AppContext, Bindings } from '../types';
import { getMarketDataProvider, marketConfig, marketProviderName } from '../market-data/provider';
import type { MarketDataProvider, QuoteRequest, SafeProviderError } from '../market-data/types';
import { safeError } from '../market-data/types';
import { formatDecimal, parseDecimal } from './decimal';

export type RefreshResult = { asset_id:number|null; symbol:string|null; exchange:string|null; status:'updated'|'skipped'|'failed'; price?:string; price_date?:string; reason?:string; error_code?:string; safe_message?:string; provider_http_status?:number; retryable?:boolean };
export type RefreshSummary = { provider:string; status?:string; requested:number; updated:number; skipped:number; failed:number; price_date:string|null; results:RefreshResult[]; warnings:string[]; estimated_provider_requests:number; error?:SafeProviderError|null; open_stock_asset_count?:number; missing_price_asset_count?:number; unsupported_asset_count?:number; max_symbols_per_refresh?:number };
const today = () => new Date().toISOString().slice(0,10);
const up = (v:any) => String(v ?? '').trim().toUpperCase();
function openQtySql() { return `EXISTS (SELECT 1 FROM investment_transactions t JOIN portfolios p ON p.id=t.account_id WHERE t.user_id=a.user_id AND t.asset_id=a.id AND p.valuation_mode<>'manual_snapshot' GROUP BY t.asset_id HAVING SUM(CASE WHEN t.transaction_type IN ('buy','sip','contribution','transfer_in','bonus') THEN CAST(COALESCE(t.quantity,'0') AS REAL) WHEN t.transaction_type IN ('sell','redemption','withdrawal','transfer_out') THEN -CAST(COALESCE(t.quantity,'0') AS REAL) ELSE 0 END) > 0)`; }
export async function marketPriceStatus(c:AppContext){ const uid=c.get('userId'), cfg=marketConfig(c.env), provider=marketProviderName(c.env); const last=await c.env.DB.prepare(`SELECT * FROM wealth_price_refresh_runs WHERE user_id=? ORDER BY COALESCE(completed_at, created_at) DESC,id DESC LIMIT 1`).bind(uid).first<any>(); const rows=await c.env.DB.prepare(`SELECT a.*, ${openQtySql()} has_open_holding, (SELECT price_date FROM investment_prices p WHERE p.user_id=a.user_id AND p.asset_id=a.id ORDER BY price_date DESC,id DESC LIMIT 1) latest_price_date FROM investment_assets a WHERE a.user_id=?`).bind(uid).all<any>(); let eligible=0, open=0, missing=0, stale=0, unsupported=0; const cutoff=new Date(Date.now()-cfg.staleHours*3600000).toISOString().slice(0,10); for(const a of rows.results){ const ok=a.is_active!==0&&a.asset_type==='stock'&&['NSE','BSE'].includes(up(a.exchange))&&up(a.symbol); if(!ok){unsupported++; continue;} eligible++; if(a.has_open_holding) open++; if(!a.latest_price_date) missing++; else if(a.latest_price_date<cutoff) stale++; } return {provider,configured:provider==='marketstack'?!!c.env.MARKETSTACK_API_KEY:!!c.env.TWELVE_DATA_API_KEY,last_run_status:last?.status||null,last_successful_refresh_at:['completed','partially_completed'].includes(last?.status)?last?.completed_at||null:null,last_run_warning:last?.warning_json||null,eligible_stock_asset_count:eligible,open_stock_asset_count:open,open_holding_asset_count:open,missing_price_asset_count:missing,missing_price_count:missing,stale_price_asset_count:stale,stale_price_count:stale,unsupported_asset_count:unsupported,max_symbols_per_refresh:cfg.maxSymbols}; }
export async function refreshMarketPrices(c:AppContext, opts:{asset_ids?:number[]; only_open_holdings?:boolean; force?:boolean; provider?:MarketDataProvider}):Promise<RefreshSummary>{ const uid=c.get('userId'), env=c.env, cfg=marketConfig(env), providerInfo=opts.provider?{configured:true,provider:opts.provider}:{...getMarketDataProvider(env)}; const providerName=opts.provider?.name||marketProviderName(env); const warnings:string[]=[]; let runId:number|undefined; const finish=async(status:string,s:RefreshSummary)=>{ if(runId) await env.DB.prepare(`UPDATE wealth_price_refresh_runs SET status=?,requested_count=?,updated_count=?,skipped_count=?,failed_count=?,warning_json=?,completed_at=datetime('now') WHERE id=?`).bind(status,s.requested,s.updated,s.skipped,s.failed,JSON.stringify(s.warnings),runId).run(); return s; };
  const rr=await env.DB.prepare(`INSERT INTO wealth_price_refresh_runs (user_id,provider,status) VALUES (?,?, 'processing')`).bind(uid,providerName).run(); runId=Number(rr.meta.last_row_id);
  try{ if(!providerInfo.configured||!providerInfo.provider) { const e=safeError('provider_not_configured',providerInfo.error||'Market data provider is not configured',undefined,false); const summary={provider:providerName,status:'failed',requested:0,updated:0,skipped:0,failed:1,price_date:null,results:[{asset_id:null,symbol:null,exchange:null,status:'failed' as const,reason:e.safe_message,error_code:e.error_code,safe_message:e.safe_message,retryable:e.retryable}],warnings:[e.error_code],estimated_provider_requests:0,error:e}; return finish('failed',summary); } const ids=[...new Set((opts.asset_ids||[]).map(Number).filter(Boolean))]; if(ids.length>cfg.maxSymbols) throw new Error('Too many assets requested'); const wh=['a.user_id=?']; const b:any[]=[providerName,uid]; if(ids.length){wh.push(`a.id IN (${ids.map(()=>'?').join(',')})`); b.push(...ids)} let sql=`SELECT a.*, ps.provider_symbol, ps.provider_exchange, ${openQtySql()} has_open_holding, (SELECT price_date FROM investment_prices p WHERE p.user_id=a.user_id AND p.asset_id=a.id ORDER BY price_date DESC,id DESC LIMIT 1) latest_price_date, (SELECT source FROM investment_prices p WHERE p.user_id=a.user_id AND p.asset_id=a.id ORDER BY price_date DESC,id DESC LIMIT 1) latest_source FROM investment_assets a LEFT JOIN wealth_provider_symbols ps ON ps.user_id=a.user_id AND ps.asset_id=a.id AND ps.provider=? WHERE ${wh.join(' AND ')}`; const assets=(await env.DB.prepare(sql).bind(...b).all<any>()).results; if(ids.length&&assets.length!==ids.length) throw new Error('Invalid asset ownership'); const results:RefreshResult[]=[]; const reqs:({asset:any; req:QuoteRequest})[]=[]; const cutoff=new Date(Date.now()-cfg.staleHours*3600000).toISOString().slice(0,10);
    for(const a of assets){ const symbol=up(a.symbol), exchange=up(a.exchange); const base={asset_id:a.id,symbol:a.symbol,exchange:a.exchange}; if(a.is_active===0){results.push({...base,status:'skipped',reason:'inactive_asset'});continue} if(a.asset_type!=='stock'){results.push({...base,status:'skipped',reason:'non_stock_asset'});continue} if(opts.only_open_holdings!==false&&!a.has_open_holding){results.push({...base,status:'skipped',reason:'closed_holding'});continue} if(a.pricing_mode==='not_priced'||(a.price_source==='manual'&&a.pricing_mode==='manual'&&!opts.force)){results.push({...base,status:'skipped',reason:'manual_pricing_asset'});continue} if(!symbol||!['NSE','BSE'].includes(exchange)){results.push({...base,status:'failed',reason:'unsupported_symbol_or_exchange'});continue} if(!opts.force&&a.latest_source==='market'&&a.latest_price_date&&a.latest_price_date>=cutoff){results.push({...base,status:'skipped',reason:'fresh_market_price'});continue} reqs.push({asset:a,req:{symbol:a.provider_symbol||symbol,exchange:(a.provider_exchange||exchange) as any,assetId:a.id}}); }
    if(reqs.length>cfg.maxSymbols) throw new Error('Too many assets requested'); const ac=new AbortController(); const timer=setTimeout(()=>ac.abort(),cfg.timeoutMs); const outcomes=await providerInfo.provider.getQuotes(reqs.map(x=>x.req), ac.signal).finally(()=>clearTimeout(timer));
    for(let i=0;i<outcomes.length;i++){ const o=outcomes[i], a=reqs[i].asset, base={asset_id:a.id,symbol:a.symbol,exchange:a.exchange}; if(!o.ok){results.push({...base,status:'failed',reason:o.safe_message||o.error,error_code:o.error_code,safe_message:o.safe_message||o.error,provider_http_status:o.provider_http_status,retryable:o.retryable});continue} const q=o.quote; const priceDate=q.market_timestamp.slice(0,10); try{ if(priceDate>today()) throw new Error('future_market_price'); if(q.currency!=='INR') throw new Error('currency_mismatch'); if(up(q.exchange)!==up(a.exchange)&&!a.provider_exchange) throw new Error('symbol_mismatch'); const price=formatDecimal(parseDecimal(q.price,{allowZero:false})); const same=await env.DB.prepare(`SELECT source FROM investment_prices WHERE user_id=? AND asset_id=? AND price_date=?`).bind(uid,a.id,priceDate).first<any>(); if(same&&same.source!=='market'&&!opts.force){results.push({...base,status:'skipped',reason:'manual_same_date_price_protected'});continue} const newer=await env.DB.prepare(`SELECT price_date FROM investment_prices WHERE user_id=? AND asset_id=? AND price_date>? ORDER BY price_date DESC LIMIT 1`).bind(uid,a.id,priceDate).first<any>(); if(newer&&!opts.force){results.push({...base,status:'skipped',reason:'newer_price_exists'});continue} await env.DB.prepare(`INSERT INTO investment_prices (user_id,asset_id,price_date,price,currency,source,notes) VALUES (?,?,?,?,?,'market',?) ON CONFLICT(user_id,asset_id,price_date) DO UPDATE SET price=excluded.price,currency=excluded.currency,source=excluded.source,notes=excluded.notes,updated_at=datetime('now')`).bind(uid,a.id,priceDate,price,'INR',`${q.provider} ${q.data_kind} ${q.symbol}.${q.exchange}`).run(); results.push({...base,status:'updated',price,price_date:priceDate}); }catch(e:any){results.push({...base,status:'failed',reason:e.message||'validation_failed'});} }
    const failedResult=results.find(r=>r.status==='failed'&&r.error_code); const topError=failedResult&&!results.some(r=>r.status==='updated')?safeError(failedResult.error_code as any,failedResult.safe_message||failedResult.reason||'Refresh failed',{symbol:failedResult.symbol||undefined,exchange:failedResult.exchange as any},!!failedResult.retryable,failedResult.provider_http_status):null; const status=results.filter(r=>r.status==='failed').length?results.some(r=>r.status==='updated')?'partially_completed':'failed':'completed'; const summary={provider:providerName,status,requested:assets.length,updated:results.filter(r=>r.status==='updated').length,skipped:results.filter(r=>r.status==='skipped').length,failed:results.filter(r=>r.status==='failed').length,price_date:results.find(r=>r.price_date)?.price_date||null,results,warnings:topError?[topError.error_code]:warnings,estimated_provider_requests:reqs.length,error:topError}; return finish(status,summary);
  }catch(e:any){ const se=safeError(e?.code||'market_data_error',e.message||'Refresh failed',undefined,!!e?.retryable); const summary={provider:providerName,status:'failed',requested:0,updated:0,skipped:0,failed:1,price_date:null,results:[{asset_id:null,symbol:null,exchange:null,status:'failed' as const,reason:se.safe_message,error_code:se.error_code,safe_message:se.safe_message,retryable:se.retryable}],warnings:[se.error_code],estimated_provider_requests:0,error:se}; return finish('failed',summary); }
}
