export type XirrCashFlow = { date: string; amount: number; source?: string; transactionId?: number };
export type XirrStatus = 'ok'|'insufficient_cash_flows'|'no_sign_change'|'no_convergence'|'invalid_date';
export type XirrResult = { status: XirrStatus; value: number|null; method?: 'newton'|'bisection'; iterations?: number; npv?: number; cashFlowCount: number; firstDate?: string; lastDate?: string; reason?: string };
const DAY = 86400000, NPV_TOL = 1e-7, RATE_TOL = 1e-10, MAX_ITER = 100, LOW = -0.999999999, HIGH_CAP = 1e6;
function validDate(s:string){ if(!/^\d{4}-\d{2}-\d{2}$/.test(s)) return false; const [y,m,d]=s.split('-').map(Number); const t=Date.UTC(y,m-1,d); const dt=new Date(t); return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d; }
function utc(s:string){ const [y,m,d]=s.split('-').map(Number); return Date.UTC(y,m-1,d); }
export function combineSameDateCashFlows(flows:XirrCashFlow[]):XirrCashFlow[]{ const m=new Map<string,number>(); for(const f of flows) m.set(f.date,(m.get(f.date)??0)+f.amount); return [...m.entries()].filter(([,a])=>Math.abs(a)>1e-9).sort(([a],[b])=>a.localeCompare(b)).map(([date,amount])=>({date,amount})); }
export function validateXirrCashFlows(flows:XirrCashFlow[]):XirrResult{ if(!flows.length) return {status:'insufficient_cash_flows',value:null,cashFlowCount:0,reason:'At least two dated cash flows are required'}; if(flows.some(f=>!validDate(f.date)||!Number.isFinite(f.amount))) return {status:'invalid_date',value:null,cashFlowCount:flows.length,reason:'Cash flows require valid YYYY-MM-DD dates and finite amounts'}; const c=combineSameDateCashFlows(flows); const base={cashFlowCount:c.length,firstDate:c[0]?.date,lastDate:c.at(-1)?.date}; if(c.length<2) return {status:'insufficient_cash_flows',value:null,...base,reason:'At least two non-zero dated cash flows are required'}; if(!c.some(f=>f.amount>0)||!c.some(f=>f.amount<0)) return {status:'no_sign_change',value:null,...base,reason:'XIRR requires at least one positive and one negative cash flow'}; return {status:'ok',value:null,...base}; }
export function calculateXnpv(rate:number, flows:XirrCashFlow[]):number{ if(rate<=-1||!Number.isFinite(rate)) return Number.NaN; const c=combineSameDateCashFlows(flows); const start=utc(c[0].date); return c.reduce((s,f)=>s+f.amount/Math.pow(1+rate,(utc(f.date)-start)/DAY/365),0); }
export function calculateXnpvDerivative(rate:number, flows:XirrCashFlow[]):number{ if(rate<=-1||!Number.isFinite(rate)) return Number.NaN; const c=combineSameDateCashFlows(flows); const start=utc(c[0].date); return c.reduce((s,f)=>{ const years=(utc(f.date)-start)/DAY/365; return s - years*f.amount/Math.pow(1+rate,years+1); },0); }
function done(method:'newton'|'bisection', rate:number, i:number, flows:XirrCashFlow[], meta:XirrResult):XirrResult{ return {...meta,status:'ok',value:rate,method,iterations:i,npv:calculateXnpv(rate,flows)}; }
export function calculateXirr(flows:XirrCashFlow[]):XirrResult{ const meta=validateXirrCashFlows(flows); if(meta.status!=='ok') return meta; const cf=combineSameDateCashFlows(flows); let r=0.1; for(let i=1;i<=MAX_ITER;i++){ const n=calculateXnpv(r,cf), d=calculateXnpvDerivative(r,cf); if(Math.abs(n)<NPV_TOL) return done('newton',r,i,cf,meta); if(!Number.isFinite(d)||Math.abs(d)<1e-12) break; const nr=r-n/d; if(!Number.isFinite(nr)||nr<=-1||Math.abs(nr)>HIGH_CAP) break; if(Math.abs(nr-r)<RATE_TOL) return done('newton',nr,i,cf,meta); r=nr; }
 let lo=LOW, hi=1, flo=calculateXnpv(lo,cf), fhi=calculateXnpv(hi,cf), expands=0; while(Number.isFinite(flo)&&Number.isFinite(fhi)&&flo*fhi>0&&hi<HIGH_CAP&&expands++<60){ hi*=2; fhi=calculateXnpv(hi,cf); }
 if(!Number.isFinite(flo)||!Number.isFinite(fhi)||flo*fhi>0) return {...meta,status:'no_convergence',value:null,reason:'Unable to bracket an XIRR root within the supported rate range'};
 for(let i=1;i<=MAX_ITER;i++){ const mid=(lo+hi)/2, fm=calculateXnpv(mid,cf); if(Math.abs(fm)<NPV_TOL||Math.abs(hi-lo)<RATE_TOL) return done('bisection',mid,i,cf,meta); if(flo*fm<=0){hi=mid; fhi=fm;} else {lo=mid; flo=fm;} }
 return {...meta,status:'no_convergence',value:null,reason:'XIRR solver did not converge within iteration limit',npv:calculateXnpv((lo+hi)/2,cf)}; }
export const isValidXirrDate = validDate;
