export type MarketDataKind = 'delayed' | 'realtime' | 'eod' | 'unknown';
export type MarketDataErrorCode = 'provider_not_configured'|'provider_authentication_failed'|'plan_access_restricted'|'rate_limited'|'quota_exceeded'|'symbol_not_found'|'timeout'|'provider_5xx'|'malformed_provider_response'|'currency_mismatch'|'symbol_mismatch'|'market_data_error';
export type QuoteRequest = { symbol: string; exchange: 'NSE' | 'BSE'; assetId?: number };
export type SafeProviderError = { status:'failed'; error_code:MarketDataErrorCode; safe_message:string; provider_http_status?:number; symbol?:string; exchange?:string; retryable:boolean; provider_status?:string|number; provider_code?:string|number };
export type MarketQuote = { provider: string; provider_timestamp: string; market_timestamp: string; currency: string; symbol: string; exchange: string; price: string; raw_status?: string; data_kind: MarketDataKind };
export type QuoteOutcome = { ok: true; request: QuoteRequest; quote: MarketQuote } | { ok: false; request: QuoteRequest; error: string; error_code?:MarketDataErrorCode; safe_message?:string; provider_http_status?:number; retryable?: boolean; provider_status?:string|number; provider_code?:string|number };
export interface MarketDataProvider { name: string; getQuote(request: QuoteRequest, signal?: AbortSignal): Promise<QuoteOutcome>; getQuotes(requests: QuoteRequest[], signal?: AbortSignal): Promise<QuoteOutcome[]>; }
export class SafeMarketDataError extends Error { constructor(message: string, public code:MarketDataErrorCode = 'market_data_error', public retryable = false) { super(message); } }
const SENSITIVE = /([?&](?:apikey|api_key|token|authorization)=)[^&\s]+|Bearer\s+[A-Za-z0-9._\-]+|[A-Za-z0-9_\-]{16,}/gi;
export function safeProviderError(err: unknown): string { const msg = err instanceof Error ? err.message : String(err || 'Provider error'); return msg.replace(SENSITIVE, (_m,p)=>p?`${p}[redacted]`:'[redacted]'); }
export function safeError(code:MarketDataErrorCode, message:string, req?:Partial<QuoteRequest>, retryable=false, http?:number, extra:Partial<SafeProviderError>={}):SafeProviderError{ return {status:'failed',error_code:code,safe_message:safeProviderError(message),provider_http_status:http,symbol:req?.symbol,exchange:req?.exchange,retryable,...extra}; }
export function outcomeError(request:QuoteRequest, code:MarketDataErrorCode, message:string, retryable=false, http?:number, extra:any={}):QuoteOutcome{ const e=safeError(code,message,request,retryable,http,extra); return {ok:false,request,error:e.safe_message,error_code:e.error_code,safe_message:e.safe_message,provider_http_status:e.provider_http_status,retryable:e.retryable,provider_status:e.provider_status,provider_code:e.provider_code}; }
