import { Hono } from 'hono';
import type { Bindings, Variables, AppContext } from '../types';
import { audit, assertDate, calculateBalance, finiteInt, previewReconciliation, wallet } from '../account-balance-service';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>(); const bad=(c:AppContext,m:string,code=400)=>c.json({error:m},code as any);
async function rec(c:AppContext,uid:number,id:any){return c.env.DB.prepare('SELECT * FROM account_reconciliations WHERE user_id=? AND id=?').bind(uid,id).first<any>();}
async function ensureUnlocked(c:AppContext,uid:number,id:any){const r=await rec(c,uid,id); if(!r)throw new Error('Not found'); if(r.locked)throw new Error('Reconciliation is locked'); return r;}
app.get('/',async c=>{const uid=c.get('userId'); const rows=(await c.env.DB.prepare('SELECT r.*,w.name wallet_name FROM account_reconciliations r JOIN wallets w ON w.id=r.wallet_id AND w.user_id=r.user_id WHERE r.user_id=? ORDER BY r.created_at DESC LIMIT 100').bind(uid).all()).results; return c.json({reconciliations:rows});});
app.post('/',async c=>{try{const uid=c.get('userId'), b=await c.req.json(); const ps=assertDate(b.period_start,'period_start'), pe=assertDate(b.period_end,'period_end'); if(pe<ps)return bad(c,'period_end must not precede period_start'); if(!await wallet(c,uid,b.wallet_id))return bad(c,'Wallet not found',404); const overlap=await c.env.DB.prepare(`SELECT id FROM account_reconciliations WHERE user_id=? AND wallet_id=? AND status NOT IN ('cancelled','locked') AND NOT (date(period_end)<date(?) OR date(period_start)>date(?)) LIMIT 1`).bind(uid,b.wallet_id,ps,pe).first<any>(); if(overlap&&!b.allow_overlap)return bad(c,'Active reconciliation overlaps this period',409); const res=await c.env.DB.prepare(`INSERT INTO account_reconciliations (user_id,wallet_id,period_start,period_end,opening_balance,statement_closing_balance,source,import_batch_id,notes) VALUES (?,?,?,?,?,?,?,?,?)`).bind(uid,b.wallet_id,ps,pe,b.opening_balance==null?null:finiteInt(b.opening_balance,'opening_balance'),b.statement_closing_balance==null?null:finiteInt(b.statement_closing_balance,'statement_closing_balance'),b.source||'manual',b.import_batch_id||null,b.notes||null).run(); await audit(c,uid,'reconciliation_started',{wallet_id:b.wallet_id,period_start:ps,period_end:pe},res.meta.last_row_id); return c.json({id:res.meta.last_row_id},201);}catch(e:any){return bad(c,e.message);}});
app.get('/history',async c=>{const uid=c.get('userId'); const rows=(await c.env.DB.prepare(`SELECT r.*,w.name wallet_name FROM account_reconciliations r JOIN wallets w ON w.id=r.wallet_id AND w.user_id=r.user_id WHERE r.user_id=? AND r.status IN ('reconciled','small_difference','unreconciled','locked','cancelled') ORDER BY COALESCE(r.reconciled_at,r.updated_at) DESC`).bind(uid).all()).results; return c.json({history:rows});});
app.get('/:id',async c=>{const uid=c.get('userId'), r=await rec(c,uid,c.req.param('id')); if(!r)return bad(c,'Not found',404); const rows=(await c.env.DB.prepare('SELECT * FROM account_reconciliation_rows WHERE user_id=? AND reconciliation_id=? ORDER BY transaction_date,id LIMIT 500').bind(uid,r.id).all()).results; return c.json({reconciliation:r,rows});});
app.put('/:id',async c=>{try{const uid=c.get('userId'), id=c.req.param('id'), r=await ensureUnlocked(c,uid,id), b=await c.req.json(); await c.env.DB.prepare(`UPDATE account_reconciliations SET opening_balance=?,statement_closing_balance=?,notes=?,updated_at=datetime('now') WHERE user_id=? AND id=?`).bind(b.opening_balance??r.opening_balance,b.statement_closing_balance??r.statement_closing_balance,b.notes??r.notes,uid,id).run(); return c.json({success:true});}catch(e:any){return bad(c,e.message,e.message==='Not found'?404:400);}});
app.delete('/:id',async c=>{try{const uid=c.get('userId'), id=c.req.param('id'); await ensureUnlocked(c,uid,id); await c.env.DB.prepare("UPDATE account_reconciliations SET status='cancelled',updated_at=datetime('now') WHERE user_id=? AND id=?").bind(uid,id).run(); await audit(c,uid,'reconciliation_cancelled',{},id); return c.json({success:true,deleted_movements:false});}catch(e:any){return bad(c,e.message);}});
app.post('/:id/preview',async c=>{const uid=c.get('userId'), r=await rec(c,uid,c.req.param('id')); if(!r)return bad(c,'Not found',404); return c.json(await previewReconciliation(c,uid,r));});
app.post('/:id/auto-match',async c=>{try{const uid=c.get('userId'), id=c.req.param('id'), r=await ensureUnlocked(c,uid,id); let matched=0; const imports=(await c.env.DB.prepare('SELECT * FROM financial_import_rows WHERE user_id=? AND batch_id=? AND validation_status="valid"').bind(uid,r.import_batch_id||-1).all<any>()).results; const used=new Set<number>(); for(const ir of imports){ const mv=await c.env.DB.prepare(`SELECT * FROM movements WHERE user_id=? AND COALESCE(status,'active')='active' AND amount=? AND date(date) BETWEEN date(?,'-3 day') AND date(?,'+3 day') AND ((src_kind='wallet' AND src_id=?) OR (dst_kind='wallet' AND dst_id=?)) ORDER BY CASE WHEN date=? THEN 0 ELSE 1 END,id LIMIT 5`).bind(uid,ir.normalized_amount,ir.normalized_date,ir.normalized_date,r.wallet_id,r.wallet_id,ir.normalized_date).first<any>(); const exact=mv && mv.date===ir.normalized_date && !used.has(mv.id); await c.env.DB.prepare(`INSERT INTO account_reconciliation_rows (user_id,reconciliation_id,movement_id,import_row_id,row_type,transaction_date,amount,direction,description,reference_number,match_status,resolution,confidence,duplicate_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid,id,exact?mv.id:null,ir.id,exact?'imported_statement_row':'unmatched_statement_row',ir.normalized_date,ir.normalized_amount,ir.normalized_direction,ir.normalized_description,ir.normalized_reference,exact?'exact':'unmatched',exact?'matched_existing':'unresolved',exact?'exact':'unmatched',ir.duplicate_status==='new'?'not_duplicate':ir.duplicate_status).run(); if(exact){matched++; used.add(mv.id);} } await audit(c,uid,'rows_auto_matched',{matched,total:imports.length},id); return c.json({matched,total:imports.length});}catch(e:any){return bad(c,e.message);}});
app.post('/:id/rows/:row_id/resolve',async c=>{try{const uid=c.get('userId'), id=c.req.param('id'), row=c.req.param('row_id'), b=await c.req.json(); await ensureUnlocked(c,uid,id); await c.env.DB.prepare(`UPDATE account_reconciliation_rows SET resolution=?,match_status='resolved',discrepancy_reason=?,updated_at=datetime('now') WHERE user_id=? AND reconciliation_id=? AND id=?`).bind(b.resolution,b.reason||null,uid,id,row).run(); await audit(c,uid,'row_resolved',{row_id:row,resolution:b.resolution},id); return c.json({success:true});}catch(e:any){return bad(c,e.message);}});
app.post('/:id/reconcile',async c=>{const uid=c.get('userId'), id=c.req.param('id'); try{const r=await ensureUnlocked(c,uid,id), p=await previewReconciliation(c,uid,r); await c.env.DB.prepare(`UPDATE account_reconciliations SET opening_balance=?,expected_closing_balance=?,difference=?,status=?,matched_count=?,unresolved_count=?,reconciled_at=datetime('now'),updated_at=datetime('now') WHERE user_id=? AND id=?`).bind(p.opening_balance,p.expected_closing_balance,p.difference,p.reconciliation_status,p.matched_movement_count,p.unmatched_statement_count,uid,id).run(); await audit(c,uid,'reconciliation_completed',{status:p.reconciliation_status,difference:p.difference},id); return c.json(p);}catch(e:any){return bad(c,e.message);}});
app.post('/:id/lock',async c=>{const uid=c.get('userId'), id=c.req.param('id'), r=await rec(c,uid,id); if(!r)return bad(c,'Not found',404); await c.env.DB.prepare(`UPDATE account_reconciliations SET locked=1,status='locked',locked_at=datetime('now'),updated_at=datetime('now') WHERE user_id=? AND id=?`).bind(uid,id).run(); await audit(c,uid,'reconciliation_locked',{},id); return c.json({success:true});});
app.post('/:id/unlock',async c=>{const uid=c.get('userId'), id=c.req.param('id'); await c.env.DB.prepare(`UPDATE account_reconciliations SET locked=0,status='in_review',locked_at=NULL,updated_at=datetime('now') WHERE user_id=? AND id=?`).bind(uid,id).run(); await audit(c,uid,'reconciliation_unlocked',{},id); return c.json({success:true});});
app.post('/:id/cancel',async c=>{const uid=c.get('userId'), id=c.req.param('id'); await c.env.DB.prepare(`UPDATE account_reconciliations SET status='cancelled',updated_at=datetime('now') WHERE user_id=? AND id=? AND locked=0`).bind(uid,id).run(); await audit(c,uid,'reconciliation_cancelled',{},id); return c.json({success:true,deleted_movements:false});});
app.post('/:id/adjustment-preview',async c=>{const uid=c.get('userId'), id=c.req.param('id'), r=await rec(c,uid,id), b=await c.req.json(); if(!r)return bad(c,'Not found',404); const amount=finiteInt(b.amount,'amount'); return c.json({wallet_id:r.wallet_id,adjustment_date:b.adjustment_date||r.period_end,amount,direction:b.direction||'credit',reason:b.reason||'other',requires_confirmation:true,will_create_movement:false,projected_difference:(r.difference||0)+(b.direction==='debit'?-amount:amount)});});
app.post('/:id/adjustment-commit',async c=>{try{const uid=c.get('userId'), id=c.req.param('id'), r=await ensureUnlocked(c,uid,id), b=await c.req.json(); if(!b.confirm)return bad(c,'Explicit confirmation required'); const amount=finiteInt(b.amount,'amount'), dir=b.direction==='debit'?'debit':'credit'; const res=await c.env.DB.prepare(`INSERT INTO account_reconciliation_rows (user_id,reconciliation_id,row_type,transaction_date,amount,direction,description,match_status,resolution,confidence,discrepancy_reason) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(uid,id,'balance_adjustment',b.adjustment_date||r.period_end,amount,dir,'[Reconciliation adjustment] '+(b.reason||'other'),'resolved','create_adjustment','exact',b.notes||null).run(); await audit(c,uid,'adjustment_committed',{amount,direction:dir,reason:b.reason},id); return c.json({id:res.meta.last_row_id,created_movement_id:null});}catch(e:any){return bad(c,e.message);}});
export default app;
export { calculateBalance };
