import { Hono } from 'hono';
import type { Bindings, Variables, AppContext } from '../types';
import { SNAPSHOT_SOURCES, assertDate, audit, finiteInt, wallet } from '../account-balance-service';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>(); const bad=(c:AppContext,m:string,code=400)=>c.json({error:m},code as any);
function noFuture(d:string){ if(d>new Date().toISOString().slice(0,10)) throw new Error('Future snapshot dates are not supported'); }
app.get('/snapshots',async c=>{ const uid=c.get('userId'), wid=c.req.query('wallet_id'); const rows=(await c.env.DB.prepare(`SELECT s.*,w.name wallet_name FROM account_balance_snapshots s JOIN wallets w ON w.id=s.wallet_id AND w.user_id=s.user_id WHERE s.user_id=? ${wid?'AND s.wallet_id=?':''} ORDER BY date(s.snapshot_date) DESC,s.id DESC LIMIT 200`).bind(...(wid?[uid,wid]:[uid])).all()).results; return c.json({snapshots:rows}); });
app.post('/snapshots',async c=>{ try{ const uid=c.get('userId'), b=await c.req.json(); const d=assertDate(b.snapshot_date,'snapshot_date'); noFuture(d); if(!SNAPSHOT_SOURCES.includes(b.source))return bad(c,'Invalid source'); if(!await wallet(c,uid,b.wallet_id))return bad(c,'Wallet not found',404); const balance=finiteInt(b.balance,'balance'); const res=await c.env.DB.prepare(`INSERT INTO account_balance_snapshots (user_id,wallet_id,snapshot_date,balance,available_balance,ledger_balance,currency,source,statement_period_start,statement_period_end,import_batch_id,external_reference,notes,is_reconciled) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid,b.wallet_id,d,balance,b.available_balance==null?null:finiteInt(b.available_balance,'available_balance'),b.ledger_balance==null?null:finiteInt(b.ledger_balance,'ledger_balance'),b.currency||'IDR',b.source,b.statement_period_start||null,b.statement_period_end||null,b.import_batch_id||null,b.external_reference||null,b.notes||null,b.is_reconciled?1:0).run(); await audit(c,uid,'snapshot_created',{wallet_id:b.wallet_id,source:b.source},null,res.meta.last_row_id); return c.json({id:res.meta.last_row_id},201); }catch(e:any){ return bad(c,e.message, /UNIQUE/.test(e.message)?409:400); } });
app.put('/snapshots/:id',async c=>{ try{ const uid=c.get('userId'), id=c.req.param('id'), old=await c.env.DB.prepare('SELECT * FROM account_balance_snapshots WHERE user_id=? AND id=?').bind(uid,id).first<any>(); if(!old)return bad(c,'Not found',404); const b=await c.req.json(); const d=assertDate(b.snapshot_date??old.snapshot_date,'snapshot_date'); noFuture(d); if(b.source && !SNAPSHOT_SOURCES.includes(b.source))return bad(c,'Invalid source'); await c.env.DB.prepare(`UPDATE account_balance_snapshots SET snapshot_date=?,balance=?,available_balance=?,ledger_balance=?,currency=?,source=?,statement_period_start=?,statement_period_end=?,external_reference=?,notes=?,is_reconciled=?,updated_at=datetime('now') WHERE user_id=? AND id=?`).bind(d,finiteInt(b.balance??old.balance),b.available_balance??old.available_balance,b.ledger_balance??old.ledger_balance,b.currency??old.currency,b.source??old.source,b.statement_period_start??old.statement_period_start,b.statement_period_end??old.statement_period_end,b.external_reference??old.external_reference,b.notes??old.notes,b.is_reconciled==null?old.is_reconciled:(b.is_reconciled?1:0),uid,id).run(); await audit(c,uid,'snapshot_edited',{id},null,id); return c.json({success:true}); }catch(e:any){return bad(c,e.message);} });
app.delete('/snapshots/:id',async c=>{ const uid=c.get('userId'), id=c.req.param('id'); const s=await c.env.DB.prepare('SELECT * FROM account_balance_snapshots WHERE user_id=? AND id=?').bind(uid,id).first<any>(); if(!s)return bad(c,'Not found',404); await c.env.DB.prepare('DELETE FROM account_balance_snapshots WHERE user_id=? AND id=?').bind(uid,id).run(); await audit(c,uid,'snapshot_deleted',{id,source:s.source},null,id); return c.json({success:true,deleted_movements:false}); });
export default app;
