import { Hono } from 'hono';
import type { AppContext, Bindings, Variables } from '../types';
import { currentMonth } from '../types';
import { calculateBudgetRows, getBudgets } from '../budget-service';
const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();
const TYPES = new Set(['monthly_category','monthly_total','income_target','savings_target','custom_period']);
const STATUSES = new Set(['active','paused','archived']);
function positiveAmount(v:any){ const n=Number(v); return Number.isFinite(n)&&n>0?Math.round(n):null; }
async function categoryOk(c:AppContext, uid:number, id:any){ if(!id) return true; const row=await c.env.DB.prepare('SELECT id FROM categories WHERE id=? AND user_id=?').bind(id,uid).first(); return !!row; }
async function parseBody(c:AppContext, uid:number, partial=false){ const b=await c.req.json<any>(); const amount=positiveAmount(b.amount ?? b.budget_amount); if(!partial && !amount) return {error:'Budget amount must be positive and finite'}; const type=b.budget_type||'monthly_category'; if(type&&!TYPES.has(type)) return {error:'Invalid budget_type'}; const status=b.status||'active'; if(status&&!STATUSES.has(status)) return {error:'Invalid status'}; const cat=b.category_id??null; if(cat && !(await categoryOk(c,uid,cat))) return {error:'Category not found'}; return {body:{name:b.name??null,month:b.month??currentMonth(),start_date:b.start_date??null,end_date:b.end_date??null,budget_type:type,category_id:cat,parent_category_id:b.parent_category_id??null,amount:amount??undefined,budget_amount:amount??undefined,rollover_enabled:b.rollover_enabled?1:0,rollover_amount:Number.isFinite(Number(b.rollover_amount))?Math.round(Number(b.rollover_amount)):0,alert_percent:Number.isFinite(Number(b.alert_percent))?Number(b.alert_percent):0.8,status,notes:b.notes??null}}; }
app.get('/summary', async c=> c.json(await calculateBudgetRows(c.env.DB,c.get('userId'),c.req.query('month')||currentMonth())));
app.post('/copy-previous-month', async (c:AppContext)=>{ const uid=c.get('userId'); const {month=currentMonth(), preview=true}=await c.req.json<any>(); const [y,m]=month.split('-').map(Number); const prev=new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7); const rows=await getBudgets(c.env.DB,uid,prev,'active'); const copy=rows.map((b:any)=>({category_id:b.category_id,name:b.name,month,amount:b.amount||b.budget_amount,budget_type:b.budget_type,rollover_enabled:b.rollover_enabled,alert_percent:b.alert_percent,status:'active'})); if(preview) return c.json({preview:true,source_month:prev,target_month:month,budgets:copy}); for(const b of copy){ await c.env.DB.prepare(`INSERT INTO budgets(user_id,name,category_id,budget_amount,month,budget_type,amount,rollover_enabled,alert_percent,status) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(uid,b.name,b.category_id,b.amount,month,b.budget_type,b.amount,b.rollover_enabled,b.alert_percent,b.status).run(); } return c.json({created:copy.length}); });
app.post('/create-from-average', async (c:AppContext)=>{ const {month=currentMonth(), preview=true}=await c.req.json<any>(); return c.json({preview,month,budgets:[],message:'Preview endpoint available; averages are calculated in category analytics before creation.'}); });
app.get('/', async (c:AppContext)=>{ const month=c.req.query('month')||currentMonth(); let rows=await calculateBudgetRows(c.env.DB,c.get('userId'),month); const cat=c.req.query('category_id'), status=c.req.query('status'), exceeded=c.req.query('exceeded_only'); if(cat) rows=rows.filter((r:any)=>String(r.category_id)===cat); if(status) rows=rows.filter((r:any)=>r.status===status||r.status===status.toLowerCase()); if(exceeded==='true') rows=rows.filter((r:any)=>r.actual_spending>r.effective_budget); return c.json(rows); });
app.post('/', async (c:AppContext)=>{ const uid=c.get('userId'); const p=await parseBody(c,uid); if('error'in p) return c.json({error:p.error},400); const b=(p as any).body; try{ const res=await c.env.DB.prepare(`INSERT INTO budgets(user_id,name,category_id,budget_amount,month,start_date,end_date,budget_type,parent_category_id,amount,rollover_enabled,rollover_amount,alert_percent,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid,b.name,b.category_id,b.budget_amount,b.month,b.start_date,b.end_date,b.budget_type,b.parent_category_id,b.amount,b.rollover_enabled,b.rollover_amount,b.alert_percent,b.status,b.notes).run(); return c.json({id:res.meta.last_row_id},201);}catch(e:any){return c.json({error:e.message?.includes('UNIQUE')?'Active category budget already exists for this month':e.message},400);} });
app.get('/:id', async (c:AppContext)=>{ const row=(await getBudgets(c.env.DB,c.get('userId'))).find((b:any)=>String(b.id)===c.req.param('id')); return row?c.json(row):c.json({error:'Not found'},404); });
app.put('/:id', async (c:AppContext)=>{ const uid=c.get('userId'); const p=await parseBody(c,uid,true); if('error'in p) return c.json({error:p.error},400); const b=(p as any).body; await c.env.DB.prepare(`UPDATE budgets SET name=COALESCE(?,name),category_id=COALESCE(?,category_id),budget_amount=COALESCE(?,budget_amount),month=COALESCE(?,month),start_date=?,end_date=?,budget_type=?,parent_category_id=?,amount=COALESCE(?,amount),rollover_enabled=?,rollover_amount=?,alert_percent=?,status=?,notes=?,updated_at=datetime('now') WHERE id=? AND user_id=?`).bind(b.name,b.category_id,b.budget_amount,b.month,b.start_date,b.end_date,b.budget_type,b.parent_category_id,b.amount,b.rollover_enabled,b.rollover_amount,b.alert_percent,b.status,b.notes,c.req.param('id'),uid).run(); return c.json({success:true}); });
app.delete('/:id', async (c:AppContext)=>{ await c.env.DB.prepare(`UPDATE budgets SET status='archived', updated_at=datetime('now') WHERE id=? AND user_id=?`).bind(c.req.param('id'),c.get('userId')).run(); return c.json({success:true, archived:true}); });
export default app;
