import { Hono } from 'hono';
import type { AppContext, Bindings, Variables } from '../types';
import { currentMonth } from '../types';
import { alerts, categoryAnalytics, monthlyCashFlow, recurringCandidates } from '../budget-service';
import { summary as incomeSummary } from '../income-service';
const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();
app.get('/monthly', async (c:AppContext)=> c.json(await monthlyCashFlow(c.env.DB,c.get('userId'),c.req.query('month')||currentMonth())));
app.get('/categories', async (c:AppContext)=> c.json(await categoryAnalytics(c.env.DB,c.get('userId'),c.req.query('month')||currentMonth())));
app.get('/alerts', async (c:AppContext)=> c.json(await alerts(c.env.DB,c.get('userId'),c.req.query('month')||currentMonth())));
app.get('/recurring-candidates', async (c:AppContext)=> c.json(await recurringCandidates(c.env.DB,c.get('userId'))));
app.get('/expected-calendar', async (c:AppContext)=>{ const days=Number(c.req.query('days')||30); const from=new Date().toISOString().slice(0,10), to=new Date(Date.now()+Math.min(Math.max(days,1),90)*86400000).toISOString().slice(0,10); const s=await incomeSummary(c.env.DB,c.get('userId'),from,to,'base'); const next=(s as any).next_expected_credit; return c.json({date_from:from,date_to:to,items: next ? [{date:next.expected_date,item_type:'expected_income',title:next.source_name||'Income',expected_inflow:next.expected_amount,expected_outflow:0,amount:next.expected_amount,confidence:'base',linked_source:next.income_source_id,status:next.status,destination_path:'/?page=income'}] : []}); });
app.get('/trends', async (c:AppContext)=>{ const from=c.req.query('date_from')||`${new Date().getUTCFullYear()}-01`; const to=c.req.query('date_to')||currentMonth(); const months=[]; let d=new Date(Date.UTC(Number(from.slice(0,4)),Number(from.slice(5,7))-1,1)); const end=new Date(Date.UTC(Number(to.slice(0,4)),Number(to.slice(5,7))-1,1)); while(d<=end){ const m=d.toISOString().slice(0,7); months.push(await monthlyCashFlow(c.env.DB,c.get('userId'),m)); d.setUTCMonth(d.getUTCMonth()+1); } return c.json({grouping:c.req.query('grouping')||'month',results:months}); });
export default app;
