import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { currentMonth } from '../types';
import { reconstructMonth } from './networth';
import { allocateValue, ensureDefaultHousehold, listRecordOwnershipHealth, resolveOwnership } from '../ownership-service';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>();
function monthEnd(m:string){ const [y,mo]=m.split('-').map(Number); return `${m}-${String(new Date(Date.UTC(y,mo,0)).getUTCDate()).padStart(2,'0')}`; }
async function householdNetWorth(db:D1Database,u:number,month:string){ const def=await ensureDefaultHousehold(db,u), s=await reconstructMonth(db,u,month); const members=(await db.prepare('SELECT * FROM household_members WHERE user_id=? AND household_id=? ORDER BY COALESCE(sort_order,999),id').bind(u,def.household.id).all<any>()).results||[]; const by:any={}; for(const m of members) by[m.id]={member:m,member_assets:0,member_liabilities:0,member_net_worth:0,assets:[],liabilities:[]}; let joint_assets=0,joint_liabilities=0,shared=0; const unallocated:any[]=[], warnings:string[]=[];
 const assets=[...(s.accounts||[]).map((a:any)=>({record_type:a.account_type==='fixed_deposit'?'other_asset':'wealth_account', record_id:a.account_id, name:a.account_name, value:a.current_value})),{record_type:'wallet',record_id:0,name:'Wallet cash total fallback',value:0}].filter((x:any)=>x.record_id);
 for(const a of assets){ const rt=a.record_type==='wealth_account'? 'wealth_account':a.record_type; const res=await resolveOwnership(db,u,rt,a.record_id); warnings.push(...res.warnings); const av=allocateValue(Number(a.value||0),res); for(const al of av.allocations){ if(al.member_id&&by[al.member_id]){ by[al.member_id].member_assets+=al.allocated_value; by[al.member_id].assets.push({...a,allocated_value:al.allocated_value}); } else shared+=al.allocated_value; if(al.ownership_type==='joint')joint_assets+=al.allocated_value; } if(res.unallocated_percent>0)unallocated.push({record_type:rt,record_id:a.record_id,unallocated_percent:res.unallocated_percent}); }
 const liabilities=(await db.prepare('SELECT id,name,current_outstanding FROM liabilities WHERE user_id=? AND status<>\'closed\' AND include_in_net_worth=1').bind(u).all<any>()).results||[];
 for(const l of liabilities){ const res=await resolveOwnership(db,u,'liability',l.id); warnings.push(...res.warnings); const av=allocateValue(Number(l.current_outstanding||0),res); for(const al of av.allocations){ if(al.member_id&&by[al.member_id]){ by[al.member_id].member_liabilities+=al.allocated_value; by[al.member_id].liabilities.push({...l,allocated_value:al.allocated_value}); } if(al.ownership_type==='joint')joint_liabilities+=al.allocated_value; } if(res.unallocated_percent>0)unallocated.push({record_type:'liability',record_id:l.id,unallocated_percent:res.unallocated_percent}); }
 Object.values(by).forEach((m:any)=>m.member_net_worth=m.member_assets-m.member_liabilities);
 return {household:def.household, household_net_worth:s.netWorth,total_assets:s.assets,total_liabilities:s.liabilities,member_wise_net_worth:Object.values(by),joint_assets,joint_liabilities,shared_household_value:shared,unallocated_records:unallocated,excluded_records:[],ownership_warnings:[...new Set(warnings)]}; }
async function cashFlow(db:D1Database,u:number,from:string,to:string){ const def=await ensureDefaultHousehold(db,u); const mv=(await db.prepare('SELECT * FROM movements WHERE user_id=? AND date BETWEEN ? AND ? ORDER BY date,id').bind(u,from,to).all<any>()).results||[]; const members=(await db.prepare('SELECT * FROM household_members WHERE user_id=? AND household_id=?').bind(u,def.household.id).all<any>()).results||[]; const by:any={}; members.forEach((m:any)=>by[m.id]={member:m,income:0,expenses:0,savings:0,transfers:0}); let income=0,expenses=0,shared_expenses=0,transfers=0;
 for(const m of mv){ const isIncome=!m.src_kind&&m.dst_kind, isExpense=m.src_kind&&!m.dst_kind, isTransfer=m.src_kind&&m.dst_kind; if(isIncome)income+=m.amount; if(isExpense)expenses+=m.amount; if(isTransfer)transfers+=m.amount; const allocs=(await db.prepare('SELECT * FROM movement_allocations WHERE user_id=? AND movement_id=?').bind(u,m.id).all<any>()).results||[]; if(allocs.length){ for(const a of allocs){ const amt=a.allocation_amount??Math.round(m.amount*Number(a.allocation_percent||0)/100); if(a.member_id&&by[a.member_id]){ if(isIncome)by[a.member_id].income+=amt; if(isExpense)by[a.member_id].expenses+=amt; } else if(isExpense) shared_expenses+=amt; } } }
 Object.values(by).forEach((x:any)=>x.savings=x.income-x.expenses); return {household:def.household,household_income:income,household_expenses:expenses,household_savings:income-expenses,member_wise:Object.values(by),shared_expenses,transfers_within_household:transfers}; }
app.get('/household/net-worth',async c=>c.json(await householdNetWorth(c.env.DB,c.get('userId'),c.req.query('month')||currentMonth())));
app.get('/household/summary',async c=>{ const u=c.get('userId'), nw=await householdNetWorth(c.env.DB,u,c.req.query('month')||currentMonth()), cf=await cashFlow(c.env.DB,u,(c.req.query('date_from')||currentMonth()+'-01'),(c.req.query('date_to')||monthEnd(currentMonth()))); return c.json({...nw,cash_flow:cf}); });
app.get('/household/members/:id/summary',async c=>{ const nw=await householdNetWorth(c.env.DB,c.get('userId'),c.req.query('month')||currentMonth()); const m=(nw.member_wise_net_worth as any[]).find(x=>String(x.member.id)===c.req.param('id')); return m?c.json(m):c.json({error:'Not found'},404); });
app.get('/household/cash-flow',async c=>c.json(await cashFlow(c.env.DB,c.get('userId'),c.req.query('date_from')||currentMonth()+'-01',c.req.query('date_to')||monthEnd(currentMonth()))));
app.get('/household/ownership-health',async c=>c.json({records:await listRecordOwnershipHealth(c.env.DB,c.get('userId'))}));
export default app;
