import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { audit } from '../ownership-service';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>();
const rel=['self','spouse','child','parent','sibling','dependant','other'];
const today=()=>new Date().toISOString().slice(0,10);
async function deps(db:D1Database,u:number,id:any){ const checks=[['ownership',`SELECT COUNT(*) count FROM financial_record_ownership WHERE user_id=? AND member_id=?`],['allocations',`SELECT COUNT(*) count FROM movement_allocations WHERE user_id=? AND member_id=?`]]; const out:any={}; for(const [k,q] of checks){ out[k]=(await db.prepare(q).bind(u,id).first<any>())?.count||0;} return out; }
app.get('/households/:id/members',async c=>{ const rows=(await c.env.DB.prepare('SELECT * FROM household_members WHERE user_id=? AND household_id=? '+(c.req.query('include_archived')==='true'?'':'AND archived_at IS NULL')+' ORDER BY COALESCE(sort_order,999),id').bind(c.get('userId'),c.req.param('id')).all()).results; return c.json(rows); });
app.post('/households/:id/members',async c=>{ const u=c.get('userId'), h=c.req.param('id'), b=await c.req.json(); if(!b.display_name)return c.json({error:'display_name required'},400); if(!rel.includes(b.relationship))return c.json({error:'invalid relationship'},400); if(b.date_of_birth&&b.date_of_birth>today())return c.json({error:'future birth dates are rejected'},400); if(b.relationship==='self'){ const ex=await c.env.DB.prepare("SELECT id FROM household_members WHERE user_id=? AND household_id=? AND relationship='self' AND archived_at IS NULL").bind(u,h).first(); if(ex)return c.json({error:'one self member per household'},409); } const r:any=await c.env.DB.prepare('INSERT INTO household_members(user_id,household_id,display_name,relationship,date_of_birth,dependent,active,sort_order,notes,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(u,h,b.display_name,b.relationship,b.date_of_birth||null,b.dependent?1:0,b.active===false?0:1,b.sort_order??null,b.notes||null,b.metadata_json?JSON.stringify(b.metadata_json):null).run(); await audit(c.env.DB,u,Number(h),'household_member',r.meta.last_row_id,'added','Member added'); return c.json(await c.env.DB.prepare('SELECT * FROM household_members WHERE user_id=? AND id=?').bind(u,r.meta.last_row_id).first(),201); });
app.get('/household-members/:id',async c=>{ const r=await c.env.DB.prepare('SELECT * FROM household_members WHERE user_id=? AND id=?').bind(c.get('userId'),c.req.param('id')).first(); return r?c.json(r):c.json({error:'Not found'},404); });
app.put('/household-members/:id',async c=>{ const u=c.get('userId'), id=c.req.param('id'), b=await c.req.json(); if(b.relationship&&!rel.includes(b.relationship))return c.json({error:'invalid relationship'},400); if(b.date_of_birth&&b.date_of_birth>today())return c.json({error:'future birth dates are rejected'},400); await c.env.DB.prepare('UPDATE household_members SET display_name=COALESCE(?,display_name),relationship=COALESCE(?,relationship),date_of_birth=?,dependent=COALESCE(?,dependent),active=COALESCE(?,active),sort_order=?,notes=?,metadata_json=?,updated_at=datetime(\'now\') WHERE user_id=? AND id=?').bind(b.display_name??null,b.relationship??null,b.date_of_birth??null,b.dependent==null?null:(b.dependent?1:0),b.active==null?null:(b.active?1:0),b.sort_order??null,b.notes??null,b.metadata_json?JSON.stringify(b.metadata_json):null,u,id).run(); await audit(c.env.DB,u,null,'household_member',Number(id),'edited','Member edited'); return c.json(await c.env.DB.prepare('SELECT * FROM household_members WHERE user_id=? AND id=?').bind(u,id).first()); });
app.delete('/household-members/:id',async c=>{ const u=c.get('userId'), id=c.req.param('id'), d=await deps(c.env.DB,u,id); const linked=Object.values(d).some((n:any)=>n>0); if(linked||c.req.query('archive')==='true'){ await c.env.DB.prepare("UPDATE household_members SET active=0, archived_at=COALESCE(archived_at,datetime('now')), updated_at=datetime('now') WHERE user_id=? AND id=?").bind(u,id).run(); await audit(c.env.DB,u,null,'household_member',Number(id),'archived','Member archived'); return c.json({archived:true,dependencies:d}); } await c.env.DB.prepare('DELETE FROM household_members WHERE user_id=? AND id=?').bind(u,id).run(); return c.json({deleted:true,dependencies:d}); });
export default app;
