import { Hono } from 'hono';
import type { Bindings, Variables, AppContext } from '../types';
import { DEFAULT_TEMPLATES, IMPORT_TYPES, STATEMENT_LIMITS, financialFingerprint, normalize, parseStatementCsv, safeRaw, sanitizeFilename, sha256Hex, suggest, validateNormalized } from '../imports/statement';

const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();
const bad=(c:AppContext,msg:string,code=400)=>c.json({error:msg},code as any);
async function audit(c:AppContext,uid:number,batch_id:number|null,event_type:string,summary:any={}){ await c.env.DB.prepare('INSERT INTO financial_import_audit_events (user_id,batch_id,event_type,summary_json) VALUES (?,?,?,?)').bind(uid,batch_id,event_type,JSON.stringify(summary)).run(); }
async function batch(c:AppContext,uid:number,id:any){ return c.env.DB.prepare('SELECT * FROM financial_import_batches WHERE user_id=? AND id=?').bind(uid,id).first<any>(); }
function mimeOk(file:File){ return /csv|text|excel|octet-stream/.test(file.type||'text/csv') || /\.csv$/i.test(file.name); }
async function walletExists(c:AppContext,uid:number,id:any){ if(!id)return null; return c.env.DB.prepare('SELECT id,name FROM wallets WHERE user_id=? AND id=?').bind(uid,id).first<any>(); }
async function categoryExists(c:AppContext,uid:number,id:any){ if(!id)return null; return c.env.DB.prepare('SELECT id,name,type FROM categories WHERE user_id=? AND id=?').bind(uid,id).first<any>(); }
async function matchMovement(c:AppContext,uid:number,n:any,walletId?:any){ const start=n.normalized_date, amount=n.normalized_amount; if(!start||!amount)return null; const rows=(await c.env.DB.prepare(`SELECT m.*, p.id pennywise_id FROM movements m LEFT JOIN pennywise_sync_records p ON p.user_id=m.user_id AND p.movement_id=m.id WHERE m.user_id=? AND COALESCE(m.status,'active')='active' AND m.amount=? AND date(m.date) BETWEEN date(?, '-3 day') AND date(?, '+3 day') ORDER BY ABS(julianday(m.date)-julianday(?)), m.id LIMIT 10`).bind(uid,amount,start,start,start).all<any>()).results; if(!rows.length)return null; const exact=rows.find(r=>r.date===start && (n.normalized_reference && String(r.description||'').includes(n.normalized_reference))); const r=exact||rows[0]; let confidence:any=exact?'exact':(r.date===start?'high':'medium'); if(walletId && !([r.src_kind+':'+r.src_id,r.dst_kind+':'+r.dst_id].includes('wallet:'+walletId))) confidence='low'; return {record_type:r.pennywise_id?'pennywise_movement':'movement',record_id:r.id,confidence}; }
async function duplicateStatus(c:AppContext,uid:number,batchId:number,rowNumber:number,n:any,walletId?:any){ const same=await c.env.DB.prepare(`SELECT r.id FROM financial_import_rows r JOIN financial_import_batches b ON b.id=r.batch_id WHERE r.user_id=? AND b.id<>? AND b.status IN ('committed','partially_committed') AND b.file_hash=(SELECT file_hash FROM financial_import_batches WHERE id=?) AND r.row_number=? LIMIT 1`).bind(uid,batchId,batchId,rowNumber).first<any>(); if(same)return 'exact_duplicate'; if(n.normalized_reference){ const ref=await c.env.DB.prepare(`SELECT id FROM financial_import_rows WHERE user_id=? AND batch_id<>? AND normalized_reference=? AND created_record_id IS NOT NULL LIMIT 1`).bind(uid,batchId,n.normalized_reference).first<any>(); if(ref)return 'exact_duplicate'; }
 const m=await matchMovement(c,uid,n,walletId); if(m?.confidence==='exact'||m?.confidence==='high') return 'matched_existing'; if(m?.confidence==='medium') return 'probable_duplicate'; if(m?.confidence==='low') return 'possible_duplicate'; return 'new'; }
function movementFor(n:any, opts:any){ const walletId=opts.wallet_id, categoryId=opts.category_id; if(!walletId) throw new Error('wallet_id required for Ledger imports'); if(n.normalized_type==='transfer' && opts.destination_wallet_id) return {date:n.normalized_date,amount:n.normalized_amount,description:n.normalized_description,category_id:null,src_kind:'wallet',src_id:walletId,dst_kind:'wallet',dst_id:opts.destination_wallet_id}; if(n.normalized_direction==='credit') return {date:n.normalized_date,amount:n.normalized_amount,description:n.normalized_description,category_id:categoryId||null,src_kind:null,src_id:null,dst_kind:'wallet',dst_id:walletId}; return {date:n.normalized_date,amount:n.normalized_amount,description:n.normalized_description,category_id:categoryId||null,src_kind:'wallet',src_id:walletId,dst_kind:null,dst_id:null}; }
async function reconciliation(c:AppContext,uid:number,id:number){ const bt=await batch(c,uid,id); if(!bt)return null; const rows=(await c.env.DB.prepare('SELECT * FROM financial_import_rows WHERE user_id=? AND batch_id=?').bind(uid,id).all<any>()).results; const debits=rows.filter(r=>r.validation_status==='valid'&&r.duplicate_status==='new'&&r.normalized_direction==='debit').reduce((s,r)=>s+(r.normalized_amount||0),0); const credits=rows.filter(r=>r.validation_status==='valid'&&r.duplicate_status==='new'&&r.normalized_direction==='credit').reduce((s,r)=>s+(r.normalized_amount||0),0); const meta=JSON.parse(bt.metadata_json||'{}'), opening=meta.opening_balance??null, closing=meta.closing_balance??null; const calc=opening==null?null:opening+credits-debits; const diff=calc==null||closing==null?null:calc-closing; const tol=meta.rounding_tolerance??1; return {statement_opening_balance:opening,statement_closing_balance:closing,imported_debits:debits,imported_credits:credits,calculated_closing_balance:calc,difference:diff,matched_rows:rows.filter(r=>r.match_status!=='unmatched').length,unmatched_rows:rows.filter(r=>r.match_status==='unmatched').length,duplicate_rows:rows.filter(r=>r.duplicate_status!=='new').length,excluded_rows:rows.filter(r=>r.resolution==='skip'||r.validation_status!=='valid').length,reconciliation_status:calc==null||closing==null?'insufficient_data':Math.abs(diff)<=tol?'reconciled':Math.abs(diff)<=100?'small_difference':'unreconciled'}; }

app.get('/templates/defaults', c=>c.json({templates:DEFAULT_TEMPLATES}));
app.post('/upload', async c=>{ const uid=c.get('userId'); const form=await c.req.formData(); const file=form.get('file') as File|null; if(!file)return bad(c,'file required'); if(!mimeOk(file))return bad(c,'Only CSV uploads are supported in Phase 15'); if(file.size>STATEMENT_LIMITS.maxFileSize)return bad(c,'File exceeds 5 MB limit'); const bytes=new Uint8Array(await file.arrayBuffer()); const file_hash=await sha256Hex(bytes); const dup=await c.env.DB.prepare("SELECT id,status FROM financial_import_batches WHERE user_id=? AND file_hash=? AND status<>'rolled_back'").bind(uid,file_hash).first<any>(); if(dup)return bad(c,'Duplicate file already uploaded',409); let parsed; try{ parsed=parseStatementCsv(bytes); }catch(e:any){return bad(c,e.message);} const s=suggest(parsed.headers); const import_type=String(form.get('import_type')||s.import_type); if(!IMPORT_TYPES.includes(import_type))return bad(c,'Invalid import_type'); const meta={headers:parsed.headers,suggested_mapping:s.column_mapping,sample_rows:parsed.rows.slice(0,5).map(r=>safeRaw(r.raw)),safe_rows:parsed.rows.map(r=>safeRaw(r.raw)),parse_errors:parsed.errors,opening_balance:null,closing_balance:null}; const res=await c.env.DB.prepare(`INSERT INTO financial_import_batches (user_id,import_type,source_institution,source_filename,file_hash,status,row_count,metadata_json) VALUES (?,?,?,?,?,?,?,?)`).bind(uid,import_type,String(form.get('source_institution')||''),sanitizeFilename(file.name),file_hash,parsed.errors.length?'needs_mapping':'uploaded',parsed.rows.length,JSON.stringify(meta)).run(); await audit(c,uid,res.meta.last_row_id as number,'file_uploaded',{filename:sanitizeFilename(file.name),rows:parsed.rows.length}); return c.json({batch_id:res.meta.last_row_id,import_type,suggested_import_type:s.import_type,detected_headers:parsed.headers,suggested_mapping:s.column_mapping,sample_rows:meta.sample_rows,parse_errors:parsed.errors,status:parsed.errors.length?'needs_mapping':'uploaded'}); });
app.post('/:id/mapping', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')), bt=await batch(c,uid,id); if(!bt)return bad(c,'Not found',404); const body=await c.req.json(); const meta={...(JSON.parse(bt.metadata_json||'{}')),mapping:body.column_mapping,date_format:body.date_format,amount_convention:body.amount_convention,wallet_id:body.wallet_id,category_id:body.category_id,opening_balance:body.opening_balance??null,closing_balance:body.closing_balance??null,rounding_tolerance:body.rounding_tolerance??1}; if(body.save_template){ await c.env.DB.prepare(`INSERT INTO financial_import_templates (user_id,name,institution,import_type,column_mapping_json,date_format,amount_convention,header_row,rows_to_skip,account_mapping_json,wallet_category_defaults_json,active) VALUES (?,?,?,?,?,?,?,?,?,?,?,1)`).bind(uid,body.template_name||'Custom template',bt.source_institution,bt.import_type,JSON.stringify(body.column_mapping),body.date_format,body.amount_convention,body.header_row||1,body.rows_to_skip||0,JSON.stringify({wallet_id:body.wallet_id}),JSON.stringify({category_id:body.category_id})).run(); }
 await c.env.DB.prepare(`UPDATE financial_import_batches SET status='previewed', metadata_json=? WHERE user_id=? AND id=?`).bind(JSON.stringify(meta),uid,id).run(); await audit(c,uid,id,'mapping_changed',{fields:Object.keys(body.column_mapping||{})}); return c.json({success:true,status:'previewed'}); });
app.post('/:id/preview', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')), bt=await batch(c,uid,id); if(!bt)return bad(c,'Not found',404); return c.json(await buildPreview(c,uid,bt,false)); });
app.post('/:id/validate', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')), bt=await batch(c,uid,id); if(!bt)return bad(c,'Not found',404); return c.json(await buildPreview(c,uid,bt,true)); });
async function buildPreview(c:AppContext,uid:number,bt:any,persist:boolean){ const meta=JSON.parse(bt.metadata_json||'{}'); const rows=(meta.safe_rows||meta.sample_rows||[]); if(!meta.mapping) throw new Error('Mapping required'); await c.env.DB.prepare('DELETE FROM financial_import_rows WHERE user_id=? AND batch_id=? AND created_record_id IS NULL').bind(uid,bt.id).run(); let valid=0, errors=0, dups=0, matched=0; const out:any[]=[]; for(let i=0;i<rows.length;i++){ const n=normalize(rows[i],meta.mapping,meta); const err=validateNormalized(n); const match=err?null:await matchMovement(c,uid,n,meta.wallet_id); const dup=err?'conflict':await duplicateStatus(c,uid,bt.id,i+2,n,meta.wallet_id); const validation_status=err?'invalid':'valid'; if(err)errors++; else valid++; if(dup!=='new')dups++; if(match&&match.confidence!=='low')matched++; const rec={row_number:i+2,...n,validation_status,duplicate_status:dup,match_status:match?.confidence||'unmatched',matched_record_type:match?.record_type||null,matched_record_id:match?.record_id||null,error_message:err}; out.push(rec); await c.env.DB.prepare(`INSERT INTO financial_import_rows (user_id,batch_id,row_number,raw_row_json,normalized_type,normalized_date,normalized_amount,normalized_direction,normalized_description,normalized_reference,normalized_account,normalized_category,normalized_balance,validation_status,duplicate_status,match_status,matched_record_type,matched_record_id,error_code,error_message) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid,bt.id,rec.row_number,JSON.stringify(rows[i]),n.normalized_type,n.normalized_date,n.normalized_amount,n.normalized_direction,n.normalized_description,n.normalized_reference,n.normalized_account,n.normalized_category,n.normalized_balance,validation_status,dup,rec.match_status,rec.matched_record_type,rec.matched_record_id,err?'validation_error':null,err).run(); }
 const status=errors?'validated':'ready'; await c.env.DB.prepare('UPDATE financial_import_batches SET status=?,valid_count=?,duplicate_count=?,matched_count=?,error_count=? WHERE id=?').bind(status,valid,dups,matched,errors,bt.id).run(); await audit(c,uid,bt.id,persist?'rows_validated':'preview_generated',{valid,errors,dups,matched}); return {batch_id:bt.id,status,row_count:out.length,valid_count:valid,duplicate_count:dups,matched_count:matched,error_count:errors,rows:out,reconciliation:await reconciliation(c,uid,bt.id)}; }
app.post('/:id/commit', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')), bt=await batch(c,uid,id); if(!bt)return bad(c,'Not found',404); if(['committed','partially_committed'].includes(bt.status))return bad(c,'Batch already committed'); const body=await c.req.json().catch(()=>({})); const meta=JSON.parse(bt.metadata_json||'{}'); if(!await walletExists(c,uid,meta.wallet_id))return bad(c,'Mapped wallet not found'); if(meta.category_id && !await categoryExists(c,uid,meta.category_id))return bad(c,'Mapped category not found'); const rows=(await c.env.DB.prepare(`SELECT * FROM financial_import_rows WHERE user_id=? AND batch_id=? ORDER BY row_number`).bind(uid,id).all<any>()).results; if(rows.some(r=>r.validation_status!=='valid')&&!body.allow_partial)return bad(c,'Partial commit requires confirmation'); let committed=0, skipped=0, failed=0; for(const r of rows){ if(r.created_record_id){skipped++; continue;} if(['exact_duplicate','probable_duplicate','possible_duplicate','matched_existing'].includes(r.duplicate_status) && r.resolution!=='import_as_new'){ await c.env.DB.prepare("UPDATE financial_import_rows SET resolution='skip', updated_at=datetime('now') WHERE id=?").bind(r.id).run(); skipped++; continue; } if(r.validation_status!=='valid'){skipped++; continue;} try{ let created:any=null; if(['bank_statement','credit_card_statement','generic_ledger'].includes(bt.import_type)){ const mv=movementFor(r,meta); const res=await c.env.DB.prepare(`INSERT INTO movements (user_id,date,amount,description,category_id,src_kind,src_id,dst_kind,dst_id) VALUES (?,?,?,?,?,?,?,?,?)`).bind(uid,mv.date,mv.amount,mv.description,mv.category_id,mv.src_kind,mv.src_id,mv.dst_kind,mv.dst_id).run(); created={type:'movement',id:res.meta.last_row_id}; }
 else if(['loan_statement','generic_liability'].includes(bt.import_type) && body.liability_id){ const res=await c.env.DB.prepare(`INSERT INTO liability_payments (user_id,liability_id,payment_date,payment_amount,principal_component,interest_component,fee_component,payment_type,source,notes) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(uid,body.liability_id,r.normalized_date,r.normalized_amount,null,null,null,'emi','statement_import',r.normalized_description).run(); created={type:'liability_payment',id:res.meta.last_row_id}; }
 else { skipped++; await c.env.DB.prepare("UPDATE financial_import_rows SET resolution='skip', updated_at=datetime('now') WHERE id=?").bind(r.id).run(); continue; }
 await c.env.DB.prepare("UPDATE financial_import_rows SET resolution='import_as_new', created_record_type=?, created_record_id=?, updated_at=datetime('now') WHERE id=?").bind(created.type,created.id,r.id).run(); committed++; }catch(e:any){ failed++; await c.env.DB.prepare("UPDATE financial_import_rows SET validation_status='invalid', error_code='commit_error', error_message=?, updated_at=datetime('now') WHERE id=?").bind(e.message,r.id).run(); } }
 const status=failed?'partially_committed':'committed'; await c.env.DB.prepare("UPDATE financial_import_batches SET status=?,committed_count=?,skipped_count=?,error_count=?,committed_at=COALESCE(committed_at,datetime('now')) WHERE id=?").bind(status,committed,skipped,failed,id).run(); await audit(c,uid,id,'commit_performed',{committed,skipped,failed}); return c.json({status,committed_count:committed,skipped_count:skipped,error_count:failed,reconciliation:await reconciliation(c,uid,id)}); });
app.post('/:id/rollback', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')), bt=await batch(c,uid,id); if(!bt)return bad(c,'Not found',404); const locked=await c.env.DB.prepare("SELECT id,status,locked FROM account_reconciliations WHERE user_id=? AND import_batch_id=? AND locked=1 LIMIT 5").bind(uid,id).all<any>(); if(locked.results.length)return c.json({error:'Rollback blocked by locked reconciliation',dependency_report:locked.results},409); if(!['committed','partially_committed'].includes(bt.status))return bad(c,'Batch cannot be rolled back'); const rows=(await c.env.DB.prepare('SELECT * FROM financial_import_rows WHERE user_id=? AND batch_id=? AND created_record_id IS NOT NULL').bind(uid,id).all<any>()).results; const deps:any[]=[]; let deleted=0; for(const r of rows){ if(r.created_record_type==='movement'){ const used=await c.env.DB.prepare('SELECT id FROM pennywise_sync_records WHERE user_id=? AND movement_id=? LIMIT 1').bind(uid,r.created_record_id).first<any>(); if(used){deps.push({row_number:r.row_number,record_type:r.created_record_type,record_id:r.created_record_id,reason:'linked PennyWise record'}); continue;} await c.env.DB.prepare('DELETE FROM movements WHERE user_id=? AND id=?').bind(uid,r.created_record_id).run(); deleted++; }
 else if(r.created_record_type==='liability_payment'){ await c.env.DB.prepare("DELETE FROM liability_payments WHERE user_id=? AND id=? AND source='statement_import'").bind(uid,r.created_record_id).run(); deleted++; } }
 if(deps.length)return c.json({error:'Rollback blocked by dependencies',dependency_report:deps},409); await c.env.DB.prepare("UPDATE financial_import_rows SET resolution='rolled_back', created_record_id=NULL, created_record_type=NULL, updated_at=datetime('now') WHERE user_id=? AND batch_id=?").bind(uid,id).run(); await c.env.DB.prepare("DELETE FROM account_balance_snapshots WHERE user_id=? AND import_batch_id=? AND source IN ('import','statement')").bind(uid,id).run(); await c.env.DB.prepare("UPDATE account_reconciliation_rows SET movement_id=NULL, match_status='unmatched', resolution='unresolved', updated_at=datetime('now') WHERE user_id=? AND import_row_id IN (SELECT id FROM financial_import_rows WHERE user_id=? AND batch_id=?)").bind(uid,uid,id).run(); await c.env.DB.prepare("UPDATE financial_import_batches SET status='rolled_back',rolled_back_at=datetime('now') WHERE user_id=? AND id=?").bind(uid,id).run(); await audit(c,uid,id,'rollback_performed',{deleted}); return c.json({status:'rolled_back',deleted_records:deleted,preserved_matched_records:true}); });
app.get('/', async c=>{ const uid=c.get('userId'); const rows=(await c.env.DB.prepare('SELECT id,import_type,source_institution,source_filename,substr(file_hash,1,12) file_hash_prefix,statement_period_start,statement_period_end,status,row_count,valid_count,duplicate_count,matched_count,committed_count,skipped_count,error_count,created_at,committed_at,rolled_back_at FROM financial_import_batches WHERE user_id=? ORDER BY created_at DESC,id DESC').bind(uid).all()).results; return c.json({batches:rows}); });
app.get('/:id', async c=>{ const uid=c.get('userId'), bt=await batch(c,uid,c.req.param('id')); if(!bt)return bad(c,'Not found',404); return c.json({batch:{...bt,file_hash:undefined,file_hash_prefix:bt.file_hash.slice(0,12),metadata:JSON.parse(bt.metadata_json||'{}')}}); });
app.get('/:id/rows', async c=>{ const uid=c.get('userId'); const rows=(await c.env.DB.prepare('SELECT * FROM financial_import_rows WHERE user_id=? AND batch_id=? ORDER BY row_number').bind(uid,c.req.param('id')).all()).results; return c.json({rows}); });
app.get('/:id/reconciliation', async c=>{ const r=await reconciliation(c,c.get('userId'),Number(c.req.param('id'))); if(!r)return bad(c,'Not found',404); return c.json(r); });
export default app;
