import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { DEFAULT_TEMPLATES } from '../imports/statement';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>();
app.get('/', async c=>{ const uid=c.get('userId'); const rows=(await c.env.DB.prepare('SELECT * FROM financial_import_templates WHERE user_id=? ORDER BY active DESC,name').bind(uid).all()).results; return c.json({templates:[...DEFAULT_TEMPLATES.map((t,i)=>({id:`default-${i+1}`,...t,system:true})),...rows.map((r:any)=>({...r,column_mapping:JSON.parse(r.column_mapping_json||'{}'),account_mapping:JSON.parse(r.account_mapping_json||'{}'),wallet_category_defaults:JSON.parse(r.wallet_category_defaults_json||'{}')}))]}); });
app.post('/', async c=>{ const uid=c.get('userId'), b=await c.req.json(); const r=await c.env.DB.prepare(`INSERT INTO financial_import_templates (user_id,name,institution,import_type,column_mapping_json,date_format,amount_convention,header_row,rows_to_skip,account_mapping_json,wallet_category_defaults_json,active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid,b.name,b.institution||null,b.import_type,JSON.stringify(b.column_mapping||{}),b.date_format||null,b.amount_convention||null,b.header_row||1,b.rows_to_skip||0,JSON.stringify(b.account_mapping||{}),JSON.stringify(b.wallet_category_defaults||{}),b.active===false?0:1).run(); return c.json({id:r.meta.last_row_id,...b},201); });
app.put('/:id', async c=>{ const uid=c.get('userId'), b=await c.req.json(); await c.env.DB.prepare(`UPDATE financial_import_templates SET name=?,institution=?,import_type=?,column_mapping_json=?,date_format=?,amount_convention=?,header_row=?,rows_to_skip=?,account_mapping_json=?,wallet_category_defaults_json=?,active=?,updated_at=datetime('now') WHERE user_id=? AND id=?`).bind(b.name,b.institution||null,b.import_type,JSON.stringify(b.column_mapping||{}),b.date_format||null,b.amount_convention||null,b.header_row||1,b.rows_to_skip||0,JSON.stringify(b.account_mapping||{}),JSON.stringify(b.wallet_category_defaults||{}),b.active===false?0:1,uid,c.req.param('id')).run(); return c.json({success:true}); });
app.delete('/:id', async c=>{ await c.env.DB.prepare('UPDATE financial_import_templates SET active=0,updated_at=datetime(\'now\') WHERE user_id=? AND id=?').bind(c.get('userId'),c.req.param('id')).run(); return c.json({success:true}); });
export default app;
