import { Hono } from 'hono';
import type { Bindings, Variables, AppContext } from '../types';
import { int } from '../wealth/liabilities';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>();
const PT=['emi','part_payment','prepayment','interest_only','fee','penalty','refund','adjustment','settlement']; const SRC=['manual','linked_movement','import','generated_schedule','migration'];
async function ownedLiability(db:D1Database,uid:number,id:any){return db.prepare('SELECT id FROM liabilities WHERE user_id=? AND id=?').bind(uid,id).first<any>();}
async function pay(c:AppContext,id:any){return c.env.DB.prepare('SELECT * FROM liability_payments WHERE user_id=? AND id=?').bind(c.get('userId'),id).first<any>();}
async function validate(c:AppContext,b:any, self=0){ if(!await ownedLiability(c.env.DB,c.get('userId'),b.liability_id))return 'Liability not found'; if(!PT.includes(b.payment_type)||!SRC.includes(b.source))return 'Invalid payment type/source'; if(b.movement_id){ const m=await c.env.DB.prepare('SELECT id,amount,date FROM movements WHERE user_id=? AND id=?').bind(c.get('userId'),b.movement_id).first<any>(); if(!m)return 'Movement not found for user'; const used=await c.env.DB.prepare('SELECT id FROM liability_payments WHERE user_id=? AND movement_id=? AND id<>?').bind(c.get('userId'),b.movement_id,self).first<any>(); if(used)return 'Movement already linked'; } return null; }
function body(b:any){return {liability_id:b.liability_id,payment_date:b.payment_date,payment_amount:int(b.payment_amount),principal_component:b.principal_component==null?null:int(b.principal_component),interest_component:b.interest_component==null?null:int(b.interest_component),fee_component:b.fee_component==null?null:int(b.fee_component),tax_component:b.tax_component==null?null:int(b.tax_component),outstanding_after:b.outstanding_after==null?null:int(b.outstanding_after),payment_type:b.payment_type||'emi',movement_id:b.movement_id??null,source:b.source||(b.movement_id?'linked_movement':'manual'),notes:b.notes??null};}
app.put('/:id',async c=>{ const ex=await pay(c,c.req.param('id')); if(!ex)return c.json({error:'Not found'},404); const p=body(await c.req.json()); const e=await validate(c,p,Number(c.req.param('id'))); if(e)return c.json({error:e},400); await c.env.DB.prepare(`UPDATE liability_payments SET liability_id=?,payment_date=?,payment_amount=?,principal_component=?,interest_component=?,fee_component=?,tax_component=?,outstanding_after=?,payment_type=?,movement_id=?,source=?,notes=?,updated_at=datetime('now') WHERE user_id=? AND id=?`).bind(...Object.values(p),c.get('userId'),c.req.param('id')).run(); return c.json({id:Number(c.req.param('id')),...p});});
app.delete('/:id',async c=>{ if(!await pay(c,c.req.param('id')))return c.json({error:'Not found'},404); await c.env.DB.prepare('DELETE FROM liability_payments WHERE user_id=? AND id=?').bind(c.get('userId'),c.req.param('id')).run(); return c.json({success:true}); });
export default app;
