import { Hono } from 'hono';
import type { Bindings, Variables, AppContext } from '../types';
import { LIABILITY_TYPES, INTEREST_TYPES, STATUSES, MODES, calculateLiability, liabilityTotals, schedule, dueStatus, expectedEmi, int } from '../wealth/liabilities';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>();
const PAYMENT_TYPES=['emi','part_payment','prepayment','interest_only','fee','penalty','refund','adjustment','settlement'];
const SOURCES=['manual','linked_movement','import','generated_schedule','migration'];
function bad(c:AppContext,m:string){return c.json({error:m},400)}
function pick(b:any){ return { name:String(b.name||'').trim(), liability_type:b.liability_type, institution:b.institution??null, account_number_masked:b.account_number_masked??null, currency:b.currency||'IDR', original_principal:int(b.original_principal), current_outstanding:int(b.current_outstanding), interest_rate:Number.isFinite(Number(b.interest_rate))?Number(b.interest_rate):0, interest_type:b.interest_type||'manual', emi_amount:int(b.emi_amount), repayment_frequency:b.repayment_frequency||'monthly', start_date:b.start_date??null, maturity_date:b.maturity_date??null, next_due_date:b.next_due_date??b.due_date??null, payment_day:b.payment_day??null, status:b.status||'active', include_in_net_worth:b.include_in_net_worth===false?0:1, auto_calculation_mode:b.auto_calculation_mode||(b.liability_type==='credit_card'?'manual':'hybrid'), linked_wallet_id:b.linked_wallet_id??null, linked_category_id:b.linked_category_id??null, credit_limit:int(b.credit_limit), statement_balance:b.statement_balance==null?null:int(b.statement_balance), available_credit:b.available_credit==null?null:int(b.available_credit), statement_date:b.statement_date??null, due_date:b.due_date??b.next_due_date??null, minimum_due:b.minimum_due==null?null:int(b.minimum_due), full_payment_amount:b.full_payment_amount==null?null:int(b.full_payment_amount), notes:b.notes??null, metadata_json:b.metadata_json?JSON.stringify(typeof b.metadata_json==='string'?JSON.parse(b.metadata_json):b.metadata_json):null }; }
function validate(l:any){ if(!l.name)return 'Name required'; if(!LIABILITY_TYPES.includes(l.liability_type))return 'Invalid liability_type'; if(!INTEREST_TYPES.includes(l.interest_type))return 'Invalid interest_type'; if(!STATUSES.includes(l.status))return 'Invalid status'; if(!MODES.includes(l.auto_calculation_mode))return 'Invalid auto_calculation_mode'; if(!Number.isFinite(l.interest_rate))return 'Invalid interest_rate'; return null; }
async function getOwned(db:D1Database,uid:number,id:any){return db.prepare('SELECT * FROM liabilities WHERE user_id=? AND id=?').bind(uid,id).first<any>();}
async function enrich(db:D1Database,uid:number,l:any){ const v=await calculateLiability(db,uid,l); const util=l.liability_type==='credit_card'&&l.credit_limit? v.outstanding/l.credit_limit*100:null; return {...l,current_outstanding:v.outstanding,valuation:v,utilization_percentage:util,amount_due:l.full_payment_amount??l.statement_balance??v.outstanding,due_status:dueStatus(l.due_date||l.next_due_date)}; }
app.get('/summary', async c=>{ const uid=c.get('userId'); const lt=await liabilityTotals(c.env.DB,uid,c.req.query('as_of')||undefined); let monthly=0, original=0, principal=0, interest=0, fees=0, overdue=0; let highest:any=null, hiRate:any=null, earliest:any=null; for(const l of lt.items){ monthly+=int(l.emi_amount); original+=int(l.original_principal); principal+=l.valuation.principal_repaid; interest+=l.valuation.interest_paid; fees+=l.valuation.fees_paid; if(dueStatus(l.due_date||l.next_due_date)==='overdue') overdue+=int(l.emi_amount||l.minimum_due||l.valuation.outstanding); if(!highest||l.valuation.outstanding>highest.current_outstanding) highest={id:l.id,name:l.name,current_outstanding:l.valuation.outstanding}; if(!hiRate||Number(l.interest_rate)>Number(hiRate.interest_rate)) hiRate={id:l.id,name:l.name,interest_rate:l.interest_rate}; if(l.maturity_date&&(!earliest||l.maturity_date<earliest.maturity_date)) earliest={id:l.id,name:l.name,maturity_date:l.maturity_date}; }
 const cc=lt.items.filter(l=>l.liability_type==='credit_card'&&l.credit_limit).map(l=>l.valuation.outstanding/l.credit_limit*100); return c.json({ total_outstanding:lt.total, original_principal:original, principal_repaid:principal, interest_paid:interest, fees_paid:fees, monthly_emi_commitment:monthly, next_30_day_payments:lt.items.filter(l=>l.next_due_date && l.next_due_date<=new Date(Date.now()+30*864e5).toISOString().slice(0,10)).length, overdue_amount:overdue, active_liability_count:lt.items.length, credit_card_utilization:cc.length?cc.reduce((s,x)=>s+x,0)/cc.length:null, highest_interest_liability:hiRate, earliest_maturity:earliest, debt_to_assets_ratio:null, debt_to_income_ratio:null, payoff_progress_percentage:original?principal/original*100:null, highest_outstanding_liability:highest, breakdown:lt.breakdown }); });
app.get('/', async c=>{ const uid=c.get('userId'); const wh=['user_id=?'], b:any[]=[uid]; for(const [q,col] of [['type','liability_type'],['status','status'],['institution','institution']] as any){ const v=c.req.query(q); if(v){wh.push(`${col}=?`); b.push(v);} } if(c.req.query('include_in_net_worth')!=null){wh.push('include_in_net_worth=?'); b.push(c.req.query('include_in_net_worth')==='true'?1:0);} if(c.req.query('due_before')){wh.push('(next_due_date<=? OR due_date<=?)'); b.push(c.req.query('due_before'),c.req.query('due_before'));} let rows=(await c.env.DB.prepare(`SELECT * FROM liabilities WHERE ${wh.join(' AND ')} ORDER BY status,name`).bind(...b).all<any>()).results; rows=await Promise.all(rows.map(l=>enrich(c.env.DB,uid,l))); if(c.req.query('overdue')==='true') rows=rows.filter(l=>l.due_status==='overdue'); return c.json({liabilities:rows}); });
app.post('/', async c=>{ const uid=c.get('userId'), l=pick(await c.req.json()); const err=validate(l); if(err)return bad(c,err); const r=await c.env.DB.prepare(`INSERT INTO liabilities (user_id,name,liability_type,institution,account_number_masked,currency,original_principal,current_outstanding,interest_rate,interest_type,emi_amount,repayment_frequency,start_date,maturity_date,next_due_date,payment_day,status,include_in_net_worth,auto_calculation_mode,linked_wallet_id,linked_category_id,credit_limit,statement_balance,available_credit,statement_date,due_date,minimum_due,full_payment_amount,notes,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid,...Object.values(l)).run(); return c.json(await enrich(c.env.DB,uid,{id:r.meta.last_row_id,...l}),201); });
app.get('/:id', async c=>{ const l=await getOwned(c.env.DB,c.get('userId'),c.req.param('id')); return l?c.json(await enrich(c.env.DB,c.get('userId'),l)):c.json({error:'Not found'},404); });
app.put('/:id', async c=>{ const uid=c.get('userId'); if(!await getOwned(c.env.DB,uid,c.req.param('id')))return c.json({error:'Not found'},404); const l=pick(await c.req.json()); const err=validate(l); if(err)return bad(c,err); await c.env.DB.prepare(`UPDATE liabilities SET name=?,liability_type=?,institution=?,account_number_masked=?,currency=?,original_principal=?,current_outstanding=?,interest_rate=?,interest_type=?,emi_amount=?,repayment_frequency=?,start_date=?,maturity_date=?,next_due_date=?,payment_day=?,status=?,include_in_net_worth=?,auto_calculation_mode=?,linked_wallet_id=?,linked_category_id=?,credit_limit=?,statement_balance=?,available_credit=?,statement_date=?,due_date=?,minimum_due=?,full_payment_amount=?,notes=?,metadata_json=?,updated_at=datetime('now'),closed_at=CASE WHEN ? IN ('closed','settled','written_off') THEN COALESCE(closed_at,datetime('now')) ELSE closed_at END WHERE user_id=? AND id=?`).bind(...Object.values(l),l.status,uid,c.req.param('id')).run(); return c.json(await enrich(c.env.DB,uid,{id:Number(c.req.param('id')),...l})); });
app.delete('/:id', async c=>{ const uid=c.get('userId'), id=c.req.param('id'); const deps:any={payments:(await c.env.DB.prepare('SELECT COUNT(*) c FROM liability_payments WHERE user_id=? AND liability_id=?').bind(uid,id).first<any>()).c,snapshots:(await c.env.DB.prepare('SELECT COUNT(*) c FROM liability_balance_snapshots WHERE user_id=? AND liability_id=?').bind(uid,id).first<any>()).c,linked_movements:(await c.env.DB.prepare('SELECT COUNT(*) c FROM liability_payments WHERE user_id=? AND liability_id=? AND movement_id IS NOT NULL').bind(uid,id).first<any>()).c,net_worth_snapshot_dependencies:(await c.env.DB.prepare("SELECT COUNT(*) c FROM net_worth_snapshots WHERE user_id=? AND breakdown_json LIKE '%' || ? || '%'").bind(uid,`liability`).first<any>()).c,import_references:0}; if(Object.values(deps).some((x:any)=>x>0)){ await c.env.DB.prepare("UPDATE liabilities SET status='inactive',updated_at=datetime('now') WHERE user_id=? AND id=?").bind(uid,id).run(); return c.json({soft_deactivated:true,dependency_report:deps},409);} await c.env.DB.prepare('DELETE FROM liabilities WHERE user_id=? AND id=?').bind(uid,id).run(); return c.json({success:true}); });
async function paymentBody(c:AppContext, liability_id?:any){ const b=await c.req.json(); return {liability_id:liability_id??b.liability_id,payment_date:b.payment_date,payment_amount:int(b.payment_amount),principal_component:b.principal_component==null?null:int(b.principal_component),interest_component:b.interest_component==null?null:int(b.interest_component),fee_component:b.fee_component==null?null:int(b.fee_component),tax_component:b.tax_component==null?null:int(b.tax_component),outstanding_after:b.outstanding_after==null?null:int(b.outstanding_after),payment_type:b.payment_type||'emi',movement_id:b.movement_id??null,source:b.source||(b.movement_id?'linked_movement':'manual'),notes:b.notes??null}; }
async function validatePayment(c:AppContext,p:any){ const uid=c.get('userId'); if(!PAYMENT_TYPES.includes(p.payment_type)||!SOURCES.includes(p.source))return 'Invalid payment type/source'; if(!await getOwned(c.env.DB,uid,p.liability_id))return 'Liability not found'; if(p.movement_id){ const m=await c.env.DB.prepare('SELECT * FROM movements WHERE user_id=? AND id=?').bind(uid,p.movement_id).first<any>(); if(!m)return 'Movement not found for user'; const used=await c.env.DB.prepare('SELECT id FROM liability_payments WHERE user_id=? AND movement_id=? AND id<>COALESCE(?,0)').bind(uid,p.movement_id,p.id??0).first<any>(); if(used)return 'Movement already linked'; } return null; }
app.get('/:id/payments',async c=>c.json({payments:(await c.env.DB.prepare('SELECT * FROM liability_payments WHERE user_id=? AND liability_id=? ORDER BY payment_date DESC,id DESC').bind(c.get('userId'),c.req.param('id')).all()).results}));
app.post('/:id/payments',async c=>{ const p=await paymentBody(c,c.req.param('id')); const e=await validatePayment(c,p); if(e)return bad(c,e); const r=await c.env.DB.prepare(`INSERT INTO liability_payments (user_id,liability_id,payment_date,payment_amount,principal_component,interest_component,fee_component,tax_component,outstanding_after,payment_type,movement_id,source,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(c.get('userId'),...Object.values(p)).run(); return c.json({id:r.meta.last_row_id,...p},201); });
app.get('/:id/balance-snapshots',async c=>c.json({balance_snapshots:(await c.env.DB.prepare('SELECT * FROM liability_balance_snapshots WHERE user_id=? AND liability_id=? ORDER BY snapshot_date DESC,id DESC').bind(c.get('userId'),c.req.param('id')).all()).results}));
app.post('/:id/balance-snapshots',async c=>{ const b=await c.req.json(); const uid=c.get('userId'); if(!await getOwned(c.env.DB,uid,c.req.param('id')))return c.json({error:'Not found'},404); const r=await c.env.DB.prepare(`INSERT INTO liability_balance_snapshots (user_id,liability_id,snapshot_date,outstanding_balance,accrued_interest,source,notes) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,liability_id,snapshot_date) DO UPDATE SET outstanding_balance=excluded.outstanding_balance,accrued_interest=excluded.accrued_interest,source=excluded.source,notes=excluded.notes,updated_at=datetime('now')`).bind(uid,c.req.param('id'),b.snapshot_date,int(b.outstanding_balance),b.accrued_interest==null?null:int(b.accrued_interest),b.source||'manual',b.notes??null).run(); return c.json({id:r.meta.last_row_id,liability_id:Number(c.req.param('id')),...b},201); });
app.get('/:id/schedule',async c=>{ const uid=c.get('userId'), l=await getOwned(c.env.DB,uid,c.req.param('id')); if(!l)return c.json({error:'Not found'},404); const v=await calculateLiability(c.env.DB,uid,l); const rows=schedule(l,v.payments); return c.json({estimate:true,expected_emi:int(l.emi_amount)||expectedEmi(l.original_principal,l.interest_rate,l.repayment_frequency,l.interest_type,rows.length),remaining_principal:v.outstanding,remaining_installments:rows.filter(r=>r.remaining>0).length,projected_maturity_date:rows.at(-1)?.due_date??null,total_projected_interest:rows.reduce((s,r)=>s+r.interest,0),next_due_date:l.next_due_date||rows.find(r=>r.due_date>=new Date().toISOString().slice(0,10))?.due_date,overdue_amount:dueStatus(l.next_due_date)==='overdue'?int(l.emi_amount):0,assumptions:['Calculated schedules are estimates only.'],warnings:v.warnings,schedule:rows}); });
export default app;
