import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { audit, ensureDefaultHousehold } from '../ownership-service';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>();
const types=['individual','equal_split','percentage','fixed_amount','household'];
async function movement(db:D1Database,u:number,id:any){return db.prepare('SELECT * FROM movements WHERE user_id=? AND id=?').bind(u,id).first<any>();}
app.get('/movements/:id/allocations',async c=>{ const rows=(await c.env.DB.prepare('SELECT a.*, m.display_name member_name FROM movement_allocations a LEFT JOIN household_members m ON m.id=a.member_id WHERE a.user_id=? AND a.movement_id=? ORDER BY a.id').bind(c.get('userId'),c.req.param('id')).all()).results; return c.json(rows); });
app.post('/movements/:id/allocations',async c=>{ const u=c.get('userId'), mid=c.req.param('id'), b=await c.req.json(), mv=await movement(c.env.DB,u,mid); if(!mv)return c.json({error:'Movement not found'},404); const def=await ensureDefaultHousehold(c.env.DB,u); const items=Array.isArray(b.items)?b.items:[b]; let total=0; for(const it of items){ if(!types.includes(it.allocation_type))return c.json({error:'invalid allocation_type'},400); const amt=it.allocation_type==='percentage'?Math.round(mv.amount*Number(it.allocation_percent||0)/100):Number(it.allocation_amount??(it.allocation_type==='household'?mv.amount:0)); total+=amt; }
 if(b.enforce_total!==false && total!==Number(mv.amount))return c.json({error:'allocation total must equal movement amount',total,amount:mv.amount},400); const ids=[]; for(const it of items){ const amt=it.allocation_type==='percentage'?Math.round(mv.amount*Number(it.allocation_percent||0)/100):it.allocation_amount??(it.allocation_type==='household'?mv.amount:null); const r:any=await c.env.DB.prepare('INSERT INTO movement_allocations(user_id,household_id,movement_id,member_id,allocation_type,allocation_percent,allocation_amount,purpose) VALUES(?,?,?,?,?,?,?,?)').bind(u,it.household_id||def.household.id,mid,it.member_id??null,it.allocation_type,it.allocation_percent??null,amt,it.purpose||null).run(); ids.push(r.meta.last_row_id); }
 await audit(c.env.DB,u,def.household.id,'movement_allocation',Number(mid),'added','Expense allocation added'); return c.json({created:ids.length,ids},201); });
app.put('/movement-allocations/:id',async c=>{ const u=c.get('userId'), id=c.req.param('id'), b=await c.req.json(); await c.env.DB.prepare('UPDATE movement_allocations SET member_id=COALESCE(?,member_id),allocation_type=COALESCE(?,allocation_type),allocation_percent=?,allocation_amount=?,purpose=?,updated_at=datetime(\'now\') WHERE user_id=? AND id=?').bind(b.member_id??null,b.allocation_type??null,b.allocation_percent??null,b.allocation_amount??null,b.purpose??null,u,id).run(); return c.json(await c.env.DB.prepare('SELECT * FROM movement_allocations WHERE user_id=? AND id=?').bind(u,id).first()); });
app.delete('/movement-allocations/:id',async c=>{ await c.env.DB.prepare('DELETE FROM movement_allocations WHERE user_id=? AND id=?').bind(c.get('userId'),c.req.param('id')).run(); return c.json({success:true,fallback_restored:true}); });
export default app;
