import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { ALLOCATION_BASIS, OWNERSHIP_TYPES, RECORD_TYPES, audit, ensureDefaultHousehold, resolveOwnership } from '../ownership-service';
const app=new Hono<{Bindings:Bindings;Variables:Variables}>();
async function validate(db:D1Database,u:number,b:any,id?:any){ if(!RECORD_TYPES.includes(b.record_type))return 'invalid record_type'; if(!OWNERSHIP_TYPES.includes(b.ownership_type))return 'invalid ownership_type'; if(!ALLOCATION_BASIS.includes(b.allocation_basis||'full'))return 'invalid allocation_basis'; const pct=Number(b.ownership_percent??100); if(!Number.isFinite(pct)||pct<0||pct>100)return 'ownership_percent must be between 0 and 100'; const rows=(await db.prepare('SELECT ownership_percent FROM financial_record_ownership WHERE user_id=? AND record_type=? AND record_id=? AND ownership_type<>\'beneficiary\' AND allocation_basis<>\'informational\' '+(id?'AND id<>?':'')).bind(...(id?[u,b.record_type,b.record_id,id]:[u,b.record_type,b.record_id])).all<any>()).results||[]; const total=rows.reduce((s,r)=>s+Number(r.ownership_percent||0),0)+pct; if(total>100.0001)return 'total economic ownership cannot exceed 100%'; return null; }
app.get('/ownership',async c=>{ const u=c.get('userId'); const wh=['o.user_id=?'], b:any[]=[u]; for(const k of ['member_id','ownership_type','record_type']) if(c.req.query(k)){ wh.push(`o.${k}=?`); b.push(c.req.query(k)); } const rows=(await c.env.DB.prepare(`SELECT o.*, m.display_name member_name FROM financial_record_ownership o LEFT JOIN household_members m ON m.id=o.member_id WHERE ${wh.join(' AND ')} ORDER BY o.record_type,o.record_id,o.id`).bind(...b).all()).results; return c.json(rows); });
app.post('/ownership/preview',async c=>{ const u=c.get('userId'), b=await c.req.json(); const current=b.record_type&&b.record_id?await resolveOwnership(c.env.DB,u,b.record_type,Number(b.record_id)):null; return c.json({current,proposed:b,warnings:current?.warnings||[]}); });
app.post('/ownership/apply',async c=>{ const u=c.get('userId'), b=await c.req.json(); if(!Array.isArray(b.items))return c.json({error:'items required'},400); const out=[]; for(const item of b.items){ const e=await validate(c.env.DB,u,item); if(e)return c.json({error:e,item},400); const r:any=await c.env.DB.prepare('INSERT INTO financial_record_ownership(user_id,household_id,record_type,record_id,member_id,ownership_type,ownership_percent,allocation_basis) VALUES(?,?,?,?,?,?,?,?)').bind(u,item.household_id,item.record_type,item.record_id,item.member_id??null,item.ownership_type,Number(item.ownership_percent??100),item.allocation_basis||'full').run(); out.push(r.meta.last_row_id); } return c.json({applied:out.length,ids:out},201); });
app.post('/ownership',async c=>{ const u=c.get('userId'), b=await c.req.json(), def=await ensureDefaultHousehold(c.env.DB,u); b.household_id=b.household_id||def.household.id; const e=await validate(c.env.DB,u,b); if(e)return c.json({error:e},400); const r:any=await c.env.DB.prepare('INSERT INTO financial_record_ownership(user_id,household_id,record_type,record_id,member_id,ownership_type,ownership_percent,allocation_basis) VALUES(?,?,?,?,?,?,?,?)').bind(u,b.household_id,b.record_type,b.record_id,b.member_id??null,b.ownership_type,Number(b.ownership_percent??100),b.allocation_basis||'full').run(); await audit(c.env.DB,u,b.household_id,'ownership',r.meta.last_row_id,'assigned','Ownership assigned'); return c.json(await c.env.DB.prepare('SELECT * FROM financial_record_ownership WHERE user_id=? AND id=?').bind(u,r.meta.last_row_id).first(),201); });
app.put('/ownership/:id',async c=>{ const u=c.get('userId'), id=c.req.param('id'), existing=await c.env.DB.prepare('SELECT * FROM financial_record_ownership WHERE user_id=? AND id=?').bind(u,id).first<any>(); if(!existing)return c.json({error:'Not found'},404); const b={...existing,...await c.req.json()}; const e=await validate(c.env.DB,u,b,id); if(e)return c.json({error:e},400); await c.env.DB.prepare('UPDATE financial_record_ownership SET member_id=?,ownership_type=?,ownership_percent=?,allocation_basis=?,updated_at=datetime(\'now\') WHERE user_id=? AND id=?').bind(b.member_id??null,b.ownership_type,Number(b.ownership_percent),b.allocation_basis,u,id).run(); await audit(c.env.DB,u,existing.household_id,'ownership',Number(id),'changed','Ownership changed'); return c.json(await c.env.DB.prepare('SELECT * FROM financial_record_ownership WHERE user_id=? AND id=?').bind(u,id).first()); });
app.delete('/ownership/:id',async c=>{ const u=c.get('userId'), id=c.req.param('id'), ex=await c.env.DB.prepare('SELECT * FROM financial_record_ownership WHERE user_id=? AND id=?').bind(u,id).first<any>(); if(!ex)return c.json({error:'Not found'},404); await c.env.DB.prepare('DELETE FROM financial_record_ownership WHERE user_id=? AND id=?').bind(u,id).run(); await audit(c.env.DB,u,ex.household_id,'ownership',Number(id),'removed','Ownership removed'); return c.json({success:true}); });
export default app;
