import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { sha256Hex, normalizeImportRow, resolveAccount, resolveAsset, fingerprint, existingSeq, validateNoOversell } from '../wealth/imports';
import { parseDecimal, formatDecimal } from '../wealth/decimal';
import { extractFinancialDocumentWithOpenAI, OpenAIClientError } from '../openai/client';
import { FINANCIAL_DOCUMENT_SCHEMA_VERSION } from '../openai/schemas/financial-document';
const route=new Hono<{Bindings:Bindings;Variables:Variables}>(); const bad=(error:string,code=400)=>({error,code});
const okTypes=['application/pdf','image/png','image/jpeg','text/plain','text/csv'];
const okDocumentTypes=['unknown','holdings_statement','broker_tradebook','broker_contract_note'];
const STALE_PROCESSING_MINUTES=5;
const READY_STATUSES=new Set(['extracted','ready_for_import']);
const RETRYABLE_DUPLICATE_STATUSES=new Set(['failed','validation_failed','deleted']);
function mask(v:any){ const s=String(v||''); return s?`****${s.replace(/\D/g,'').slice(-4)}`:null; }
function csvConsent(value:FormDataEntryValue|null){ return String(value||'').toLowerCase()==='true'; }
function validateDocumentType(documentType:string){ if(!okDocumentTypes.includes(documentType)) throw new Error('Unsupported document type'); }
function validateFile(file:File, explicitCsv:boolean, env:any){ const max=Number(env.OPENAI_MAX_FILE_BYTES||10*1024*1024); if(file.size>max) throw new Error('File exceeds OpenAI extraction size limit'); if(!okTypes.includes(file.type||'') && !/\.(pdf|png|jpe?g|txt|csv)$/i.test(file.name)) throw new Error('Unsupported file type'); if((file.type==='text/csv'||/\.csv$/i.test(file.name))&&!explicitCsv) throw new Error('CSV AI interpretation must be explicitly selected'); }
function safeError(e:any){ const code=e instanceof OpenAIClientError?e.code:(e?.code||'extract_failed'); const mapped=code==='timeout'?'openai_timeout':code; const msg=mapped==='openai_timeout'?'OpenAI extraction timed out. Please retry the extraction.':mapped==='openai_refusal'?'OpenAI refused to extract this document.':mapped==='invalid_schema'?'OpenAI returned data that could not be validated. Please retry or use a clearer document.':mapped==='missing_api_key'?'OpenAI document extraction is not configured on the server.':e?.code?'OpenAI extraction failed. Please retry.':String(e?.message||'OpenAI extraction failed. Please retry.'); return {code:mapped,message:msg,status:mapped==='invalid_schema'?'validation_failed':'failed'}; }
async function failExtraction(c:any,uid:number,id:number,e:any){ const safe=safeError(e); await c.env.DB.prepare(`UPDATE ai_document_extractions SET status=?, error_code=?, error_message=?, updated_at=datetime('now') WHERE id=? AND user_id=?`).bind(safe.status,safe.code,safe.message,id,uid).run(); return safe; }
async function recoverStale(c:any,uid:number,id?:number){ const where=id?'user_id=? AND id=?':'user_id=?'; const params=id?[uid,id]:[uid]; await c.env.DB.prepare(`UPDATE ai_document_extractions SET status='failed', error_code='stale_processing', error_message='Extraction processing took too long and was marked failed. Please retry.', updated_at=datetime('now') WHERE ${where} AND status='processing' AND deleted_at IS NULL AND datetime(COALESCE(updated_at,created_at)) <= datetime('now', '-' || ? || ' minutes')`).bind(...params,STALE_PROCESSING_MINUTES).run(); }
function presentExtraction(r:any){ return {...r,file_hash:undefined,file_hash_prefix:r.file_hash_prefix||r.file_hash?.slice(0,12),extraction:r.extracted_json?JSON.parse(r.extracted_json):null,validation:r.validation_json?JSON.parse(r.validation_json):null,usage:r.usage_json?JSON.parse(r.usage_json):null,extracted_json:undefined,validation_json:undefined,usage_json:undefined}; }
function validation(j:any){ const warnings:string[]=[]; const date=/^\d{4}-\d{2}-\d{2}$/; for(const t of j.transactions||[]){ if(t.trade_date&&!date.test(t.trade_date)) warnings.push(`Invalid trade date for ${t.symbol||t.asset_name||'transaction'}`); for(const k of ['quantity','unit_price']) if(t[k]!=null) try{parseDecimal(String(t[k]),{allowZero:true});}catch{warnings.push(`Invalid decimal ${k}`);} } for(const h of j.holdings||[]) if(h.quantity!=null) try{parseDecimal(String(h.quantity),{allowZero:true});}catch{warnings.push(`Invalid holding quantity`);} return {warnings,valid:warnings.length===0}; }
route.post('/extract', async c=>{ const uid=c.get('userId'); let id:number|null=null; try{ const form=await c.req.formData(); const file=form.get('file') as File|null; if(!file)return c.json(bad('file required'),400); const requested=String(form.get('document_type')||'unknown'); validateDocumentType(requested); validateFile(file, csvConsent(form.get('allow_csv_ai_interpretation')), c.env); const bytes=new Uint8Array(await file.arrayBuffer()); if(file.type==='application/pdf' && new TextDecoder('latin1').decode(bytes.slice(0,4096)).includes('/Encrypt')) return c.json(bad('Encrypted/password-protected PDFs are not supported'),400); const hash=await sha256Hex(bytes); await recoverStale(c as any,uid); const prev=await c.env.DB.prepare(`SELECT id,status FROM ai_document_extractions WHERE user_id=? AND file_hash=? AND deleted_at IS NULL ORDER BY id DESC LIMIT 1`).bind(uid,hash).first<any>(); if(prev&&!RETRYABLE_DUPLICATE_STATUSES.has(prev.status)) return c.json({duplicate:true,id:prev.id,status:prev.status}); const processing=await c.env.DB.prepare(`INSERT INTO ai_document_extractions (user_id,file_name,file_hash,document_type_requested,status,schema_version,prompt_version) VALUES (?,?,?,?,?,?,?)`).bind(uid,file.name,hash,requested,'processing',FINANCIAL_DOCUMENT_SCHEMA_VERSION,'2026-07-13.1').run(); id=processing.meta.last_row_id; try{ const out=await extractFinancialDocumentWithOpenAI(c.env,{name:file.name,type:file.type||'application/octet-stream',bytes},requested); out.json.document=out.json.document||{}; out.json.document.account_number_masked=mask(out.json.document.account_number_masked); const v=validation(out.json); const status=v.valid?'extracted':'validation_failed'; await c.env.DB.prepare(`UPDATE ai_document_extractions SET status=?, error_code=NULL, error_message=NULL, document_type_detected=?, model=?, response_id=?, extracted_json=?, validation_json=?, usage_json=?, updated_at=datetime('now') WHERE id=? AND user_id=?`).bind(status,out.json.document.document_type,out.model,out.response_id,JSON.stringify(out.json),JSON.stringify(v),JSON.stringify(out.usage),id,uid).run(); return c.json({id,status,extraction:out.json,validation:v,model:out.model,response_id:out.response_id}); }catch(e:any){ const safe=await failExtraction(c as any,uid,id!,e); return c.json(bad(safe.message,safe.code), safe.code==='missing_api_key'?503:400); } }catch(e:any){ const safe=safeError(e); if(id) await failExtraction(c as any,uid,id,e); return c.json(bad(safe.message,safe.code), safe.code==='missing_api_key'?503:400); }});
route.get('/', async c=>{ const uid=c.get('userId'); await recoverStale(c as any,uid); const r=await c.env.DB.prepare(`SELECT id,file_name,substr(file_hash,1,12) file_hash_prefix,document_type_requested,document_type_detected,status,model,response_id,schema_version,prompt_version,validation_json,usage_json,error_code,error_message,created_at,updated_at FROM ai_document_extractions WHERE user_id=? AND deleted_at IS NULL ORDER BY created_at DESC,id DESC`).bind(uid).all<any>(); return c.json(r.results.map(presentExtraction)); });
route.get('/:id', async c=>{ const uid=c.get('userId'),id=Number(c.req.param('id')); await recoverStale(c as any,uid,id); const r=await c.env.DB.prepare(`SELECT * FROM ai_document_extractions WHERE id=? AND user_id=? AND deleted_at IS NULL`).bind(id,uid).first<any>(); if(!r)return c.json(bad('Not found'),404); return c.json(presentExtraction(r)); });
route.delete('/:id', async c=>{ const uid=c.get('userId'),id=Number(c.req.param('id')); await c.env.DB.prepare(`UPDATE ai_document_extractions SET status='deleted',deleted_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND user_id=?`).bind(id,uid).run(); return c.json({deleted:true}); });
route.post('/:id/prepare', async c=>{ const uid=c.get('userId'),id=Number(c.req.param('id')); try{ const req=await c.req.json().catch(()=>({})); const rec=await c.env.DB.prepare(`SELECT * FROM ai_document_extractions WHERE id=? AND user_id=? AND deleted_at IS NULL`).bind(id,uid).first<any>(); if(!rec)return c.json(bad('Not found'),404); if(!READY_STATUSES.has(rec.status)) return c.json(bad('Extraction is not ready to prepare for import','extraction_not_ready'),409); const ex=JSON.parse(rec.extracted_json||'{}'); const doc=ex.document||{}; const cutover=req.cutover_date||doc.statement_date||'2026-04-01'; const rows:any[]=[]; if(doc.document_type==='holdings_statement'){ for(const h of ex.holdings||[]) rows.push({account_name:req.account_name,asset_name:h.asset_name||h.symbol,asset_type:'stock',symbol:h.symbol,isin:h.isin,exchange:h.exchange,transaction_type:'transfer_in',trade_date:new Date(new Date(cutover+'T00:00:00Z').getTime()-86400000).toISOString().slice(0,10),quantity:h.quantity,unit_price:h.average_cost,gross_amount:h.total_cost,net_amount:h.total_cost,currency:'INR',external_ref:`ai:${id}:${h.isin||h.symbol}`,notes:'Opening holding proposed from OpenAI extraction'}); } else { for(const t of ex.transactions||[]) rows.push({account_name:req.account_name,asset_name:t.asset_name||t.symbol,asset_type:'stock',symbol:t.symbol,isin:t.isin,exchange:t.exchange,transaction_type:t.transaction_type,trade_date:t.trade_date,settlement_date:t.settlement_date,quantity:t.quantity,unit_price:t.unit_price,gross_amount:t.gross_amount,charges:t.charges||0,taxes:t.taxes||0,net_amount:t.net_amount,currency:'INR',external_ref:t.external_ref,notes:'Proposed from OpenAI extraction'}); }
 const batch=await c.env.DB.prepare(`INSERT INTO wealth_import_batches (user_id,file_name,file_hash,source_type,status,mapping_json,options_json,total_rows) VALUES (?,?,?,?,?,?,?,?)`).bind(uid,rec.file_name,rec.file_hash,'openai_document','previewed','{}',JSON.stringify({openai_extraction_id:id,default_account_id:req.account_id,default_currency:'INR'}),rows.length).run(); const batchId=batch.meta.last_row_id as number; let valid=0,invalid=0,dup=0; const preview:any[]=[]; for(let i=0;i<rows.length;i++){ let status='valid',err=null,n:any=null,acc:any=null,asset:any=null,fp:any=null; try{ n=normalizeImportRow(rows[i],Object.fromEntries(Object.keys(rows[i]).map(k=>[k,k])),{default_account_id:req.account_id,default_currency:'INR'}); n=n.normalized; acc=await resolveAccount(c as any,uid,n,{default_account_id:req.account_id}); asset=await resolveAsset(c as any,uid,n); fp=await fingerprint(uid,n,acc,asset); if(n.transaction_type&&acc.id&&asset.id) validateNoOversell(await existingSeq(c as any,uid,acc.id,asset.id,[{...n,account_id:acc.id,asset_id:asset.id}])); }catch(e:any){status='invalid';err=e.message;} if(status==='valid')valid++; else invalid++; await c.env.DB.prepare(`INSERT INTO wealth_import_rows (user_id,batch_id,row_number,raw_json,normalized_json,fingerprint,status,error_code,error_message,warning_json) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(uid,batchId,i+1,JSON.stringify(rows[i]),n?JSON.stringify({...n,account:acc,asset}):null,fp,status,status==='invalid'?'validation_error':null,err,'[]').run(); if(preview.length<100)preview.push({row_number:i+1,status,normalized:n,account:acc,asset,errors:err?[err]:[]}); } await c.env.DB.prepare(`UPDATE wealth_import_batches SET valid_rows=?,invalid_rows=?,duplicate_rows=?,status=?,updated_at=datetime('now') WHERE id=?`).bind(valid,invalid,dup,invalid?'previewed':'validated',batchId).run(); await c.env.DB.prepare(`UPDATE ai_document_extractions SET status='ready_for_import',updated_at=datetime('now') WHERE id=? AND user_id=?`).bind(id,uid).run(); return c.json({batch_id:batchId,total_rows:rows.length,valid_rows:valid,invalid_rows:invalid,duplicate_rows:dup,rows:preview,can_commit:valid>0&&invalid===0}); }catch(e:any){return c.json(bad(e.message),400);} });
export default route;
