import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { marketPriceStatus, refreshMarketPrices } from '../wealth/market-prices';
import { parseCsv } from '../wealth/csv';
import { isDateOnly, normalizeCurrency } from '../wealth/validation';
import { formatDecimal, parseDecimal } from '../wealth/decimal';
const route=new Hono<{Bindings:Bindings;Variables:Variables}>();
const bad=(m:string)=>({error:m});
const today=()=>new Date().toISOString().slice(0,10);
const norm=(v:any)=>String(v??'').trim();
const up=(v:any)=>norm(v).toUpperCase();
const esc=(v:any)=>{const s=String(v??'');return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};
const warnPct=(env:any)=>Number(env.EOD_PRICE_WARNING_PERCENT||20);
const blockPct=(env:any)=>Number(env.EOD_PRICE_BLOCK_PERCENT||50);

async function resolveAsset(c:any, uid:number, r:any){
  const assetId=Number(r.asset_id||0);
  if(assetId){ const a=await c.env.DB.prepare('SELECT * FROM investment_assets WHERE user_id=? AND id=? AND is_active<>0 AND asset_type=\'stock\'').bind(uid,assetId).first(); if(a)return{asset:a}; }
  const isin=up(r.isin); if(isin){ const rows=(await c.env.DB.prepare('SELECT * FROM investment_assets WHERE user_id=? AND UPPER(isin)=? AND is_active<>0 AND asset_type=\'stock\'').bind(uid,isin).all()).results; if(rows.length===1)return{asset:rows[0]}; if(rows.length>1)return{error:'ambiguous ISIN'}; }
  const symbol=up(r.symbol), exchange=up(r.exchange); if(symbol&&exchange){ const rows=(await c.env.DB.prepare('SELECT * FROM investment_assets WHERE user_id=? AND UPPER(symbol)=? AND UPPER(exchange)=? AND is_active<>0 AND asset_type=\'stock\'').bind(uid,symbol,exchange).all()).results; if(rows.length===1)return{asset:rows[0]}; if(rows.length>1)return{error:'ambiguous symbol and exchange'}; }
  return {error:'asset not found'};
}
async function latestPrice(c:any, uid:number, aid:number, date?:string){return c.env.DB.prepare(`SELECT price_date,price,currency,source FROM investment_prices WHERE user_id=? AND asset_id=? ${date?'AND price_date<=?':''} ORDER BY price_date DESC,id DESC LIMIT 1`).bind(...(date?[uid,aid,date]:[uid,aid])).first();}
async function validatePriceCsv(c:any, text:string, fileName='eod-prices.csv'){
 const uid=c.get('userId'); const parsed=parseCsv(text,{maxFileSize:2*1024*1024,maxRows:500,maxColumns:20,maxCellLength:1000}); const seen=new Map<string,number>(); const rows:any[]=[]; let skipped_blank_rows=0, duplicate_rows=0, unchanged_rows=0, suspicious_rows=0;
 const add=(r:any)=>{ rows.push(r); if(r.status==='duplicate')duplicate_rows++; if(r.status==='unchanged')unchanged_rows++; if(r.status==='warning'||r.status==='blocked')suspicious_rows++; };
 for(const e of parsed.errors) add({row_number:e.rowNumber,status:'invalid',errors:[e.message],warnings:[]});
 for(const row of parsed.rows){ const raw:any={}; for(const [k,v] of Object.entries(row.raw)) raw[k.toLowerCase().trim()]=String(v).trim(); const hasNew='new_price_date' in raw || 'new_close' in raw; const price_date=hasNew?raw.new_price_date:raw.price_date; const close=hasNew?raw.new_close:raw.close; const blank=!Object.values(raw).some(v=>String(v).trim()); const out:any={row_number:row.rowNumber,status:'valid',raw,errors:[],warnings:[],symbol:raw.symbol,exchange:raw.exchange,isin:raw.isin,proposed_price_date:price_date,proposed_price:close};
   if(blank || (hasNew&&!price_date&&!close)){ skipped_blank_rows++; add({...out,status:'skipped',skip_reason:'blank row or no new price supplied'}); continue; }
   const res=await resolveAsset(c,uid,raw); if(res.error){add({...out,status:'invalid',errors:[res.error]});continue} const a=res.asset; Object.assign(out,{asset_id:a.id,asset_name:a.name,symbol:a.symbol,exchange:a.exchange,isin:a.isin});
   if(!isDateOnly(price_date)||!price_date){add({...out,status:'invalid',errors:['invalid price_date']});continue} if(price_date>today()){add({...out,status:'invalid',errors:['future price_date']});continue}
   let price:string; try{price=formatDecimal(parseDecimal(close,{allowZero:false}));}catch{add({...out,status:'invalid',errors:['invalid close']});continue}
   const currency=normalizeCurrency(raw.currency||'INR'); if(!currency||currency!=='INR'){add({...out,status:'invalid',errors:['unsupported currency']});continue}
   const key=`${a.id}:${price_date}`; if(seen.has(key)){ add({...out,status:'duplicate',errors:[`duplicate row; first seen at CSV row ${seen.get(key)}`]}); continue; } seen.set(key,row.rowNumber);
   const prev=await latestPrice(c,uid,a.id); const same=await c.env.DB.prepare('SELECT price,source,price_date FROM investment_prices WHERE user_id=? AND asset_id=? AND price_date=?').bind(uid,a.id,price_date).first();
   let status='valid'; const warnings:string[]=[]; const errors:string[]=[]; let abs_change:null|number=null, pct_change:null|number=null;
   const base=prev?Number(prev.price):null; if(base&&base>0){ abs_change=Number(price)-base; pct_change=abs_change/base*100; if(Math.abs(pct_change)>blockPct(c.env)){status='blocked'; errors.push('Large price change detected. Verify for stock split, bonus, symbol mismatch, or incorrect decimal.');} else if(Math.abs(pct_change)>warnPct(c.env)){status='warning'; warnings.push('Large price change detected. Verify for stock split, bonus, symbol mismatch, or incorrect decimal.');} }
   if(same&&Number(same.price)===Number(price)){status='unchanged'; warnings.push('same asset/date/price already exists; row will be skipped');}
   else if(same&&same.source==='manual'){status='protected'; errors.push('same-date manual price exists; overwrite_manual is required');}
   else if(same){warnings.push('same-date correction candidate');}
   add({...out,status,errors,warnings,price_date,close:price,currency,previous_price:prev?.price??null,previous_price_date:prev?.price_date??null,previous_source:prev?.source??null,proposed_price:price,proposed_price_date:price_date,absolute_change:abs_change,percentage_change:pct_change,notes:`manual EOD CSV: ${fileName}`});
 }
 const invalid_rows=rows.filter(r=>['invalid','blocked','protected','duplicate'].includes(r.status)).length; const valid_rows=rows.filter(r=>['valid','warning','unchanged'].includes(r.status)).length; return {headers:parsed.headers,total_rows:parsed.rows.length,valid_rows,invalid_rows,skipped_blank_rows,duplicate_rows,unchanged_rows,suspicious_rows,can_commit:invalid_rows===0&&valid_rows>0,rows};
}
async function createPreview(c:any,text:string,fileName:string){ const uid=c.get('userId'); const p=await validatePriceCsv(c,text,fileName); const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(b=>b.toString(16).padStart(2,'0')).join(''); const b=await c.env.DB.prepare(`INSERT INTO wealth_import_batches (user_id,file_name,file_hash,source_type,status,total_rows,valid_rows,invalid_rows,duplicate_rows,skipped_rows,failed_rows,mapping_json,options_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id`).bind(uid,fileName,hash,'eod_price_csv','previewed',p.total_rows,p.valid_rows,p.invalid_rows,p.duplicate_rows,p.skipped_blank_rows,p.invalid_rows,JSON.stringify(p.rows),JSON.stringify({kind:'eod_price_preview'})).first(); return {...p,preview_id:b?.id}; }

route.get('/status', async c=>c.json(await marketPriceStatus(c as any)));
route.get('/template', c=>new Response('symbol,exchange,isin,price_date,close,currency\n',{headers:{'content-type':'text/csv','content-disposition':'attachment; filename=market-price-template.csv'}}));
route.get('/holdings-template', async c=>{ const uid=c.get('userId'), asOf=c.req.query('as_of')||today(), account=c.req.query('account_id'), onlyMissing=String(c.req.query('only_missing')||'false')==='true'; const b:any[]=[uid,asOf]; let acct=''; if(account){acct=' AND t.account_id=?'; b.push(account)} const sql=`SELECT a.id asset_id,a.symbol,a.exchange,a.isin,a.name asset_name, SUM(CASE WHEN t.transaction_type IN ('buy','transfer_in') THEN CAST(COALESCE(t.quantity,0) AS REAL) WHEN t.transaction_type IN ('sell','transfer_out') THEN -CAST(COALESCE(t.quantity,0) AS REAL) ELSE 0 END) quantity, (SELECT price_date FROM investment_prices p WHERE p.user_id=a.user_id AND p.asset_id=a.id ORDER BY price_date DESC,id DESC LIMIT 1) existing_price_date, (SELECT price FROM investment_prices p WHERE p.user_id=a.user_id AND p.asset_id=a.id ORDER BY price_date DESC,id DESC LIMIT 1) existing_close FROM investment_assets a JOIN investment_transactions t ON t.user_id=a.user_id AND t.asset_id=a.id WHERE a.user_id=? AND t.trade_date<=? ${acct} AND a.is_active<>0 AND a.asset_type='stock' GROUP BY a.id HAVING quantity>0 ORDER BY a.symbol,a.exchange`;
 const rows=(await c.env.DB.prepare(sql).bind(...b).all()).results.filter((r:any)=>!onlyMissing||!r.existing_price_date); const header=['asset_id','symbol','exchange','isin','asset_name','quantity','existing_price_date','existing_close','new_price_date','new_close','currency']; const csv=[header.join(','),...rows.map((r:any)=>[r.asset_id,r.symbol,r.exchange,r.isin,r.asset_name,r.quantity,r.existing_price_date,r.existing_close,'','','INR'].map(esc).join(','))].join('\n')+'\n'; return new Response(csv,{headers:{'content-type':'text/csv','content-disposition':`attachment; filename=kotecash-eod-prices-${asOf}.csv`}}); });
route.post('/import-csv/preview', async c=>{ try{ const form=await c.req.formData(); const file=form.get('file'); if(!(file instanceof File)) return c.json(bad('CSV file is required'),400); return c.json(await createPreview(c as any,await file.text(),file.name||'eod-prices.csv')); }catch(e:any){ return c.json(bad(e.message||'CSV preview failed'),400); }});
route.get('/import-csv/:preview_id', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('preview_id')); const b=await c.env.DB.prepare('SELECT * FROM wealth_import_batches WHERE user_id=? AND id=? AND source_type=\'eod_price_csv\'').bind(uid,id).first(); if(!b)return c.json(bad('Not found'),404); const rows=JSON.parse(b.mapping_json||'[]'); return c.json({preview_id:id,total_rows:b.total_rows,valid_rows:b.valid_rows,invalid_rows:b.invalid_rows,duplicate_rows:b.duplicate_rows,skipped_blank_rows:b.skipped_rows,can_commit:b.invalid_rows===0&&b.valid_rows>0,rows}); });
route.post('/import-csv/:preview_id/commit', async c=>{ try{ const uid=c.get('userId'), id=Number(c.req.param('preview_id')), body=await c.req.json().catch(()=>({})); const b=await c.env.DB.prepare('SELECT * FROM wealth_import_batches WHERE user_id=? AND id=? AND source_type=\'eod_price_csv\'').bind(uid,id).first(); if(!b)return c.json(bad('Not found'),404); const rows=JSON.parse(b.mapping_json||'[]'); let updated=0,skipped=0,failed=0; const warnings:string[]=[]; let valuation_date:null|string=null; for(const r of rows){ if(r.status==='unchanged'||r.status==='skipped'){skipped++; continue} if(r.status==='warning'&&!body.confirm_warnings){failed++; warnings.push('confirm_warnings is required'); continue} if(['invalid','duplicate','blocked'].includes(r.status)){failed++; continue} const res=await resolveAsset(c,uid,r); if(res.error){failed++; continue} const same=await c.env.DB.prepare('SELECT price,source FROM investment_prices WHERE user_id=? AND asset_id=? AND price_date=?').bind(uid,r.asset_id,r.price_date).first(); if(same&&Number(same.price)===Number(r.close)){skipped++; continue} if(same?.source==='manual'&&!body.overwrite_manual){failed++; warnings.push('manual same-date price protected'); continue} if(same?.source==='import'&&!body.overwrite_same_date_import){failed++; warnings.push('overwrite_same_date_import is required'); continue} await c.env.DB.prepare(`INSERT INTO investment_prices (user_id,asset_id,price_date,price,currency,source,notes,import_batch_id) VALUES (?,?,?,?,?,'import',?,?) ON CONFLICT(user_id,asset_id,price_date) DO UPDATE SET price=excluded.price,currency=excluded.currency,source=excluded.source,notes=excluded.notes,import_batch_id=excluded.import_batch_id,updated_at=datetime('now')`).bind(uid,r.asset_id,r.price_date,r.close,r.currency||'INR',r.notes||'manual EOD CSV',id).run(); updated++; valuation_date=!valuation_date||r.price_date>valuation_date?r.price_date:valuation_date; }
 await c.env.DB.prepare('UPDATE wealth_import_batches SET status=?,imported_rows=?,skipped_rows=?,failed_rows=?,committed_at=datetime(\'now\'),updated_at=datetime(\'now\') WHERE id=?').bind(failed?'partially_imported':'imported',updated,skipped,failed,id).run(); return c.json({updated,skipped,failed,warnings:[...new Set(warnings)],valuation_date}); }catch(e:any){ return c.json(bad(e.message||'CSV commit failed'),400); }});
route.post('/import-csv', async c=>{ const form=await c.req.formData(); const file=form.get('file'); if(!(file instanceof File)) return c.json(bad('CSV file is required'),400); const p=await createPreview(c as any,await file.text(),file.name||'eod-prices.csv'); return c.json({...p,committed:false}); });
route.post('/refresh', async c=>{ try{ const b=await c.req.json().catch(()=>({})); const ids=Array.isArray(b.asset_ids)?b.asset_ids.map(Number).filter(Boolean):undefined; const out=await refreshMarketPrices(c as any,{asset_ids:ids,only_open_holdings:b.only_open_holdings!==false,force:b.force===true}); const code=out.failed&&out.updated===0?400:200; return c.json(out,code as any); }catch(e:any){ return c.json(bad(e.message||'Refresh failed'),400); }});
export default route;
export { validatePriceCsv };
