import { Hono } from 'hono';
import type { AppContext, Bindings, Variables } from '../types';
import { isDateOnly, normalizeCurrency, optionalText, isEnumValue } from '../wealth/validation';
import { parseDecimal, formatDecimal } from '../wealth/decimal';
const route = new Hono<{ Bindings: Bindings; Variables: Variables }>();
const SOURCES = ['manual','import','market','nav','snapshot'] as const; function bad(error:string){return{error}}
async function ownAsset(c:AppContext, uid:number, id:number){return c.env.DB.prepare('SELECT id FROM investment_assets WHERE id=? AND user_id=?').bind(id,uid).first();}
route.get('/', async c=>{const uid=c.get('userId'); const wh=['user_id=?']; const b:any[]=[uid]; for(const [q,f] of [['asset_id','asset_id'],['source','source']] as any){const v=c.req.query(q); if(v){wh.push(`${f}=?`); b.push(v)}} const from=c.req.query('from'),to=c.req.query('to'); if(from){wh.push('price_date>=?');b.push(from)} if(to){wh.push('price_date<=?');b.push(to)} const r=await c.env.DB.prepare(`SELECT * FROM investment_prices WHERE ${wh.join(' AND ')} ORDER BY price_date DESC, id DESC`).bind(...b).all(); return c.json(r.results);});
route.post('/', async c=>{const uid=c.get('userId'); try{const body=await c.req.json(); const aid=Number(body.asset_id); if(!aid||!await ownAsset(c,uid,aid)) throw new Error('Invalid asset ownership'); if(!isDateOnly(body.price_date)||!body.price_date) throw new Error('Invalid price_date'); const price=formatDecimal(parseDecimal(body.price,{allowZero:false})); const currency=normalizeCurrency(body.currency); if(!currency) throw new Error('Invalid currency'); const source=body.source??'manual'; if(!isEnumValue(SOURCES,source)) throw new Error('Invalid source'); const notes=optionalText(body.notes); const r=await c.env.DB.prepare(`INSERT INTO investment_prices (user_id,asset_id,price_date,price,currency,source,notes) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,asset_id,price_date) DO UPDATE SET price=excluded.price,currency=excluded.currency,source=excluded.source,notes=excluded.notes,updated_at=datetime('now') RETURNING id`).bind(uid,aid,body.price_date,price,currency,source,notes).first<any>(); return c.json({id:r?.id,success:true},201);}catch(e:any){return c.json(bad(e.message),400)}});
route.delete('/:id', async c=>{const uid=c.get('userId'), id=Number(c.req.param('id')); const r=await c.env.DB.prepare('DELETE FROM investment_prices WHERE id=? AND user_id=?').bind(id,uid).run(); if((r.meta as any).changes===0)return c.json(bad('Not found'),404); return c.json({success:true});});
export default route;
