import { Hono } from 'hono';
import type { AppContext, Bindings, Variables } from '../types';
import { parseCsv, CSV_LIMITS } from '../wealth/csv';
import { validateMapping, normalizeImportRow, resolveAccount, resolveAsset, fingerprint, sha256Hex, validateMovement, existingSeq, validateNoOversell, CANONICAL_COLUMNS } from '../wealth/imports';

const route = new Hono<{ Bindings: Bindings; Variables: Variables }>();
const bad=(error:string)=>({error});
const DELETABLE_STATUSES = ['uploaded','previewed','validated','failed'];
function page(c:AppContext){ const p=Math.max(1,Number(c.req.query('page')||1)); const ps=Math.min(100,Math.max(1,Number(c.req.query('page_size')||50))); return {p,ps,off:(p-1)*ps}; }
async function batch(c:AppContext, uid:number, id:number){ return c.env.DB.prepare('SELECT * FROM wealth_import_batches WHERE id=? AND user_id=?').bind(id,uid).first<any>(); }
async function duplicateFingerprint(c:AppContext, uid:number, fp:string){ const r=await c.env.DB.prepare(`SELECT id FROM wealth_import_rows WHERE user_id=? AND fingerprint=? AND status IN ('valid','imported') LIMIT 1`).bind(uid,fp).first(); if(r) return true; return false; }
async function canDeleteBatch(c:AppContext, uid:number, bt:any){ if(!bt||!DELETABLE_STATUSES.includes(bt.status)||Number(bt.imported_rows||0)!==0) return false; const rows=await c.env.DB.prepare('SELECT COUNT(*) count FROM wealth_import_rows WHERE user_id=? AND batch_id=? AND (created_transaction_id IS NOT NULL OR created_price_id IS NOT NULL)').bind(uid,bt.id).first<any>(); if(Number(rows?.count||0)>0) return false; const tx=await c.env.DB.prepare('SELECT COUNT(*) count FROM investment_transactions WHERE user_id=? AND import_batch_id=?').bind(uid,bt.id).first<any>(); if(Number(tx?.count||0)>0) return false; const prices=await c.env.DB.prepare('SELECT COUNT(*) count FROM investment_prices WHERE user_id=? AND import_batch_id=?').bind(uid,bt.id).first<any>(); return Number(prices?.count||0)===0; }
function txFrom(n:any, aid:number, sid:number){ return { account_id:aid, asset_id:sid, transaction_type:n.transaction_type, trade_date:n.trade_date, settlement_date:n.settlement_date, quantity:n.quantity, unit_price:n.unit_price, gross_amount:n.gross_amount, charges:n.charges, taxes:n.taxes, net_amount:n.net_amount, movement_id:n.movement_id, external_ref:n.external_ref, notes:n.notes }; }
function isZeroCostTransferIn(n:any){ return n?.transaction_type==='transfer_in' && ![n.net_amount,n.gross_amount,n.unit_price].some(v=>v!=null&&v!==''&&Number(v)!==0); }
function batchCommitEligible(bt:any, rows:any[]=[]){ if(!bt||!['previewed','validated'].includes(bt.status)) return false; if(Number(bt.valid_rows ?? bt.total_rows ?? 0)<=0) return false; if((bt.invalid_rows||0)>0) return false; return !rows.some((r:any)=>{ const n=r.normalized_json?JSON.parse(r.normalized_json):r.normalized; const acc=n?.account, asset=n?.asset; return !acc || (!acc.id && !acc.candidate) || !asset || (!asset.id && !asset.candidate) || isZeroCostTransferIn(n); }); }
function rowHasCandidateAsset(r:any){ const n=r.normalized_json?JSON.parse(r.normalized_json):r.normalized; return !!n?.asset?.candidate; }
function candidateKey(prefix:string,c:any){ return [prefix,c?.isin,c?.scheme_code,c?.symbol,c?.exchange,c?.asset_type,c?.name,c?.account_type,c?.institution].map(v=>String(v??'').toLowerCase()).join('|'); }
function sortRowsForCommit(a:any,b:any){ const an=JSON.parse(a.normalized_json), bn=JSON.parse(b.normalized_json); return String(an.trade_date||'').localeCompare(String(bn.trade_date||'')) || ((a.row_number??a.id??0)-(b.row_number??b.id??0)); }

route.get('/template', c => new Response(CANONICAL_COLUMNS.join(',')+'\n', { headers: { 'content-type':'text/csv; charset=utf-8', 'content-disposition':'attachment; filename="kotecash-wealth-import-template.csv"' } }));

route.post('/preview', async c => { const uid=c.get('userId'); try{ const form=await c.req.formData(); const file=form.get('file') as File|null; if(!file) return c.json(bad('file required'),400); if(file.size>CSV_LIMITS.maxFileSize) return c.json(bad('CSV file exceeds 2 MB limit'),400); const mapping=JSON.parse(String(form.get('mapping')||'{}')); const options=JSON.parse(String(form.get('options')||'{}')); const bytes=new Uint8Array(await file.arrayBuffer()); const fileHash=await sha256Hex(bytes); const prev=await c.env.DB.prepare(`SELECT id,status FROM wealth_import_batches WHERE user_id=? AND file_hash=? AND status<>'rolled_back' ORDER BY id DESC LIMIT 1`).bind(uid,fileHash).first<any>(); if(prev && ['imported','partially_imported','previewed','validated'].includes(prev.status)) return c.json(bad('Duplicate file already uploaded or imported'),409);
 const parsed=parseCsv(bytes); const validMap=validateMapping(mapping, parsed.headers); const batchRes=await c.env.DB.prepare(`INSERT INTO wealth_import_batches (user_id,file_name,file_hash,status,mapping_json,options_json,total_rows) VALUES (?,?,?,?,?,?,?)`).bind(uid,file.name,fileHash,'previewed',JSON.stringify(validMap),JSON.stringify(options),parsed.rows.length).run(); const batchId=batchRes.meta.last_row_id as number; const seen=new Set<string>(); const preview:any[]=[]; let valid=0, invalid=0, dup=0; const seqs=new Map<string,any[]>();
 for(const row of parsed.rows){ let status='valid', err:string|null=null, norm:any=null, acc:any=null, asset:any=null, fp:string|null=null, warns:any[]=[]; try{ const nr=normalizeImportRow(row.raw,validMap,options); norm=nr.normalized; warns=nr.warnings; await validateMovement(c,uid,norm.movement_id); acc=await resolveAccount(c,uid,norm,options); asset=await resolveAsset(c,uid,norm); fp=await fingerprint(uid,norm,acc,asset); if(seen.has(fp)||await duplicateFingerprint(c,uid,fp)){ status='duplicate'; err='Duplicate row'; } else seen.add(fp); if(status==='valid' && norm.transaction_type){ if(!norm.trade_date) throw new Error('trade_date required'); if(!acc.id || !asset.id) { /* candidates validated at commit */ } else { const tx=txFrom(norm,acc.id,asset.id); const key=`${acc.id}:${asset.id}`; const ex=seqs.get(key)||await existingSeq(c,uid,acc.id,asset.id); ex.push(tx); validateNoOversell(ex); seqs.set(key,ex); } } if(status==='valid' && norm.price && !norm.price_date) throw new Error('price_date required'); } catch(e:any){ status='invalid'; err=e.message; }
 if(status==='valid') valid++; else if(status==='duplicate') dup++; else invalid++; await c.env.DB.prepare(`INSERT INTO wealth_import_rows (user_id,batch_id,row_number,raw_json,normalized_json,fingerprint,status,error_code,error_message,warning_json) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(uid,batchId,row.rowNumber,JSON.stringify(row.raw),norm?JSON.stringify({ ...norm, account:acc, asset }):null,fp,status,status==='invalid'?'validation_error':status==='duplicate'?'duplicate':null,err,JSON.stringify(warns)).run(); if(preview.length<100) preview.push({row_number:row.rowNumber,status,normalized:norm,account:acc,asset,errors:err?[err]:[],warnings:warns,duplicate_reason:status==='duplicate'?err:null}); }
 if(parsed.errors.length) invalid+=parsed.errors.length; await c.env.DB.prepare('UPDATE wealth_import_batches SET valid_rows=?, invalid_rows=?, duplicate_rows=?, status=?, updated_at=datetime(\'now\') WHERE id=?').bind(valid,invalid,dup,invalid?'previewed':'validated',batchId).run(); return c.json({batch_id:batchId,file_name:file.name,file_hash_prefix:fileHash.slice(0,12),total_rows:parsed.rows.length,valid_rows:valid,invalid_rows:invalid,duplicate_rows:dup,warnings:parsed.errors,detected_headers:parsed.headers,mapping:validMap,rows:preview,can_commit:valid>0&&(invalid===0||options.allow_partial),requires_partial_confirmation:invalid>0}); }catch(e:any){ return c.json(bad(e.message),400); }});

route.get('/', async c=>{ const uid=c.get('userId'); const wh=['user_id=?']; const b:any[]=[uid]; const st=c.req.query('status'), from=c.req.query('from'), to=c.req.query('to'); if(st){wh.push('status=?');b.push(st)} if(from){wh.push('created_at>=?');b.push(from)} if(to){wh.push('created_at<=?');b.push(to)} const r=await c.env.DB.prepare(`SELECT id,file_name,substr(file_hash,1,12) file_hash_prefix,source_type,status,total_rows,valid_rows,invalid_rows,duplicate_rows,imported_rows,skipped_rows,failed_rows,created_at,updated_at,committed_at,rolled_back_at,CASE WHEN status IN ('uploaded','previewed','validated','failed') AND COALESCE(imported_rows,0)=0 AND NOT EXISTS (SELECT 1 FROM wealth_import_rows r WHERE r.user_id=wealth_import_batches.user_id AND r.batch_id=wealth_import_batches.id AND (r.created_transaction_id IS NOT NULL OR r.created_price_id IS NOT NULL)) AND NOT EXISTS (SELECT 1 FROM investment_transactions t WHERE t.user_id=wealth_import_batches.user_id AND t.import_batch_id=wealth_import_batches.id) AND NOT EXISTS (SELECT 1 FROM investment_prices p WHERE p.user_id=wealth_import_batches.user_id AND p.import_batch_id=wealth_import_batches.id) THEN 1 ELSE 0 END can_delete FROM wealth_import_batches WHERE ${wh.join(' AND ')} ORDER BY created_at DESC,id DESC`).bind(...b).all(); return c.json(r.results); });
route.get('/:id', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')); const bt=await batch(c,uid,id); if(!bt)return c.json(bad('Not found'),404); const {ps,off}=page(c); const rows=await c.env.DB.prepare('SELECT row_number,status,normalized_json,error_code,error_message,warning_json,created_transaction_id,created_price_id FROM wealth_import_rows WHERE user_id=? AND batch_id=? ORDER BY row_number LIMIT ? OFFSET ?').bind(uid,id,ps,off).all<any>(); const cnt=await c.env.DB.prepare('SELECT COUNT(*) count FROM wealth_import_rows WHERE user_id=? AND batch_id=?').bind(uid,id).first<any>(); const parsedRows=rows.results.map(r=>({...r,normalized:r.normalized_json?JSON.parse(r.normalized_json):null,warnings:r.warning_json?JSON.parse(r.warning_json):[]})); return c.json({batch:{...bt,file_hash:undefined,file_hash_prefix:bt.file_hash.slice(0,12),mapping:JSON.parse(bt.mapping_json||'{}'),options:JSON.parse(bt.options_json||'{}'),can_delete:await canDeleteBatch(c,uid,bt)},row_total:cnt?.count||0,page_size:ps,rows:parsedRows,can_commit:batchCommitEligible(bt,parsedRows),can_rollback:['imported','partially_imported'].includes(bt.status),can_delete:await canDeleteBatch(c,uid,bt)}); });

route.delete('/:id', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')); const bt=await batch(c,uid,id); if(!bt)return c.json(bad('Not found'),404); if(!DELETABLE_STATUSES.includes(bt.status)) return c.json(bad('Only uncommitted preview batches can be deleted'),400); if(Number(bt.imported_rows||0)!==0) return c.json(bad('Batch has imported rows and cannot be deleted'),400); const rows=await c.env.DB.prepare('SELECT COUNT(*) count FROM wealth_import_rows WHERE user_id=? AND batch_id=? AND (created_transaction_id IS NOT NULL OR created_price_id IS NOT NULL)').bind(uid,id).first<any>(); if(Number(rows?.count||0)>0) return c.json(bad('Batch has created financial records and cannot be deleted'),400); const tx=await c.env.DB.prepare('SELECT COUNT(*) count FROM investment_transactions WHERE user_id=? AND import_batch_id=?').bind(uid,id).first<any>(); const prices=await c.env.DB.prepare('SELECT COUNT(*) count FROM investment_prices WHERE user_id=? AND import_batch_id=?').bind(uid,id).first<any>(); if(Number(tx?.count||0)>0||Number(prices?.count||0)>0) return c.json(bad('Batch has created financial records and cannot be deleted'),400); const rowCount=await c.env.DB.prepare('SELECT COUNT(*) count FROM wealth_import_rows WHERE user_id=? AND batch_id=?').bind(uid,id).first<any>(); await c.env.DB.prepare('DELETE FROM wealth_import_rows WHERE user_id=? AND batch_id=?').bind(uid,id).run(); await c.env.DB.prepare('DELETE FROM wealth_import_batches WHERE user_id=? AND id=?').bind(uid,id).run(); return c.json({deleted:true,deleted_rows:Number(rowCount?.count||0)}); });

route.post('/:id/commit', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')); const bt=await batch(c,uid,id); if(!bt)return c.json(bad('Not found'),404); if(!['previewed','validated','partially_imported','imported'].includes(bt.status)) return c.json(bad('Batch cannot be committed'),400); const req=await c.req.json().catch(()=>({})); if(Number(bt.valid_rows ?? bt.total_rows ?? 0)<=0) return c.json(bad('Batch has no valid rows to commit'),400); if(bt.invalid_rows>0 && !req.allow_partial) return c.json(bad('Partial import requires confirmation'),400); const rows=await c.env.DB.prepare(`SELECT * FROM wealth_import_rows WHERE user_id=? AND batch_id=? AND status IN ('valid','duplicate','imported','failed') ORDER BY row_number`).bind(uid,id).all<any>(); if(rows.results.length===0) return c.json(bad('Batch has no committable rows'),400); const retryRows=rows.results.filter(r=>r.status!=='imported' && !(r.status==='duplicate' && req.skip_duplicates!==false)); if(retryRows.some(rowHasCandidateAsset) && !req.create_missing_assets) return c.json(bad('Missing asset creation not allowed'),400); if(!req.import_opening_without_cost_basis && retryRows.some(r=>r.normalized_json && isZeroCostTransferIn(JSON.parse(r.normalized_json)))) return c.json(bad('Opening transfer_in rows without acquisition cost require explicit override; realised gain and XIRR will be inaccurate.'),400); let imported=0, skipped=0, failed=0; const accountMap=new Map<string,any>(), assetMap=new Map<string,any>(); const pending:any[]=[]; const failedIds=new Set<number>();
 for(const r of rows.results){ if(r.status==='imported'){skipped++; continue;} if(r.status==='duplicate' && req.skip_duplicates!==false){ await c.env.DB.prepare('UPDATE wealth_import_rows SET status=\'skipped\' WHERE id=?').bind(r.id).run(); skipped++; continue;} try{ const n=JSON.parse(r.normalized_json); let acc=n.account, asset=n.asset; if(acc.candidate){ const key=candidateKey('account',acc.candidate); acc=accountMap.get(key); if(!acc){ try{ acc=await resolveAccount(c,uid,{...n,account_id:null,account_name:acc.candidate.name,account_type:acc.candidate.account_type,institution:acc.candidate.institution},{}); }catch{} } if(!acc || acc.candidate){ if(!req.create_missing_accounts) throw new Error('Missing account creation not allowed'); const a=n.account.candidate; const ar=await c.env.DB.prepare(`INSERT INTO portfolios (user_id,name,value,account_type,institution,currency,valuation_mode) VALUES (?,?,?,?,?,?,?)`).bind(uid,a.name,0,a.account_type,a.institution,a.currency,'holdings').run(); acc={id:ar.meta.last_row_id,name:a.name,account_type:a.account_type}; } accountMap.set(key,acc); }
 if(asset.candidate){ const key=candidateKey('asset',asset.candidate); asset=assetMap.get(key); if(!asset){ try{ asset=await resolveAsset(c,uid,{...n,...asset.candidate}); }catch{} } if(!asset || asset.candidate){ if(!req.create_missing_assets) throw new Error('Missing asset creation not allowed'); const a=n.asset.candidate; const ar=await c.env.DB.prepare(`INSERT INTO investment_assets (user_id,name,asset_type,symbol,isin,exchange,scheme_code,currency,price_source,pricing_mode) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(uid,a.name,a.asset_type,a.symbol,a.isin,a.exchange,a.scheme_code,a.currency,'import','manual').run(); asset={id:ar.meta.last_row_id,name:a.name,asset_type:a.asset_type}; } assetMap.set(key,asset); }
 await validateMovement(c,uid,n.movement_id); pending.push({...r,n,acc,asset}); }catch(e:any){ failed++; failedIds.add(r.id); await c.env.DB.prepare('UPDATE wealth_import_rows SET status=\'failed\', error_code=\'commit_error\', error_message=? WHERE id=?').bind(e.message,r.id).run(); } }
 const txPending=pending.filter(p=>p.n.transaction_type); const groups=new Map<string,any[]>(); for(const p of txPending){ const tx={...txFrom(p.n,p.acc.id,p.asset.id),__seq:p.row_number??p.id}; const key=`${p.acc.id}:${p.asset.id}`; if(!groups.has(key)) groups.set(key,[]); groups.get(key)!.push({...p,tx}); }
 for(const [key,items] of groups){ try{ const [accId,assetId]=key.split(':').map(Number); const extras=items.map(i=>i.tx).sort((a,b)=>a.trade_date.localeCompare(b.trade_date)||((a.__seq??0)-(b.__seq??0))); validateNoOversell(await existingSeq(c,uid,accId,assetId,extras)); }catch(e:any){ for(const i of items){ failed++; failedIds.add(i.id); await c.env.DB.prepare('UPDATE wealth_import_rows SET status=\'failed\', error_code=\'commit_error\', error_message=? WHERE id=?').bind(e.message,i.id).run(); } } }
 for(const p of pending.sort(sortRowsForCommit)){ if(failedIds.has(p.id)) continue; try{ const n=p.n, acc=p.acc, asset=p.asset; if(n.transaction_type){ const tx=txFrom(n,acc.id,asset.id); const f=Object.keys(tx); const ir=await c.env.DB.prepare(`INSERT INTO investment_transactions (user_id,${f.join(',')},import_batch_id) VALUES (?,${f.map(()=>'?').join(',')},?)`).bind(uid,...f.map(k=>(tx as any)[k]),id).run(); await c.env.DB.prepare('UPDATE wealth_import_rows SET status=\'imported\', created_account_id=?, created_asset_id=?, created_transaction_id=? WHERE id=?').bind(acc.id,asset.id,ir.meta.last_row_id,p.id).run(); }
 if(n.price && n.price_date){ const pr=await c.env.DB.prepare(`INSERT INTO investment_prices (user_id,asset_id,price_date,price,currency,source,notes,import_batch_id) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(user_id,asset_id,price_date) DO UPDATE SET price=excluded.price,currency=excluded.currency,source=excluded.source,notes=excluded.notes,import_batch_id=excluded.import_batch_id,updated_at=datetime('now') RETURNING id`).bind(uid,asset.id,n.price_date,n.price,n.currency,n.price_source||'import',n.notes,id).first<any>(); await c.env.DB.prepare('UPDATE wealth_import_rows SET created_price_id=COALESCE(?,created_price_id), status=\'imported\' WHERE id=?').bind(pr?.id,p.id).run(); }
 imported++; }catch(e:any){ failed++; failedIds.add(p.id); await c.env.DB.prepare('UPDATE wealth_import_rows SET status=\'failed\', error_code=\'commit_error\', error_message=? WHERE id=?').bind(e.message,p.id).run(); } }
 const status=failed?'partially_imported':'imported'; await c.env.DB.prepare(`UPDATE wealth_import_batches SET imported_rows=(SELECT COUNT(*) FROM wealth_import_rows WHERE user_id=? AND batch_id=? AND status='imported'),skipped_rows=(SELECT COUNT(*) FROM wealth_import_rows WHERE user_id=? AND batch_id=? AND status='skipped'),failed_rows=(SELECT COUNT(*) FROM wealth_import_rows WHERE user_id=? AND batch_id=? AND status='failed'),status=?,committed_at=COALESCE(committed_at,datetime('now')),updated_at=datetime('now') WHERE id=?`).bind(uid,id,uid,id,uid,id,status,id).run(); return c.json({imported_rows:imported,skipped_rows:skipped,failed_rows:failed,warnings:failed?['Some rows failed; retry is idempotent by row status.']:[]}); });

route.post('/:id/rollback', async c=>{ const uid=c.get('userId'), id=Number(c.req.param('id')); const bt=await batch(c,uid,id); if(!bt)return c.json(bad('Not found'),404); if(bt.status==='rolled_back') return c.json({deleted_transactions:0,deleted_prices:0,preserved_accounts:[],preserved_assets:[],warnings:['Batch already rolled back']}); if(!['imported','partially_imported'].includes(bt.status)) return c.json(bad('Batch cannot be rolled back'),400); const later=await c.env.DB.prepare(`SELECT COUNT(*) count FROM investment_transactions t WHERE t.user_id=? AND t.import_batch_id<>? AND EXISTS (SELECT 1 FROM investment_transactions x WHERE x.import_batch_id=? AND x.user_id=t.user_id AND x.account_id=t.account_id AND x.asset_id=t.asset_id AND t.trade_date>=x.trade_date)`).bind(uid,id,id).first<any>(); if(later?.count) return c.json(bad('Rollback would affect later non-imported sequence'),400); const pr=await c.env.DB.prepare('DELETE FROM investment_prices WHERE user_id=? AND import_batch_id=?').bind(uid,id).run(); const tr=await c.env.DB.prepare('DELETE FROM investment_transactions WHERE user_id=? AND import_batch_id=?').bind(uid,id).run(); await c.env.DB.prepare('UPDATE wealth_import_rows SET status=\'rolled_back\' WHERE user_id=? AND batch_id=? AND status IN (\'imported\',\'failed\',\'skipped\')').bind(uid,id).run(); await c.env.DB.prepare('UPDATE wealth_import_batches SET status=\'rolled_back\', rolled_back_at=datetime(\'now\'), updated_at=datetime(\'now\') WHERE id=?').bind(id).run(); return c.json({deleted_transactions:(tr.meta as any).changes||0,deleted_prices:(pr.meta as any).changes||0,preserved_accounts:[],preserved_assets:[],warnings:['Accounts and assets created during import are preserved.']}); });
export default route;
