import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { calculateHolding } from '../wealth/formulas';
import { summarizePerformance, type Tx } from '../wealth/performance';
import { isValidXirrDate } from '../wealth/xirr';

const route = new Hono<{ Bindings: Bindings; Variables: Variables }>();
const bad=(error:string)=>({error}); const today=()=>new Date().toISOString().slice(0,10);
const finite=(n:any)=>Number.isFinite(Number(n));
const num=(n:any)=>finite(n)?Number(n):0;
function isOpen(q:string){ return Number(q||0)!==0; }
function clean<T>(v:T):T{ if(Array.isArray(v)) return v.map(clean) as T; if(v&&typeof v==='object'){ const o:any={}; for(const [k,val] of Object.entries(v as any)) o[k]=clean(val as any); return o; } return (typeof v==='number'&&!Number.isFinite(v)?null:v) as T; }
function holdingStatus(h:any){ if(h.current_value==null) return 'missing_price'; if(h.stale_price) return 'stale'; return 'priced'; }
function msgHealth(open:number, priced:number, missing:number, stale:number){ const m:string[]=[]; if(open===0)m.push('No open holdings to value.'); else if(missing===0)m.push(`${priced} of ${open} open holdings have prices.`); if(missing>0)m.push(`${missing} open holdings are missing prices.`); if(stale>0)m.push(`${stale} prices are older than the configured stale threshold.`); if(missing>0)m.push('Portfolio value is partial because some holdings are unpriced.'); return m; }
function pct(part:number, total:number){ return total>0 ? part/total*100 : null; }
function sortHoldings(key:string, dir=1){ return (a:any,b:any)=> dir*((num(a[key])-num(b[key])) || String(a.asset_name).localeCompare(String(b.asset_name)) || String(a.account_name).localeCompare(String(b.account_name)) || (a.asset_id-b.asset_id) || (a.account_id-b.account_id)); }
function alloc(rows:any[], key:(h:any)=>string, name:(h:any)=>string){ const m=new Map<string,any>(); for(const h of rows){ const k=key(h); const r=m.get(k)||{name:name(h), current_value:0, invested_value:0, unpriced_count:0, holding_count:0}; r.holding_count++; r.invested_value+=h.cost_basis; if(h.current_value==null) r.unpriced_count++; else r.current_value+=h.current_value; m.set(k,r); } return [...m.values()]; }

async function load(c:any, uid:number, asOf:string, accountId?:number){
 const wh=['t.user_id=?','t.trade_date<=?','p.is_active<>0','p.include_in_net_worth<>0']; const b:any[]=[uid,asOf];
 if(accountId){ wh.push('t.account_id=?'); b.push(accountId); }
 const tx=await c.env.DB.prepare(`SELECT t.*, p.name account_name, p.account_type, p.institution, p.valuation_mode, a.name asset_name, a.asset_type, a.symbol, a.pricing_mode FROM investment_transactions t JOIN portfolios p ON p.id=t.account_id AND p.user_id=t.user_id LEFT JOIN investment_assets a ON a.id=t.asset_id AND a.user_id=t.user_id WHERE ${wh.join(' AND ')} ORDER BY t.trade_date,t.id`).bind(...b).all<any>();
 const prices=await c.env.DB.prepare('SELECT pr.* FROM investment_prices pr WHERE pr.user_id=? AND pr.price_date<=? ORDER BY pr.price_date DESC, pr.id DESC').bind(uid,asOf).all<any>();
 const active=await c.env.DB.prepare('SELECT COUNT(*) count FROM portfolios WHERE user_id=? AND is_active<>0 AND include_in_net_worth<>0').bind(uid).first<any>();
 return {tx:tx.results, prices:prices.results, active_accounts:Number(active?.count||0)};
}

route.get('/', async c=>{ const uid=c.get('userId'); const asOf=c.req.query('as_of')??today(); if(!isValidXirrDate(asOf)) return c.json(bad('Invalid as_of'),400); const accountId=c.req.query('account_id')?Number(c.req.query('account_id')):undefined; if(accountId&&!await c.env.DB.prepare('SELECT id FROM portfolios WHERE id=? AND user_id=?').bind(accountId,uid).first()) return c.json(bad('Not found'),404);
 const {tx,prices,active_accounts}=await load(c,uid,asOf,accountId); const groups=new Map<string,any[]>(); for(const t of tx.filter((r:any)=>r.asset_id&&r.valuation_mode!=='manual_snapshot')) groups.set(`${t.account_id}:${t.asset_id}`,[...(groups.get(`${t.account_id}:${t.asset_id}`)||[]),t]);
 const holdings:any[]=[]; const rawWarnings:string[]=[]; let totalInvested=0,currentValue=0,realised=0,unreal=0,totalGain=0, pricedAssets=0, missing=0, stale=0, latest:string|null=null, oldest:string|null=null;
 for(const txs of groups.values()){ const f=txs[0]; const ps=prices.filter((p:any)=>p.asset_id===f.asset_id); const h=calculateHolding(txs,ps,{asOf,assetType:f.asset_type,pricingMode:f.pricing_mode}); if(!isOpen(h.quantity)) continue; rawWarnings.push(...h.warnings); const row={account_id:f.account_id,account:f.account_name,account_name:f.account_name,institution:f.institution||'Unspecified',asset_id:f.asset_id,asset_name:f.asset_name,symbol:f.symbol,asset_type:f.asset_type,quantity:h.quantity,cost_basis:h.remaining_cost_basis,current_value:h.current_value,realised_gain:h.realised_gain,unrealised_gain:h.unrealised_gain,total_gain:h.total_gain,absolute_return_percent:h.absolute_return_pct,latest_price:h.latest_price,price_date:h.latest_price_date,price_source:ps[0]?.source||null,valuation_status:holdingStatus(h)}; holdings.push(row); totalInvested+=h.remaining_cost_basis; realised+=h.realised_gain; if(h.current_value==null) missing++; else { currentValue+=h.current_value; pricedAssets++; unreal+=h.unrealised_gain??0; totalGain+=h.total_gain??h.realised_gain; } if(h.stale_price) stale++; if(h.latest_price_date){ if(!latest||h.latest_price_date>latest) latest=h.latest_price_date; if(!oldest||h.latest_price_date<oldest) oldest=h.latest_price_date; } }
 const valuationComplete=missing===0; const perf=summarizePerformance({scope:'portfolio',scopeId:'portfolio',valuationDate:asOf,transactions:tx as Tx[],currentValue,appendTerminal:currentValue>0,extraWarnings:valuationComplete?[]:['incomplete_valuation_missing_price']});
 const gainRows=holdings.filter(h=>h.current_value!=null); const positive=holdings.filter(h=>(h.total_gain??0)>0).length, negative=holdings.filter(h=>(h.total_gain??0)<0).length;
 const pricedDen=currentValue, investedDen=totalInvested; const addPct=(a:any[])=>a.sort((x,y)=>y.current_value-x.current_value||x.name.localeCompare(y.name)).map(x=>({...x,percentage_of_priced_portfolio:pct(x.current_value,pricedDen),percentage_of_total_invested_portfolio:pct(x.invested_value,investedDen),valuation_complete:x.unpriced_count===0}));
 const allocations={asset:addPct(alloc(holdings,h=>String(h.asset_id),h=>h.asset_name)),account:addPct(alloc(holdings,h=>String(h.account_id),h=>h.account_name)),asset_type:addPct(alloc(holdings,h=>h.asset_type||'other',h=>h.asset_type||'other')),institution:addPct(alloc(holdings,h=>h.institution||'Unspecified',h=>h.institution||'Unspecified')),unpriced_assets:holdings.filter(h=>h.current_value==null)};
 const recent=(await c.env.DB.prepare(`SELECT t.id,t.trade_date,t.transaction_type,t.quantity,t.gross_amount,t.net_amount,p.name account,a.name asset_name,a.symbol FROM investment_transactions t JOIN portfolios p ON p.id=t.account_id AND p.user_id=t.user_id LEFT JOIN investment_assets a ON a.id=t.asset_id AND a.user_id=t.user_id WHERE t.user_id=? ${accountId?'AND t.account_id=?':''} ORDER BY t.trade_date DESC,t.id DESC LIMIT 10`).bind(uid,...(accountId?[accountId]:[])).all<any>()).results;
 const healthStatus=holdings.length===0?'unavailable':missing>0?'partial':stale>0?'stale':'complete';
 const summary={valuation_date:asOf,total_invested:totalInvested,current_value:currentValue,realised_gain:realised,unrealised_gain:valuationComplete?unreal:null,total_gain:valuationComplete?totalGain:realised+unreal,absolute_return_percent:totalInvested?((valuationComplete?totalGain:realised+unreal)/totalInvested)*100:null,xirr:perf.xirr,xirr_status:perf.xirr_status,active_accounts,open_holdings:holdings.length,priced_assets:pricedAssets,missing_price_assets:missing,stale_price_assets:stale,valuation_complete:valuationComplete,warnings:[]};
 const valuation_health={status:healthStatus,priced_assets:pricedAssets,total_open_assets:holdings.length,missing_assets:missing,stale_assets:stale,latest_valuation_date:latest,oldest_price_date:oldest,messages:msgHealth(holdings.length,pricedAssets,missing,stale)};
 const response={summary,valuation_health,top_gainers:gainRows.filter(h=>(h.total_gain??0)>0).sort(sortHoldings('total_gain',-1)).slice(0,5),top_losers:gainRows.filter(h=>(h.total_gain??0)<0).sort(sortHoldings('total_gain',1)).slice(0,5),largest_holdings:gainRows.sort(sortHoldings('current_value',-1)).slice(0,5),largest_cost_allocations:holdings.sort(sortHoldings('cost_basis',-1)).slice(0,5),realised_gain_contributors:holdings.filter(h=>h.realised_gain!==0).sort(sortHoldings('realised_gain',-1)).slice(0,5),missing_price_holdings:holdings.filter(h=>h.valuation_status==='missing_price'),stale_price_holdings:holdings.filter(h=>h.valuation_status==='stale'),allocations,gain_loss:{realised_gain:realised,unrealised_gain:valuationComplete?unreal:null,total_gain:valuationComplete?totalGain:realised+unreal,positive_holdings_count:positive,negative_holdings_count:negative,flat_holdings_count:holdings.length-positive-negative-missing,unpriced_holdings_count:missing},recent_transactions:recent,warnings:[...new Set(rawWarnings)]};
 return c.json(clean(response)); });
export default route;
