import { Hono } from 'hono';
import type { AppContext, Bindings, Variables } from '../types';
import { isDateOnly, isEnumValue, optionalText } from '../wealth/validation';
import { parseDecimal, formatDecimal, multiplyQuantityByPriceMinor } from '../wealth/decimal';
import { validateNoOversell, type InvestmentTransactionInput } from '../wealth/formulas';

const route = new Hono<{ Bindings: Bindings; Variables: Variables }>();
const TYPES = ['buy','sell','sip','redemption','dividend','interest','contribution','withdrawal','transfer_in','transfer_out','bonus','split','charges','maturity'] as const;
const needAsset = new Set(['buy','sell','sip','redemption','dividend','transfer_in','transfer_out','bonus','split']);
const needQty = new Set(['buy','sell','sip','redemption','transfer_in','transfer_out','bonus','split']);
function bad(error: string) { return { error }; }
function money(v: any, name: string, def: number | null = null) { if (v == null || v === '') return def; const n = Number(v); if (!Number.isInteger(n) || n < 0) throw new Error(`Invalid ${name}`); return n; }
function dec(v: any, positive = false) { if (v == null || v === '') return null; const x = parseDecimal(v, { allowZero: !positive }); return formatDecimal(x); }
async function account(c: AppContext, uid: number, id: number) { return c.env.DB.prepare('SELECT id, is_active FROM portfolios WHERE id=? AND user_id=?').bind(id, uid).first<any>(); }
async function asset(c: AppContext, uid: number, id: number) { return c.env.DB.prepare('SELECT id, is_active FROM investment_assets WHERE id=? AND user_id=?').bind(id, uid).first<any>(); }
async function seq(c: AppContext, uid: number, accountId: number, assetId: number | null, replace?: any, removeId?: number) { const rows = await c.env.DB.prepare('SELECT * FROM investment_transactions WHERE user_id=? AND account_id=? AND asset_id=? ORDER BY trade_date, id').bind(uid, accountId, assetId).all<any>(); return rows.results.filter(r => r.id !== removeId).map(r => replace && r.id === replace.id ? replace : r).concat(replace && !replace.id ? [replace] : []); }
async function normalize(c: AppContext, uid: number, body: any, existing?: any) {
  const v: any = { ...existing, ...body };
  if (!Number.isInteger(Number(v.account_id))) throw new Error('Invalid account_id'); const acc = await account(c, uid, Number(v.account_id)); if (!acc) throw new Error('Invalid account ownership'); if (!acc.is_active) throw new Error('Inactive account');
  if (!isEnumValue(TYPES, v.transaction_type)) throw new Error('Invalid transaction_type'); if (!isDateOnly(v.trade_date) || !v.trade_date) throw new Error('Invalid trade_date'); if (v.settlement_date && !isDateOnly(v.settlement_date)) throw new Error('Invalid settlement_date');
  const aid = v.asset_id == null || v.asset_id === '' ? null : Number(v.asset_id); if (needAsset.has(v.transaction_type) && !aid) throw new Error('Asset required'); let ast:any=null; if (aid) { ast = await asset(c, uid, aid); if (!ast) throw new Error('Invalid asset ownership'); if (!ast.is_active && ['buy','sip','contribution'].includes(v.transaction_type)) throw new Error('Inactive asset'); }
  if (v.movement_id) { const m = await c.env.DB.prepare('SELECT id FROM movements WHERE id=? AND user_id=?').bind(Number(v.movement_id), uid).first(); if (!m) throw new Error('Invalid movement ownership'); }
  const quantity = dec(v.quantity, needQty.has(v.transaction_type)); const unit_price = dec(v.unit_price, false); const charges = money(v.charges, 'charges', 0)!; const taxes = money(v.taxes, 'taxes', 0)!; let gross_amount = money(v.gross_amount, 'gross_amount'); let net_amount = money(v.net_amount, 'net_amount');
  if ((v.transaction_type === 'buy' || v.transaction_type === 'sip') && gross_amount == null && quantity && unit_price) gross_amount = multiplyQuantityByPriceMinor(quantity, unit_price);
  if ((v.transaction_type === 'buy' || v.transaction_type === 'sip') && net_amount == null && gross_amount != null) net_amount = gross_amount + charges + taxes;
  if (['buy','sip'].includes(v.transaction_type) && gross_amount == null && unit_price == null) throw new Error('unit_price or gross_amount required');
  if (['sell','redemption'].includes(v.transaction_type) && gross_amount == null && net_amount == null) throw new Error('net_amount or gross_amount required');
  if (['dividend','interest','contribution','withdrawal','maturity'].includes(v.transaction_type) && gross_amount == null && net_amount == null) throw new Error('Amount required');
  if (v.transaction_type === 'charges' && charges === 0 && net_amount == null) throw new Error('Charges required');
  return { account_id:Number(v.account_id), asset_id:aid, transaction_type:v.transaction_type, trade_date:v.trade_date, settlement_date:optionalText(v.settlement_date), quantity, unit_price, gross_amount, charges, taxes, net_amount, movement_id:v.movement_id?Number(v.movement_id):null, external_ref:optionalText(v.external_ref), notes:optionalText(v.notes) };
}
route.get('/', async c => { const uid=c.get('userId'); const wh=['t.user_id=?']; const b:any[]=[uid]; for (const [q,f] of [['account_id','t.account_id'],['asset_id','t.asset_id'],['transaction_type','t.transaction_type']] as any) { const v=c.req.query(q); if(v){wh.push(`${f}=?`); b.push(v);} } const from=c.req.query('from'), to=c.req.query('to'), q=c.req.query('q'); if(from){wh.push('t.trade_date>=?');b.push(from)} if(to){wh.push('t.trade_date<=?');b.push(to)} if(q){wh.push('(t.external_ref LIKE ? OR t.notes LIKE ? OR a.name LIKE ?)');b.push(`%${q}%`,`%${q}%`,`%${q}%`)} const r=await c.env.DB.prepare(`SELECT t.*, p.name account_name, a.name asset_name, a.asset_type, m.date movement_date, m.amount movement_amount FROM investment_transactions t JOIN portfolios p ON p.id=t.account_id LEFT JOIN investment_assets a ON a.id=t.asset_id LEFT JOIN movements m ON m.id=t.movement_id WHERE ${wh.join(' AND ')} ORDER BY t.trade_date DESC, t.id DESC`).bind(...b).all(); return c.json(r.results); });
route.post('/', async c => { const uid=c.get('userId'); try { const v=await normalize(c, uid, await c.req.json()); if(v.asset_id) validateNoOversell(await seq(c, uid, v.account_id, v.asset_id, v)); const f=Object.keys(v); const r=await c.env.DB.prepare(`INSERT INTO investment_transactions (user_id, ${f.join(',')}) VALUES (?, ${f.map(()=>'?').join(',')})`).bind(uid,...f.map(k=>v[k])).run(); return c.json({id:r.meta.last_row_id},201);} catch(e:any){return c.json(bad(e.message),400)} });
route.put('/:id', async c => { const uid=c.get('userId'), id=Number(c.req.param('id')); const ex=await c.env.DB.prepare('SELECT * FROM investment_transactions WHERE id=? AND user_id=?').bind(id,uid).first<any>(); if(!ex)return c.json(bad('Not found'),404); try{const v=await normalize(c,uid,await c.req.json(),ex); const rep={...v,id}; if(v.asset_id) validateNoOversell(await seq(c,uid,v.account_id,v.asset_id,rep)); const f=Object.keys(v); await c.env.DB.prepare(`UPDATE investment_transactions SET ${f.map(k=>`${k}=?`).join(', ')}, updated_at=datetime('now') WHERE id=? AND user_id=?`).bind(...f.map(k=>v[k]),id,uid).run(); return c.json({success:true});}catch(e:any){return c.json(bad(e.message),400)} });
route.delete('/:id', async c => { const uid=c.get('userId'), id=Number(c.req.param('id')); const ex=await c.env.DB.prepare('SELECT * FROM investment_transactions WHERE id=? AND user_id=?').bind(id,uid).first<any>(); if(!ex)return c.json(bad('Not found'),404); try{ if(ex.asset_id) validateNoOversell(await seq(c,uid,ex.account_id,ex.asset_id,undefined,id)); await c.env.DB.prepare('DELETE FROM investment_transactions WHERE id=? AND user_id=?').bind(id,uid).run(); return c.json({success:true});}catch(e:any){return c.json(bad(e.message),400)} });
export default route;
