import { Hono } from 'hono';
import type { Bindings, Variables, AppContext } from '../types';
import { isDateOnly, normalizeCurrency, isEnumValue, optionalText } from '../wealth/validation';
import { parseDecimal, formatDecimal } from '../wealth/decimal';
import { refreshIndianMarketPrices, refreshHistory } from '../wealth/indian-market-refresh';
const route=new Hono<{Bindings:Bindings;Variables:Variables}>(); const bad=(m:string)=>({error:m}); const SOURCES=['manual','import','market','nav','snapshot'];
async function ownAsset(c:AppContext,uid:number,id:number){return !!await c.env.DB.prepare('SELECT id FROM investment_assets WHERE user_id=? AND id=?').bind(uid,id).first();}
route.get('/', async c=>{const uid=c.get('userId'); const wh=['p.user_id=?']; const b:any[]=[uid]; for(const [q,f] of [['asset_id','p.asset_id'],['source','p.source']] as any){const v=c.req.query(q); if(v){wh.push(`${f}=?`); b.push(v)}} const from=c.req.query('from'),to=c.req.query('to'); if(from){wh.push('p.price_date>=?');b.push(from)} if(to){wh.push('p.price_date<=?');b.push(to)} const r=await c.env.DB.prepare(`SELECT p.*, a.name asset_name, a.symbol, a.exchange, (SELECT pp.price FROM investment_prices pp WHERE pp.user_id=p.user_id AND pp.asset_id=p.asset_id AND (pp.price_date<p.price_date OR (pp.price_date=p.price_date AND pp.id<p.id)) ORDER BY pp.price_date DESC, pp.id DESC LIMIT 1) previous_price, (SELECT pp.price_date FROM investment_prices pp WHERE pp.user_id=p.user_id AND pp.asset_id=p.asset_id AND (pp.price_date<p.price_date OR (pp.price_date=p.price_date AND pp.id<p.id)) ORDER BY pp.price_date DESC, pp.id DESC LIMIT 1) previous_price_date FROM investment_prices p LEFT JOIN investment_assets a ON a.id=p.asset_id WHERE ${wh.join(' AND ')} ORDER BY p.price_date DESC, p.id DESC`).bind(...b).all(); return c.json(r.results);});
route.post('/', async c=>{const uid=c.get('userId'); try{const body=await c.req.json(); const aid=Number(body.asset_id); if(!aid||!await ownAsset(c as any,uid,aid)) throw new Error('Invalid asset ownership'); if(!isDateOnly(body.price_date)||!body.price_date) throw new Error('Invalid price_date'); if(body.price_date>new Date().toISOString().slice(0,10)) throw new Error('Future price_date is not allowed'); const price=formatDecimal(parseDecimal(body.price,{allowZero:false})); const currency=normalizeCurrency(body.currency); if(!currency) throw new Error('Invalid currency'); const source=body.source??'manual'; if(!isEnumValue(SOURCES,source)) throw new Error('Invalid source'); const notes=optionalText(body.notes); const r=await c.env.DB.prepare(`INSERT INTO investment_prices (user_id,asset_id,price_date,price,currency,source,notes) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,asset_id,price_date) DO UPDATE SET price=excluded.price,currency=excluded.currency,source=excluded.source,notes=excluded.notes,updated_at=datetime('now') RETURNING id`).bind(uid,aid,body.price_date,price,currency,source,notes).first<any>(); return c.json({id:r?.id,success:true},201);}catch(e:any){return c.json(bad(e.message),400)}});
route.post('/refresh', async c=>{ try{ const b=await c.req.json().catch(()=>({})); const out=await refreshIndianMarketPrices(c as any,{scope:b.scope,assetIds:b.assetIds||b.asset_ids,force:b.force===true,trigger:'manual',targetDate:b.targetDate||b.target_date}); return c.json(out,200 as any); }catch(e:any){const msg=e.message||'Refresh failed'; return c.json(bad(msg),msg.includes('cooldown')?429:400)} });
route.get('/refresh-history', async c=>c.json(await refreshHistory(c as any)));
route.get('/refresh-history/:batchId', async c=>{ const r=await refreshHistory(c as any,Number(c.req.param('batchId'))); return r?c.json(r):c.json(bad('Not found'),404); });
route.delete('/:id', async c=>{const uid=c.get('userId'), id=Number(c.req.param('id')); const r=await c.env.DB.prepare('DELETE FROM investment_prices WHERE id=? AND user_id=?').bind(id,uid).run(); if((r.meta as any).changes===0)return c.json(bad('Not found'),404); return c.json({success:true});});
export default route;
