import { Hono } from 'hono';
import type { Bindings, Variables } from '../types';
import { ASSET_TYPES } from '../wealth/types';
import { isEnumValue, parseQueryBoolean } from '../wealth/validation';
import { isValidXirrDate, combineSameDateCashFlows } from '../wealth/xirr';
import { holdingFor, summarizePerformance } from '../wealth/performance';
const route = new Hono<{ Bindings: Bindings; Variables: Variables }>();
const bad=(error:string)=>({error}); const today=()=>new Date().toISOString().slice(0,10);
async function load(c:any, uid:number, asOf:string, filters:any={}){ const wh=['t.user_id=?','t.trade_date<=?']; const b:any[]=[uid,asOf]; if(filters.account_id){wh.push('t.account_id=?');b.push(filters.account_id)} if(filters.asset_id){wh.push('t.asset_id=?');b.push(filters.asset_id)} if(filters.asset_type){wh.push('a.asset_type=?');b.push(filters.asset_type)}
 const tx=await c.env.DB.prepare(`SELECT t.*, p.name account_name, p.valuation_mode, a.name asset_name, a.asset_type, a.symbol, a.pricing_mode FROM investment_transactions t JOIN portfolios p ON p.id=t.account_id AND p.user_id=t.user_id LEFT JOIN investment_assets a ON a.id=t.asset_id AND a.user_id=t.user_id WHERE ${wh.join(' AND ')} ORDER BY t.trade_date, t.id`).bind(...b).all<any>();
 const prices=await c.env.DB.prepare('SELECT pr.* FROM investment_prices pr JOIN investment_assets a ON a.id=pr.asset_id WHERE pr.user_id=? AND pr.price_date<=? ORDER BY pr.price_date DESC, pr.id DESC').bind(uid,asOf).all<any>();
 return {tx:tx.results, prices:prices.results}; }
function groups(rows:any[], key:(r:any)=>string){ const m=new Map<string,any[]>(); for(const r of rows){ const k=key(r); if(k) m.set(k,[...(m.get(k)??[]),r]); } return [...m.values()]; }
function assetSummary(txs:any[], prices:any[], asOf:string, includeClosed:boolean, debug=false){ const first=txs[0]; const ps=prices.filter((p:any)=>p.asset_id===first.asset_id); const h=holdingFor(txs,ps,asOf); if(!includeClosed&&h.quantity==='0') return null; return summarizePerformance({scope:'asset',scopeId:first.asset_id,valuationDate:asOf,transactions:txs,holding:h,currentValue:h.quantity==='0'?0:h.current_value,appendTerminal:h.quantity!=='0',debug}); }
function aggregate(scope:string, id:any, asOf:string, txs:any[], prices:any[], includeClosed:boolean, debug=false){ const warnings:string[]=[]; let current=0, cvComplete=true, realised=0, unreal=0, total=0; const flowsTx=txs; for(const g of groups(txs.filter(t=>t.asset_id&&t.valuation_mode!=='manual_snapshot'), r=>`${r.account_id}:${r.asset_id}`)){ const h=holdingFor(g,prices.filter((p:any)=>p.asset_id===g[0].asset_id),asOf); if(!includeClosed&&h.quantity==='0') continue; warnings.push(...h.warnings); realised+=h.realised_gain; unreal+=h.unrealised_gain??0; total+=h.total_gain??h.realised_gain; if(h.quantity!=='0'){ if(h.current_value==null) cvComplete=false; else current+=h.current_value; } }
 if(!cvComplete) warnings.push('incomplete_valuation_missing_price'); const s=summarizePerformance({scope,scopeId:id,valuationDate:asOf,transactions:flowsTx,currentValue:cvComplete?current:null,appendTerminal:current>0||!cvComplete,extraWarnings:warnings,debug}); s.realised_gain=realised; s.unrealised_gain=cvComplete?unreal:null; s.total_gain=cvComplete?total:null; s.current_value=cvComplete?current:null; s.valuation_complete=cvComplete&&!s.warnings.some(w=>w.includes('missing_price')); return s; }
async function manualSnapshots(c:any, uid:number, asOf:string, accountIds:number[]){ if(!accountIds.length) return new Map<number,number>(); const out=new Map<number,number>(); for(const id of accountIds){ const row=await c.env.DB.prepare("SELECT amount FROM balance_history WHERE user_id=? AND entity_kind='portfolio' AND entity_id=? AND date(recorded_at)<=? ORDER BY recorded_at DESC LIMIT 1").bind(uid,id,asOf).first<any>(); if(row) out.set(id,row.amount); } return out; }
async function movementFallback(c:any, uid:number, asOf:string, accountId:number){ const rows=await c.env.DB.prepare("SELECT * FROM movements WHERE user_id=? AND date<=? AND ((dst_kind='portfolio' AND dst_id=?) OR (src_kind='portfolio' AND src_id=?)) ORDER BY date,id").bind(uid,asOf,accountId,accountId).all<any>(); return rows.results.map((m:any)=>({account_id:accountId,trade_date:m.date,transaction_type:(m.dst_kind==='portfolio'?'contribution':'withdrawal'),gross_amount:m.amount,net_amount:m.amount})); }
route.get('/', async c=>{ const uid=c.get('userId'); const scope=c.req.query('scope')??'portfolio'; const asOf=c.req.query('as_of')??today(); const debug=parseQueryBoolean(c.req.query('debug')??null)===true; const includeClosed=parseQueryBoolean(c.req.query('include_closed')??null)!==false; if(!['portfolio','account','asset','asset_type'].includes(scope)) return c.json(bad('Invalid scope'),400); if(!isValidXirrDate(asOf)) return c.json(bad('Invalid as_of'),400); const account_id=c.req.query('account_id')?Number(c.req.query('account_id')):undefined; const asset_id=c.req.query('asset_id')?Number(c.req.query('asset_id')):undefined; const asset_type=c.req.query('asset_type'); if(scope==='account'&&!account_id) return c.json(bad('account_id required'),400); if(scope==='asset'&&!asset_id) return c.json(bad('asset_id required'),400); if(scope==='asset_type'&&(!asset_type||!isEnumValue(ASSET_TYPES,asset_type))) return c.json(bad('Valid asset_type required'),400);
 if(account_id&&!await c.env.DB.prepare('SELECT id FROM portfolios WHERE id=? AND user_id=?').bind(account_id,uid).first()) return c.json(bad('Not found'),404); if(asset_id&&!await c.env.DB.prepare('SELECT id FROM investment_assets WHERE id=? AND user_id=?').bind(asset_id,uid).first()) return c.json(bad('Not found'),404);
 const {tx,prices}=await load(c,uid,asOf,{account_id:scope==='account'?account_id:undefined,asset_id:scope==='asset'?asset_id:undefined,asset_type:scope==='asset_type'?asset_type:undefined});
 if(scope==='asset'){ const s=tx.length?assetSummary(tx,prices,asOf,includeClosed,debug):summarizePerformance({scope:'asset',scopeId:asset_id,valuationDate:asOf,transactions:[],currentValue:0,appendTerminal:false,debug}); return c.json({asset:s, cash_flows:debug?s.debug?.cash_flows:combineSameDateCashFlows([]), warnings:s?.warnings??[]}); }
 if(scope==='account'){ let s=aggregate('account',account_id,asOf,tx,prices,includeClosed,debug); const acct=await c.env.DB.prepare('SELECT valuation_mode FROM portfolios WHERE id=? AND user_id=?').bind(account_id,uid).first<any>(); if(acct?.valuation_mode==='manual_snapshot'){ const snap=await manualSnapshots(c,uid,asOf,[account_id!]); if(!tx.length) s=summarizePerformance({scope:'account',scopeId:account_id,valuationDate:asOf,transactions:await movementFallback(c,uid,asOf,account_id!),currentValue:snap.get(account_id!)??null,appendTerminal:true,extraWarnings:['manual_snapshot_movement_fallback'],debug}); else s.current_value=snap.get(account_id!)??s.current_value; }
 const assets=groups(tx.filter(t=>t.asset_id),r=>`${r.account_id}:${r.asset_id}`).map(g=>assetSummary(g,prices,asOf,includeClosed,debug)).filter(Boolean); return c.json({account:s, assets, warnings:s.warnings}); }
 if(scope==='asset_type'){ const s=aggregate('asset_type',asset_type,asOf,tx,prices,includeClosed,debug); return c.json({grouped:s, included_account_ids:[...new Set(tx.map(t=>t.account_id))], included_asset_ids:[...new Set(tx.map(t=>t.asset_id).filter(Boolean))], warnings:s.warnings}); }
 const overall=aggregate('portfolio','portfolio',asOf,tx,prices,includeClosed,debug); const account_summaries=groups(tx,r=>String(r.account_id)).map(g=>aggregate('account',g[0].account_id,asOf,g,prices,includeClosed,debug)); const asset_type_summaries=groups(tx.filter(t=>t.asset_type),r=>r.asset_type).map(g=>aggregate('asset_type',g[0].asset_type,asOf,g,prices,includeClosed,debug)); return c.json({overall, accounts:account_summaries, asset_types:asset_type_summaries, warnings:overall.warnings}); });
export default route;
