import { unzipSync } from 'fflate';
import { parseCsv } from './csv';
import type { MarketDataProvider, MarketPrice, ProviderResult } from './types';
import { sanitizeProviderError } from './types';
const up=(v:any)=>String(v??'').trim().toUpperCase();
const val=(r:Record<string,string>,...keys:string[])=>{ for(const k of keys){ const v=r[k]??r[k.toUpperCase()]; if(v!=null&&v!=='') return v; } return ''; };
const nseDate=(d:string)=>{const [y,m,day]=d.split('-');return `${day}${m}${y}`};
const ddMon=(d:string)=>{const dt=new Date(`${d}T00:00:00Z`);return `${String(dt.getUTCDate()).padStart(2,'0')}${dt.toLocaleString('en-US',{month:'short',timeZone:'UTC'}).toUpperCase()}${dt.getUTCFullYear()}`};
export function nseUdKiffUrl(date:string){ const file=`BhavCopy_NSE_CM_0_0_0_${nseDate(date)}_F_0000.csv.zip`; return `https://nsearchives.nseindia.com/content/cm/${file}`; }
export class NseBhavcopyProvider implements MarketDataProvider { name='nse_bhavcopy' as const; constructor(private fetcher:typeof fetch=fetch){} async fetchPrices({targetDate,assets,signal}:{targetDate:string;assets:any[];signal?:AbortSignal}):Promise<ProviderResult>{ try{ const res=await this.fetcher(nseUdKiffUrl(targetDate),{signal,headers:{accept:'application/zip,text/csv,*/*','user-agent':'KoteCash personal EOD price refresh'}} as any); if(res.status===404) return {status:'not_yet_published',prices:[],retryable:true,error:'NSE bhavcopy not published yet'}; if(!res.ok) return {status:'unavailable',prices:[],retryable:res.status>=500||res.status===429,error:`NSE download failed (${res.status})`}; const ct=res.headers.get('content-type')||''; const buf=new Uint8Array(await res.arrayBuffer()); if(buf.length<128) return {status:'unavailable',prices:[],retryable:true,error:'NSE payload was empty or too small'}; if(ct.includes('html')||buf[0]!==0x50||buf[1]!==0x4b) return {status:'unavailable',prices:[],retryable:true,error:'NSE response was not a ZIP file'}; const zip=unzipSync(buf); const entry=Object.entries(zip).find(([k])=>k.toLowerCase().endsWith('.csv')); if(!entry) return {status:'unavailable',prices:[],retryable:false,error:'NSE ZIP did not contain CSV'}; const text=new TextDecoder().decode(entry[1]); const rows=parseCsv(text); const wanted=new Map(assets.map(a=>[up(a.provider_symbol||a.symbol),a])); const bySym=new Map<string,MarketPrice>(); for(const r of rows){ const sym=up(val(r,'TckrSymb','SYMBOL')), series=up(val(r,'SctySrs','SERIES')), seg=up(val(r,'Sgmt','SEGMENT')); if(!sym||!wanted.has(sym)) continue; if(series&&series!=='EQ'&&series!=='BE'&&series!=='BZ') continue; if(seg&&seg!=='CM') continue; const closeRaw=val(r,'ClsPric','CLOSE_PRICE','CLOSE','Close'); const close=Number(closeRaw); const stamp=val(r,'TradDt','TIMESTAMP'); const td=stamp.slice(0,10) || targetDate; if(td!==targetDate && up(val(r,'TIMESTAMP'))!==ddMon(targetDate)) continue; if(!Number.isFinite(close)||close<=0) continue; const mp:MarketPrice={assetId:wanted.get(sym).id,symbol:sym,exchange:'NSE',close:String(close),currency:'INR',tradeDate:targetDate,providerTimestamp:targetDate,series,provider:this.name,sourceType:'official_close',providerSymbol:sym}; const old=bySym.get(sym); if(!old || (series==='EQ'&&old.series!=='EQ')) bySym.set(sym,mp); } return {status:'ok',prices:[...bySym.values()]}; }catch(e){ return {status:'unavailable',prices:[],retryable:true,error:sanitizeProviderError(e)}; } } }
